function QNO_TQ_SPEAR_2()
  QUESTID = LuaGetQuestID("QNO_TQ_SPEAR_2")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 89, 79)
  LuaSetDifferentString(1)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CH_SMITH")
  LuaInsertMissionOrCompleteNpc("NPC_CH_SMITH")
  LuaQuestInsertNpc(1, "NPC_CH_SMITH")
  LuaSetAchievementLimit(3)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_TQ_SPEAR_2_01", 1, "NPC_CH_SMITH", 1, 40, "ITEM_QNO_TQ_SPEAR_2_01", "MOB_TQ_ROYALSOLDIER_CLON", 10)
  InsertQuestMenuStringList("NPC_CH_SMITH", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_SMITH_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_TQ_SPEAR_2_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_TQ_SPEAR_2_03", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_TQ_SPEAR_2_04", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_TQ_SPEAR_2_05", "BASIC_MENUSTRING_ACCEPT_AFTER_ONE_CLEAR", "SN_TALK_QNO_TQ_SPEAR_2_02", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_TQ_SPEAR_2_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_TQ_SPEAR_2_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 3250000, 0, 100000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
