function QNO_CH_POTION_3()
  QUESTID = LuaGetQuestID("QNO_CH_POTION_3")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 6, 1)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CH_POTION")
  LuaInsertMissionOrCompleteNpc("NPC_CH_POTION")
  LuaQuestInsertNpc(1, "NPC_CH_POTION")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_CH_POTION_3", 2, "NPC_CH_POTION", 1, 15, "ITEM_QNO_CH_POTION_3_01", "MOB_CH_WATERGHOST_CLON", 25, "MOB_CH_WATERGHOST", 25)
  InsertQuestMenuStringList("NPC_CH_POTION", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_POTION_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_CH_POTION_3_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_CH_POTION_3_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_CH_POTION_3_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_CH_POTION_3_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_CH_POTION_3_05", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_CH_POTION_3_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_CH_POTION_3_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(1, 13650, 4000, 0, 1, "ITEM_ETC_MP_POTION_01", 50)
  LuaSetAchievedSkillPont(0)
end
