function QNO_CH_SPECIAL_3()
  QUESTID = LuaGetQuestID("QNO_CH_SPECIAL_3")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 18, 3)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CH_SPECIAL")
  LuaInsertMissionOrCompleteNpc("NPC_CH_SPECIAL")
  LuaQuestInsertNpc(1, "NPC_CH_SPECIAL")
  LuaSetAchievementLimit(1)
  LuaInsertDependancyQuests(1, "QNO_CH_SPECIAL_2")
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_CH_SPECIAL_3", 1, "NPC_CH_SPECIAL", 1, 140, "ITEM_QNO_CH_SPECIAL_2_01", "MOB_CH_WHITETIGER", 50)
  InsertQuestMenuStringList("NPC_CH_SPECIAL", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_SPECIAL_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_CH_SPECIAL_3_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_CH_SPECIAL_3_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_CH_SPECIAL_3_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_CH_SPECIAL_3_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_CH_SPECIAL_3_05", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_CH_SPECIAL_3_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_CH_SPECIAL_3_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(1, 186120, 20000, 0, 1, "ITEM_QNO_CH_SPECIAL_2_02", 1)
  LuaSetAchievedSkillPont(0)
end
