function QNO_SD_HW_021()
  QUESTID = LuaGetQuestID("QNO_SD_HW_021")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 105, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_EU_GENERAL", "NPC_SD_M_AREA_SENMUTE")
  LuaQuestInsertNpc(2, "NPC_EU_GENERAL", "NPC_SD_M_AREA_SENMUTE")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_SENMUTE")
  LuaInsertDependancyQuests(1, "QNO_EU_HWAN_2_6")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDialLogMissionData(QUESTID, 0, MISSION_TYPE_DIALOG, "SN_CON_QNO_SD_HW_021_1", 1, "SN_TALK_QNO_SD_HW_021_05")
  InsertQuestMenuStringList("NPC_EU_GENERAL", 5, "BASIC_MENUSTRING_GREETING", "SN_NPC_EU_GENERAL_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_HW_021_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_HW_021_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_HW_021_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_HW_021_04")
  InsertQuestMenuStringList("NPC_SD_M_AREA_SENMUTE", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_SENMUTE_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_HW_021_05")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 5412921, 0, 2450, 0, 0)
  LuaSetAchievedSkillPont(1100)
end
