function QNO_CH_HORSE_1()
  QUESTID = LuaGetQuestID("QNO_CH_HORSE_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 16, 6)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CH_HORSE")
  LuaInsertMissionOrCompleteNpc("NPC_CH_HORSE")
  LuaQuestInsertNpc(1, "NPC_CH_HORSE")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_CH_HORSE_1", 1, "MOB_CH_WHITETIGER", 0, MONSTER_CLASS_NORMAL, 30, 0)
  InsertQuestMenuStringList("NPC_CH_HORSE", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_HORSE_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_CH_HORSE_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_CH_HORSE_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_CH_HORSE_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_CH_HORSE_1_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_CH_HORSE_1_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_CH_HORSE_1_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 20020, 0, 4300, 0, 0)
  LuaSetAchievedSkillPont(0)
end
