function QNO_SD_NO_044()
  QUESTID = LuaGetQuestID("QNO_SD_NO_044")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 106, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_SD_M_AREA_AHHA", "NPC_SD_T_AREA_GUILD2")
  LuaQuestInsertNpc(2, "NPC_SD_M_AREA_AHHA", "NPC_SD_T_AREA_GUILD2")
  LuaInsertMissionOrCompleteNpc("NPC_SD_T_AREA_GUILD2")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDialLogMissionData(QUESTID, 0, MISSION_TYPE_DIALOG, "SN_CON_QNO_SD_NO_044_1", 1, "SN_TALK_QNO_SD_NO_044_05")
  InsertQuestMenuStringList("NPC_SD_M_AREA_AHHA", 5, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_AHHA_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_NO_044_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_NO_044_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_NO_044_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_NO_044_04")
  InsertQuestMenuStringList("NPC_SD_T_AREA_GUILD2", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_T_AREA_GUILD2_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_NO_044_05")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 5575309, 0, 2471, 0, 0)
  LuaSetAchievedSkillPont(1200)
end
