function QNO_WOF_TITLE_01()
  QUESTID = LuaGetQuestID("QNO_WOF_TITLE_01")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 1, 1)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CH_KISAENG3")
  LuaInsertMissionOrCompleteNpc("NPC_CH_KISAENG3")
  LuaQuestInsertNpc(1, "NPC_CH_KISAENG3")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_WOF_TITLE_01", 19, "MOB_CH_TIGERWOMAN", "MOB_OA_URUCHI", "MOB_KK_ISYUTARU", "MOB_EU_KERBEROS", "MOB_AM_IVY", "MOB_TK_BONELORD", "MOB_RM_TAHOMET", "MOB_RM_ROC_1", "MOB_TQ_WHITESNAKE", "MOB_CH_TIGERWOMAN_STR", "MOB_OA_URUCHI_STR", "MOB_KK_ISYUTARU_STR", "MOB_EU_KERBEROS_STR", "MOB_AM_IVY_STR", "MOB_TK_BONELORD_STR", "MOB_RM_TAHOMET_STR", "MOB_RM_ROC_1_STR", "MOB_TQ_WHITESNAKE_STR", "MOB_GM_IMMORTAL_ROC", 0, 50, 0, 1)
  InsertQuestMenuStringList("NPC_CH_KISAENG3", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_POTION_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_WOF_TITLE_01_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_WOF_TITLE_01_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_WOF_TITLE_01_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_WOF_TITLE_01_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_WOF_TITLE_01_05", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_WOF_TITLE_01_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_WOF_TITLE_01_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(1, 7200, 0, 0, 1, "ITEM_MALL_GLOBAL_CHATTING", 1)
  LuaSetAchievedSkillPont(0)
end
