function QNO_SD_RE_029()
  QUESTID = LuaGetQuestID("QNO_SD_RE_029")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 107, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_M_AREA_MERCHANT")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_MERCHANT")
  LuaQuestInsertNpc(1, "NPC_SD_M_AREA_MERCHANT")
  LuaInsertDependancyQuests(5, "QNO_SD_RE_017", "QNO_SD_RE_020", "QNO_SD_RE_023", "QNO_SD_RE_026", "QNO_SD_RE_028")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_SD_RE_029_1", 1, "NPC_SD_M_AREA_MERCHANT", 1, 100, "ITEM_QNO_SD_RE_029_1", "MOB_SD_EVILBUG", 100)
  InsertQuestMenuStringList("NPC_SD_M_AREA_MERCHANT", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_MERCHANT_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_RE_029_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_RE_029_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_RE_029_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_RE_029_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_RE_029_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_RE_029_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 11485137, 0, 4987, 0)
  LuaSetAchievedSkillPont(1800)
end
