function QNO_JUPITER_MAIN_006()
  QUESTID = LuaGetQuestID("QNO_JUPITER_MAIN_006")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 111, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_JUPITER_INVESTIGATION_02", "NPC_JUPITER_INVESTIGATION_03")
  LuaQuestInsertNpc(2, "NPC_JUPITER_INVESTIGATION_02", "NPC_JUPITER_INVESTIGATION_03")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_INVESTIGATION_03")
  LuaInsertDependancyQuests(1, "QNO_JUPITER_MAIN_032")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDialLogMissionData(QUESTID, 0, MISSION_TYPE_DIALOG, "SN_CON_QNO_JUPITER_MAIN_006_1", 1, "SN_TALK_QNO_JUPITER_MAIN_006_05")
  InsertQuestMenuStringList("NPC_JUPITER_INVESTIGATION_02", 5, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_INVESTIGATION_02_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_MAIN_006_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_MAIN_006_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_MAIN_006_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_MAIN_006_04")
  InsertQuestMenuStringList("NPC_JUPITER_INVESTIGATION_03", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_INVESTIGATION_03_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_MAIN_006_05")
end
