function QNO_CA_HORSE_2()
  QUESTID = LuaGetQuestID("QNO_CA_HORSE_2")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 29, 19)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CA_HORSE")
  LuaInsertMissionOrCompleteNpc("NPC_CA_HORSE")
  LuaQuestInsertNpc(1, "NPC_CA_HORSE")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_CA_HORSE_2", 1, "NPC_CA_HORSE", 1, 20, "ITEM_QNO_CA_HORSE_2_01", "MOB_AM_PUNISHER_CLON", 20)
  InsertQuestMenuStringList("NPC_CA_HORSE", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_CA_HORSE_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_CA_HORSE_2_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_CA_HORSE_2_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_CA_HORSE_2_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_CA_HORSE_2_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_CA_HORSE_2_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_CA_HORSE_2_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 486400, 7500, 15000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
