function QNO_CA_TREASURE_3()
  QUESTID = LuaGetQuestID("QNO_CA_TREASURE_3")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 34, 23)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_CA_WAREHOUSE", "NPC_CA_SMITH")
  LuaQuestInsertNpc(2, "NPC_CA_WAREHOUSE", "NPC_CA_SMITH")
  LuaInsertMissionOrCompleteNpc("NPC_CA_SMITH")
  LuaSetAchievementLimit(1)
  LuaInsertDependancyQuests(1, "QNO_CA_TREASURE_2")
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDialLogMissionData(QUESTID, 0, MISSION_TYPE_DIALOG, "SN_CON_QNO_CA_TREASURE_3", 1, "SN_TALK_QNO_CA_TREASURE_3_07")
  InsertQuestMenuStringList("NPC_CA_WAREHOUSE", 6, "BASIC_MENUSTRING_GREETING", "SN_NPC_CA_WAREHOUSE_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_CA_TREASURE_3_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_CA_TREASURE_3_04", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_CA_TREASURE_3_05", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_CA_TREASURE_3_06", "BASIC_MENUSTRING_MIDDLE_ACHIEVED", "SN_TALK_QNO_CA_TREASURE_3_08")
  InsertQuestMenuStringList("NPC_CA_SMITH", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_CA_SMITH_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_CA_TREASURE_3_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 4350, 150, 320, 0, 0)
  LuaSetAchievedSkillPont(0)
end
