function QNO_JUPITER_MAIN_037()
  QUESTID = LuaGetQuestID("QNO_JUPITER_MAIN_037")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 118, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_JUPITER_SOLDIER_19", "NPC_JUPITER_SOLDIER_18")
  LuaQuestInsertNpc(2, "NPC_JUPITER_SOLDIER_19", "NPC_JUPITER_SOLDIER_18")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_SOLDIER_18")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDialLogMissionData(QUESTID, 0, MISSION_TYPE_DIALOG, "SN_CON_QNO_JUPITER_MAIN_037_1", 1, "SN_TALK_QNO_JUPITER_MAIN_037_05")
  InsertQuestMenuStringList("NPC_JUPITER_SOLDIER_19", 5, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_19_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_MAIN_037_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_MAIN_037_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_MAIN_037_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_MAIN_037_04")
  InsertQuestMenuStringList("NPC_JUPITER_INVESTIGATION_01", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_18_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_MAIN_037_05")
end
