function QNO_TQ_ORNAMENT_1()
  QUESTID = LuaGetQuestID("QNO_TQ_ORNAMENT_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 94, 84)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CH_ACCESSORY")
  LuaInsertMissionOrCompleteNpc("NPC_CH_ACCESSORY")
  LuaQuestInsertNpc(1, "NPC_CH_ACCESSORY")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_TQ_ORNAMENT_1_01", 1, "NPC_CH_ACCESSORY", 1, 50, "ITEM_QNO_TQ_ORNAMENT_1_01", "MOB_TQ_SNAKEWOMAN_CLON", 20)
  InsertQuestMenuStringList("NPC_CH_ACCESSORY", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_ACCESSORY_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_TQ_ORNAMENT_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_TQ_ORNAMENT_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_TQ_ORNAMENT_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_TQ_ORNAMENT_1_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_TQ_ORNAMENT_1_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_TQ_ORNAMENT_1_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 8200100, 0, 66000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
