function QNO_SD_NO_050()
  QUESTID = LuaGetQuestID("QNO_SD_NO_050")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 108, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_M_AREA_HUNTER")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_HUNTER")
  LuaQuestInsertNpc(1, "NPC_SD_M_AREA_HUNTER")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 2)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_SD_NO_050_1", 1, "NPC_SD_M_AREA_HUNTER", 1, 30, "ITEM_QNO_SD_NO_050_1", "MOB_SD_COELACAN", 30)
  LuaSetCollectionItemMissionData(QUESTID, 1, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_SD_NO_050_2", 1, "NPC_SD_M_AREA_HUNTER", 1, 30, "ITEM_QNO_SD_NO_050_2", "MOB_SD_SANDWORM", 30)
  InsertQuestMenuStringList("NPC_SD_M_AREA_HUNTER", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_HUNTER_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_NO_050_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_NO_050_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_NO_050_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_NO_050_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_NO_050_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_NO_050_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 11829691, 0, 5031, 0, 0)
  LuaSetAchievedSkillPont(1900)
end
