function QNO_RM_YOUNGWOMAN1_1()
  QUESTID = LuaGetQuestID("QNO_RM_YOUNGWOMAN1_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 72, 62)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_RM_YOUNGWOMAN1")
  LuaInsertMissionOrCompleteNpc("NPC_RM_YOUNGWOMAN1")
  LuaQuestInsertNpc(1, "NPC_RM_YOUNGWOMAN1")
  LuaSetAchievementLimit(3)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_RM_YOUNGWOMAN1_1", 1, "MOB_RM_ROCKY_CLON", 0, MONSTER_CLASS_NORMAL, 500, 0)
  InsertQuestMenuStringList("NPC_RM_YOUNGWOMAN1", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_RM_YOUNGWOMAN1_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_RM_YOUNGWOMAN1_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_RM_YOUNGWOMAN1_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_RM_YOUNGWOMAN1_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_RM_YOUNGWOMAN1_1_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_RM_YOUNGWOMAN1_1_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_RM_YOUNGWOMAN1_1_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 7516000, 0, 311000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
