function QNO_JUPITER_SUB_025()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_025")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 113, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_INVESTIGATION_03")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_INVESTIGATION_03")
  LuaQuestInsertNpc(1, "NPC_JUPITER_INVESTIGATION_03")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 3)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_025_1", 1, "MOB_JUPITER_GRIFFIN", 0, 30, 0, 1)
  LuaSetMissionData_EX(QUESTID, 1, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_025_2", 1, "MOB_JUPITER_GRIFFIN_GUARD", 0, 50, 0, 1)
  LuaSetMissionData_EX(QUESTID, 2, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_025_3", 1, "MOB_JUPITER_GRIFFIN_IMMOTAL", 0, 50, 0, 1)
  InsertQuestMenuStringList("NPC_JUPITER_INVESTIGATION_03", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_INVESTIGATION_03_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_025_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_025_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_025_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_025_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_025_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_025_06")
end
