function QNO_SD_SU_022()
  QUESTID = LuaGetQuestID("QNO_SD_SU_022")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 105, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_M_AREA_EYPTSOLIDER_4")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_EYPTSOLIDER_4")
  LuaInsertDependancyQuests(1, "QNO_SD_SU_002")
  LuaQuestInsertNpc(1, "NPC_SD_M_AREA_EYPTSOLIDER_4")
  MISSION_TYPE_KILL_MONSTER = 2
  MONSTER_CLASS_CHAMPION = 1
  MONSTER_CLASS_NORMAL = 0
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_SD_SU_022_1", 1, "MOB_SD_AKER", 0, MONSTER_CLASS_NORMAL, 800, 0)
  InsertQuestMenuStringList("NPC_SD_M_AREA_EYPTSOLIDER_4", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_EYPTSOLIDER_4_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_SU_022_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_SU_022_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_SU_022_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_SU_022_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_SU_022_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_SU_022_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 8660675, 0, 39200, 0, 0)
  LuaSetAchievedSkillPont(850)
end
