function QNO_SD_NO_043()
  QUESTID = LuaGetQuestID("QNO_SD_NO_043")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 106, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_SD_M_AREA_SMITH", "NPC_SD_M_AREA_SPECIAL")
  LuaQuestInsertNpc(2, "NPC_SD_M_AREA_SMITH", "NPC_SD_M_AREA_SPECIAL")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_SPECIAL")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDeliverMissionData(QUESTID, 0, MISSION_TYPE_DELIVER_ITEM, "SN_CON_QNO_SD_NO_043_1", "NPC_SD_M_AREA_SPECIAL", 1, 1, "ITEM_QNO_SD_NO_043_1", 1, "SN_TALK_QNO_SD_NO_043_06")
  InsertQuestMenuStringList("NPC_SD_M_AREA_SMITH", 6, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_SMITH_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_NO_043_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_NO_043_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_NO_043_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_NO_043_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_SD_NO_043_05")
  InsertQuestMenuStringList("NPC_SD_M_AREA_SPECIAL", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_SPECIAL_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_NO_043_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 5575309, 0, 2471, 0, 0)
  LuaSetAchievedSkillPont(1200)
end
