function QNO_SD_HW_009()
  QUESTID = LuaGetQuestID("QNO_SD_HW_009")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 110, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_SD_M_AREA_SENMUTE", "NPC_SD_M_AREA_LENENUNE")
  LuaQuestInsertNpc(2, "NPC_SD_M_AREA_SENMUTE", "NPC_SD_M_AREA_LENENUNE")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_LENENUNE")
  LuaInsertDependancyQuestsOneClear(2, "QNO_SD_HW_019", "QNO_SD_HW_023")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDialLogMissionData(QUESTID, 0, MISSION_TYPE_DIALOG, "SN_CON_QNO_SD_HW_009_1", 1, "SN_TALK_QNO_SD_HW_009_05")
  InsertQuestMenuStringList("NPC_SD_M_AREA_SENMUTE", 5, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_SENMUTE_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_HW_009_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_HW_009_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_HW_009_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_HW_009_04")
  InsertQuestMenuStringList("NPC_SD_M_AREA_LENENUNE", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_LENENUNE_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_HW_009_05")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 6275059, 0, 2559, 0, 0)
  LuaSetAchievedSkillPont(1600)
end
