function QNO_SD_RE_019()
  QUESTID = LuaGetQuestID("QNO_SD_RE_019")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 107, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_T_AREA_POTION")
  LuaInsertMissionOrCompleteNpc("NPC_SD_T_AREA_POTION")
  LuaQuestInsertNpc(1, "NPC_SD_T_AREA_POTION")
  LuaInsertDependancyQuests(1, "QNO_SD_RE_018")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_SD_RE_019_1", 1, "NPC_SD_T_AREA_POTION", 1, 100, "ITEM_QNO_SD_RE_019_1", "MOB_SD_ACHNISH", 100)
  InsertQuestMenuStringList("NPC_SD_T_AREA_POTION", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_T_AREA_POTION_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_RE_019_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_RE_019_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_RE_019_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_RE_019_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_RE_019_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_RE_019_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 11485137, 0, 4987, 0)
  LuaSetAchievedSkillPont(1800)
end
