function QNO_SD_MA_023()
  QUESTID = LuaGetQuestID("QNO_SD_MA_023")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 107, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_M_AREA_LENENUNE")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_LENENUNE")
  LuaQuestInsertNpc(1, "NPC_SD_M_AREA_LENENUNE")
  LuaInsertDependancyQuests(1, "QNO_SD_MA_022")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 2)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_SD_MA_023_1", 1, "NPC_SD_M_AREA_LENENUNE", 1, 50, "ITEM_QNO_SD_MA_023_1", "MOB_SD_SANDBUG", 100)
  LuaSetCollectionItemMissionData(QUESTID, 1, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_SD_MA_023_2", 1, "NPC_SD_M_AREA_LENENUNE", 1, 50, "ITEM_QNO_SD_MA_023_2", "MOB_SD_COELACANTH", 100)
  InsertQuestMenuStringList("NPC_SD_M_AREA_LENENUNE", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_LENENUNE_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_MA_023_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_MA_023_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_MA_023_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_MA_023_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_MA_023_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_MA_023_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 22970275, 0, 4987, 0, 0)
  LuaSetAchievedSkillPont(2800)
end
