function QNO_SD_NO_031()
  QUESTID = LuaGetQuestID("QNO_SD_NO_031")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 104, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_M_AREA_SPECIAL2")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_SPECIAL2")
  LuaQuestInsertNpc(1, "NPC_SD_M_AREA_SPECIAL2")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_SD_NO_031_1", 1, "NPC_SD_M_AREA_SPECIAL2", 1, 50, "ITEM_QNO_SD_NO_031_1", "MOB_SD_URAEUS", 50)
  InsertQuestMenuStringList("NPC_SD_M_AREA_SPECIAL2", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_SPECIAL2_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_NO_031_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_NO_031_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_NO_031_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_NO_031_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_NO_031_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_NO_031_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 10510528, 0, 4856, 0, 0)
  LuaSetAchievedSkillPont(1500)
end
