function QNO_KT_PLUS_037()
  QUESTID = LuaGetQuestID("QNO_KT_PLUS_037")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 77, 72)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_TK_TUNNEL_NO")
  LuaInsertMissionOrCompleteNpc("NPC_TK_TUNNEL_NO")
  LuaQuestInsertNpc(1, "NPC_TK_TUNNEL_NO")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_KT_PLUS_037_1", 1, "MOB_TK_BONEMAGE_CLON", 0, MONSTER_CLASS_NORMAL, 300, 0)
  InsertQuestMenuStringList("NPC_TK_TUNNEL_NO", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_TK_TUNNEL_NO_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_KT_PLUS_037_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_KT_PLUS_037_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_KT_PLUS_037_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_KT_PLUS_037_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_KT_PLUS_037_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_KT_PLUS_037_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 14494000, 88000, 342000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
