function QNO_EU_HORSE_1()
  QUESTID = LuaGetQuestID("QNO_EU_HORSE_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 28, 18)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_EU_HORSE", "NPC_CA_HORSE")
  LuaQuestInsertNpc(2, "NPC_EU_HORSE", "NPC_CA_HORSE")
  LuaInsertMissionOrCompleteNpc("NPC_CA_HORSE")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDeliverMissionData(QUESTID, 0, MISSION_TYPE_DELIVER_ITEM, "SN_CON_QNO_EU_HORSE_1", "NPC_CA_HORSE", 1, 1, "ITEM_QNO_EU_HORSE_1_01", 1, "SN_TALK_QNO_EU_HORSE_1_05")
  InsertQuestMenuStringList("NPC_EU_HORSE", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_EU_HORSE_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_EU_HORSE_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_EU_HORSE_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_EU_HORSE_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_EU_HORSE_1_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_EU_HORSE_1_07", "BASIC_MENUSTRING_MIDDLE_ACHIEVED", "SN_TALK_QNO_EU_HORSE_1_06")
  InsertQuestMenuStringList("NPC_CA_HORSE", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_CA_HORSE_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_EU_HORSE_1_05")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 74000, 2700, 6000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
