function QNO_FW_RB1_011()
  QUESTID = LuaGetQuestID("QNO_FW_RB1_011")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 51, 51)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_KT_MINISTER")
  LuaInsertMissionOrCompleteNpc("NPC_KT_MINISTER")
  LuaQuestInsertNpc(1, "NPC_KT_MINISTER")
  LuaSetAchievementLimit(1)
  LuaSetDivideType(5)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_FW_RB1_011_1", 2, "NPC_KT_MINISTER", 1, 100, "ITEM_QNO_FW_RB1_011_1", "MOB_GOD_TOGUI_TOGUIDOLL_B1", 50, "MOB_GOD_TOGUI_TOGUIDOLL_B2", 50)
  InsertQuestMenuStringList("NPC_KT_MINISTER", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_KT_MINISTER_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_FW_RB1_011_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_FW_RB1_011_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_FW_RB1_011_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_FW_RB1_011_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_FW_RB1_011_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_FW_RB1_011_06")
  LuaSetMissionCompleteNum(0)
end
