function QNO_SD_MA_004()
  QUESTID = LuaGetQuestID("QNO_SD_MA_004")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 100, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_M_AREA_MANETO")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_MANETO")
  LuaQuestInsertNpc(1, "NPC_SD_M_AREA_MANETO")
  LuaInsertDependancyQuests(1, "QNO_SD_MA_003")
  LuaSetAchievementLimit(1)
  MISSION_TYPE_KILL_MONSTER = 2
  MONSTER_CLASS_CHAMPION = 1
  MONSTER_CLASS_NORMAL = 0
  LuaSetMissionDataSize(QUESTID, 2)
  LuaSetMissionData(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_SD_MA_004_1", 1, "MOB_SD_UNEG", 0, MONSTER_CLASS_NORMAL, 50, 0)
  LuaSetMissionData(QUESTID, 1, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_SD_MA_004_2", 1, "MOB_SD_SANDRAIDER", 0, MONSTER_CLASS_NORMAL, 50, 1)
  InsertQuestMenuStringList("NPC_SD_M_AREA_MANETO", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_MANETO_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_MA_004_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_MA_004_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_MA_004_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_MA_004_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_MA_004_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_MA_004_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 18676935, 0, 4681, 0, 0)
  LuaSetAchievedSkillPont(2100)
end
