function QNO_JUPITER_SUB_055()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_055")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 119, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_SOLDIER_02")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_SOLDIER_02")
  LuaQuestInsertNpc(1, "NPC_JUPITER_SOLDIER_02")
  LuaInsertDependancyQuests(1, "QNO_JUPITER_SUB_018")
  LuaSetAchievementLimit(0)
  LuaSetMissionDataSize(QUESTID, 2)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_055_1", 1, "MOB_JUPITER_BAAL_MODIFY_FANATICISM", 0, 250, 0, 1)
  LuaSetMissionData_EX(QUESTID, 1, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_055_2", 1, "MOB_JUPITER_BAAL_MODIFY_WATCH", 0, 250, 0, 1)
  InsertQuestMenuStringList("NPC_JUPITER_SOLDIER_02", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_02_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_055_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_055_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_055_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_055_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_055_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_055_06")
end
