function QNO_WC_WAREHOUSE_W_1()
  QUESTID = LuaGetQuestID("QNO_WC_WAREHOUSE_W_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 28, 18)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_WC_WAREHOUSE_W")
  LuaInsertMissionOrCompleteNpc("NPC_WC_WAREHOUSE_W")
  LuaQuestInsertNpc(1, "NPC_WC_WAREHOUSE_W")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_WC_WAREHOUSE_W_1", 2, "NPC_WC_WAREHOUSE_W", 1, 15, "ITEM_QNO_WC_WAREHOUSE_W_1", "MOB_WC_EARTHKING", 50, "MOB_WC_EARTHKING_CLON", 50)
  InsertQuestMenuStringList("NPC_WC_WAREHOUSE_W", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_WC_WAREHOUSE_W_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_WC_WAREHOUSE_W_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_WC_WAREHOUSE_W_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_WC_WAREHOUSE_W_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_WC_WAREHOUSE_W_1_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_WC_WAREHOUSE_W_1_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_WC_WAREHOUSE_W_1_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 42470, 0, 4000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
