function QNO_WOF_TITLE_02()
  QUESTID = LuaGetQuestID("QNO_WOF_TITLE_02")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 1, 1)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CH_KISAENG3")
  LuaInsertMissionOrCompleteNpc("NPC_CH_KISAENG3")
  LuaQuestInsertNpc(1, "NPC_CH_KISAENG3")
  LuaSetAchievementLimit(1)
  MISSION_TYPE_KILL_MONSTER = 9
  MONSTER_CLASS_CHAMPION = 1
  MONSTER_CLASS_UNIQUE = 0
  LuaSetMissionDataSize(QUESTID, 9)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_WOF_TITLE_02_01", 1, "MOB_CH_TIGERWOMAN", 0, 10, 0, 1)
  LuaSetMissionData_EX(QUESTID, 1, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_WOF_TITLE_02_02", 1, "MOB_EU_KERBEROS", 0, 10, 0, 1)
  LuaSetMissionData_EX(QUESTID, 2, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_WOF_TITLE_02_03", 1, "MOB_OA_URUCHI", 0, 10, 0, 1)
  LuaSetMissionData_EX(QUESTID, 3, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_WOF_TITLE_02_04", 1, "MOB_AM_IVY", 0, 10, 0, 1)
  LuaSetMissionData_EX(QUESTID, 4, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_WOF_TITLE_02_05", 1, "MOB_KK_ISYUTARU", 0, 10, 0, 1)
  LuaSetMissionData_EX(QUESTID, 5, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_WOF_TITLE_02_06", 1, "MOB_TK_BONELORD", 0, 10, 0, 1)
  LuaSetMissionData_EX(QUESTID, 6, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_WOF_TITLE_02_07", 1, "MOB_RM_TAHOMET", 0, 10, 0, 1)
  LuaSetMissionData_EX(QUESTID, 7, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_WOF_TITLE_02_08", 1, "MOB_TQ_WHITESNAKE", 0, 1, 0, 1)
  LuaSetMissionData_EX(QUESTID, 8, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_WOF_TITLE_02_09", 1, "MOB_RM_ROC", 0, 1, 0, 1)
  InsertQuestMenuStringList("NPC_CH_KISAENG3", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_POTION_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_WOF_TITLE_02_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_WOF_TITLE_02_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_WOF_TITLE_02_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_WOF_TITLE_02_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_WOF_TITLE_02_05", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_WOF_TITLE_02_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_WOF_TITLE_02_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(1, 7200, 0, 0, 1, "ITEM_MALL_GLOBAL_CHATTING", 1)
  LuaSetAchievedSkillPont(0)
end
