function QNO_SD_RE_009()
  QUESTID = LuaGetQuestID("QNO_SD_RE_009")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 104, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_T_AREA_ACCESSORY")
  LuaInsertMissionOrCompleteNpc("NPC_SD_T_AREA_ACCESSORY")
  LuaQuestInsertNpc(1, "NPC_SD_T_AREA_ACCESSORY")
  LuaInsertDependancyQuests(1, "QNO_SD_RE_008")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 2)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_SD_RE_009_1", 1, "NPC_SD_T_AREA_ACCESSORY", 1, 30, "ITEM_QNO_SD_RE_009_1", "MOB_SD_URAEUS", 50)
  LuaSetCollectionItemMissionData(QUESTID, 1, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_SD_RE_009_2", 1, "NPC_SD_T_AREA_ACCESSORY", 1, 50, "ITEM_QNO_SD_RE_009_2", "MOB_SD_BLOOD_HYENA", 100)
  InsertQuestMenuStringList("NPC_SD_T_AREA_ACCESSORY", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_T_AREA_ACCESSORY_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_RE_009_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_RE_009_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_RE_009_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_RE_009_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_RE_009_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_RE_009_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 10510528, 0, 4856, 0, 0)
  LuaSetAchievedSkillPont(1500)
end
