function QNO_WC_POTION_2()
  QUESTID = LuaGetQuestID("QNO_WC_POTION_2")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 32, 22)
  LuaSetDifferentString(1)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_WC_POTION")
  LuaInsertMissionOrCompleteNpc("NPC_WC_POTION")
  LuaQuestInsertNpc(1, "NPC_WC_POTION")
  LuaSetAchievementLimit(2)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_WC_POTION_2", 1, "NPC_WC_POTION", 1, 130, "ITEM_QNO_WC_POTION_2_01", "MOB_OA_SCORPION", 35)
  InsertQuestMenuStringList("NPC_WC_POTION", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_WC_POTION_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_WC_POTION_2_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_WC_POTION_2_04", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_WC_POTION_2_05", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_WC_POTION_2_06", "BASIC_MENUSTRING_ACCEPT_AFTER_ONE_CLEAR", "SN_TALK_QNO_WC_POTION_2_08", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_WC_POTION_2_07", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_WC_POTION_2_09")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 927800, 40000, 0, 0, 0)
  LuaSetAchievedSkillPont(0)
end
