function QNO_WC_ACCESSORY_2()
  QUESTID = LuaGetQuestID("QNO_WC_ACCESSORY_2")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 26, 16)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_WC_ACCESSORY")
  LuaInsertMissionOrCompleteNpc("NPC_WC_ACCESSORY")
  LuaQuestInsertNpc(1, "NPC_WC_ACCESSORY")
  LuaSetAchievementLimit(3)
  LuaInsertDependancyQuests(1, "QNO_WC_ACCESSORY_1")
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_WC_ACCESSORY_2", 2, "NPC_WC_ACCESSORY", 1, 140, "ITEM_QNO_WC_ACCESSORY_1", "MOB_WC_GUNPOWDERGHOST_CLON", 50, "MOB_WC_GUNPOWDERGHOST", 50)
  InsertQuestMenuStringList("NPC_WC_ACCESSORY", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_WC_ACCESSORY_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_WC_ACCESSORY_2_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_WC_ACCESSORY_2_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_WC_ACCESSORY_2_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_WC_ACCESSORY_2_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_WC_ACCESSORY_2_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_WC_ACCESSORY_2_08")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 293080, 20000, 34500, 0, 0)
  LuaSetAchievedSkillPont(0)
end
