function QNO_KT_PLUS_035()
  QUESTID = LuaGetQuestID("QNO_KT_PLUS_035")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 76, 71)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_KT_SMITH")
  LuaInsertMissionOrCompleteNpc("NPC_KT_SMITH")
  LuaQuestInsertNpc(1, "NPC_KT_SMITH")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_KT_PLUS_035_1", 1, "NPC_KT_SMITH", 1, 30, "ITEM_QNO_KT_PLUS_035_1", "MOB_TK_BONEHUNTER", 10)
  InsertQuestMenuStringList("NPC_KT_SMITH", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_KT_SMITH_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_KT_PLUS_035_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_KT_PLUS_035_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_KT_PLUS_035_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_KT_PLUS_035_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_KT_PLUS_035_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_KT_PLUS_035_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 14494000, 88000, 342000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
