function QNO_TQ_FINDFRIEND_1()
  QUESTID = LuaGetQuestID("QNO_TQ_FINDFRIEND_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 84, 74)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_CH_KISAENG5", "NPC_CH_EUROPE")
  LuaQuestInsertNpc(2, "NPC_CH_KISAENG5", "NPC_CH_EUROPE")
  LuaInsertMissionOrCompleteNpc("NPC_CH_EUROPE")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDialLogMissionData(QUESTID, 0, MISSION_TYPE_DIALOG, "SN_CON_QNO_TQ_FINDFRIEND_1_01", 1, "SN_TALK_QNO_TQ_FINDFRIEND_1_05")
  InsertQuestMenuStringList("NPC_CH_KISAENG5", 6, "BASIC_MENUSTRING_GREETING", "SN_QNO_RM_OLDWOMAN_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_TQ_FINDFRIEND_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_TQ_FINDFRIEND_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_TQ_FINDFRIEND_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_TQ_FINDFRIEND_1_04", "BASIC_MENUSTRING_MIDDLE_ACHIEVED", "SN_TALK_QNO_TQ_FINDFRIEND_1_06")
  InsertQuestMenuStringList("NPC_CH_EUROPE", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_EUROPE_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_TQ_FINDFRIEND_1_05")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 2583500, 0, 0, 0, 0)
  LuaSetAchievedSkillPont(0)
end
