function QNO_WC_SOLDIER_EA2_1()
  QUESTID = LuaGetQuestID("QNO_WC_SOLDIER_EA2_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 65, 55)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_WC_SOLDIER_EA2")
  LuaInsertMissionOrCompleteNpc("NPC_WC_SOLDIER_EA2")
  LuaQuestInsertNpc(1, "NPC_WC_SOLDIER_EA2")
  LuaSetAchievementLimit(3)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_WC_SOLDIER_EA2_1", 2, "MOB_DH_SOLDIEREARTHGHOST", "MOB_DH_SOLDIEREARTHGHOST_CLON", 0, 500, 0, 1)
  InsertQuestMenuStringList("NPC_WC_SOLDIER_EA2", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_WC_SOLDIER_EA2_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_WC_SOLDIER_EA2_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_WC_SOLDIER_EA2_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_WC_SOLDIER_EA2_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_WC_SOLDIER_EA2_1_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_WC_SOLDIER_EA2_1_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_WC_SOLDIER_EA2_1_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 7025100, 0, 275000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
