function QNO_KT_PLUS_039()
  QUESTID = LuaGetQuestID("QNO_KT_PLUS_039")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 80, 75)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_KT_ACCESSORY")
  LuaInsertMissionOrCompleteNpc("NPC_KT_ACCESSORY")
  LuaQuestInsertNpc(1, "NPC_KT_ACCESSORY")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_KT_PLUS_039_1", 1, "NPC_KT_ACCESSORY", 1, 30, "ITEM_QNO_KT_PLUS_039_1", "MOB_TK_BONEGENERAL", 10)
  InsertQuestMenuStringList("NPC_KT_ACCESSORY", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_KT_ACCESSORY_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_KT_PLUS_039_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_KT_PLUS_039_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_KT_PLUS_039_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_KT_PLUS_039_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_KT_PLUS_039_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_KT_PLUS_039_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 14494000, 90000, 340000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
