function QNO_SD_GU_002()
  QUESTID = LuaGetQuestID("QNO_SD_GU_002")
  LuaSetStartCodition(3, QSC_QUEST, QSC_LEVEL, QSC_SYSTEM, 105, 105)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_SD_M_AREA_HUNTER", "NPC_SD_GUILD_AGENT2")
  LuaQuestInsertNpc(2, "NPC_SD_M_AREA_HUNTER", "NPC_SD_GUILD_AGENT2")
  LuaInsertMissionOrCompleteNpc("NPC_SD_GUILD_AGENT2")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDisableQuest(1)
  LuaSetJobTypeStartCondition(1, OBJ_JOBSTATE_HUNTER, 1)
  LuaSetDialLogMissionData(QUESTID, 0, MISSION_TYPE_DIALOG, "SN_CON_QNO_SD_GU_002_1", 1, "SN_TALK_QNO_SD_GU_002_05")
  InsertQuestMenuStringList("NPC_SD_M_AREA_HUNTER", 5, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_HUNTER_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_GU_002_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_GU_002_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_GU_002_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_GU_002_04")
  InsertQuestMenuStringList("NPC_SD_GUILD_AGENT2", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_GUILD_AGENT2_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_GU_002_05")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 5412921, 0, 2340, 0, 0)
  LuaSetAchievedSkillPont(1100)
end
