function QNO_SD_NO_051()
  QUESTID = LuaGetQuestID("QNO_SD_NO_051")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 109, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_T_AREA_THIEF")
  LuaInsertMissionOrCompleteNpc("NPC_SD_T_AREA_THIEF")
  LuaQuestInsertNpc(1, "NPC_SD_T_AREA_THIEF")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_SD_NO_051_1", 1, "NPC_SD_T_AREA_THIEF", 1, 1, "ITEM_QNO_SD_NO_051_1", "MOB_SD_AKERU", 1)
  InsertQuestMenuStringList("NPC_SD_T_AREA_THIEF", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_T_AREA_THIEF_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_NO_051_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_NO_051_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_NO_051_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_NO_051_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_NO_051_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_NO_051_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 12184582, 0, 5075, 0, 0)
  LuaSetAchievedSkillPont(2000)
end
