function QNO_CH_GENARAL_SP_1()
  QUESTID = LuaGetQuestID("QNO_CH_GENARAL_SP_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 13, 3)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CH_GENARAL_SP")
  LuaInsertMissionOrCompleteNpc("NPC_CH_GENARAL_SP")
  LuaQuestInsertNpc(1, "NPC_CH_GENARAL_SP")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_CH_GENARAL_SP_1", 2, "MOB_CH_BANDIT_CLON", "MOB_CH_BANDIT", 0, 25, 0, 1)
  InsertQuestMenuStringList("NPC_CH_GENARAL_SP", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_GENARAL_SP_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_CH_GENARAL_SP_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_CH_GENARAL_SP_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_CH_GENARAL_SP_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_CH_GENARAL_SP_1_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_CH_GENARAL_SP_1_05", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_CH_GENARAL_SP_1_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_CH_GENARAL_SP_1_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(1, 14500, 0, 0, 1, "ITEM_ETC_ALL_POTION_01", 50)
  LuaSetAchievedSkillPont(0)
end
