function QNO_SD_SU_045()
  QUESTID = LuaGetQuestID("QNO_SD_SU_045")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 100, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_SD_M_AREA_SENMUTE", "NPC_SD_M_AREA_EYPTSOLIDER_3")
  LuaQuestInsertNpc(2, "NPC_SD_M_AREA_SENMUTE", "NPC_SD_M_AREA_EYPTSOLIDER_3")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_EYPTSOLIDER_3")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDialLogMissionData(QUESTID, 0, MISSION_TYPE_DIALOG, "SN_CON_QNO_SD_SU_045_1", 1, "SN_TALK_QNO_SD_SU_045_05")
  InsertQuestMenuStringList("NPC_SD_M_AREA_SENMUTE", 5, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_SENMUTE_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_SU_045_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_SU_045_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_SU_045_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_SU_045_04")
  InsertQuestMenuStringList("NPC_SD_M_AREA_EYPTSOLIDER_3", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_EYPTSOLIDER_3_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_SU_045_05")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 466923, 0, 2340, 0, 0)
  LuaSetAchievedSkillPont(150)
end
