function QNO_JUPITER_SUB_056()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_056")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 119, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_SOLDIER_04")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_SOLDIER_04")
  LuaQuestInsertNpc(1, "NPC_JUPITER_SOLDIER_04")
  LuaInsertDependancyQuests(1, "QNO_JUPITER_SUB_017")
  LuaSetAchievementLimit(0)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_056_1", 1, "MOB_JUPITER_HELL_ENCHANTRESS", 0, 450, 0, 1)
  InsertQuestMenuStringList("NPC_JUPITER_SOLDIER_04", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_04_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_056_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_056_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_056_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_056_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_056_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_056_06")
end
