function QNO_WC_SOLDIER_WE2_1()
  QUESTID = LuaGetQuestID("QNO_WC_SOLDIER_WE2_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 33, 23)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_WC_SOLDIER_WE2")
  LuaInsertMissionOrCompleteNpc("NPC_WC_SOLDIER_WE2")
  LuaQuestInsertNpc(1, "NPC_WC_SOLDIER_WE2")
  LuaSetAchievementLimit(3)
  LuaSetDifferentString(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_WC_SOLDIER_WE2_1", 2, "MOB_OA_DESERTTRUNKZ_CLON2", "MOB_OA_DESERTTRUNKZ", 0, 500, 0, 1)
  InsertQuestMenuStringList("NPC_WC_SOLDIER_WE2", 9, "BASIC_MENUSTRING_GREETING", "SN_NPC_WC_SOLDIER_WE2_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_WC_SOLDIER_WE2_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_WC_SOLDIER_WE2_1_03", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_WC_SOLDIER_WE2_1_04", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_WC_SOLDIER_WE2_1_05", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_WC_SOLDIER_WE2_1_06", "BASIC_MENUSTRING_ACCEPT_AFTER_ONE_CLEAR", "SN_TALK_QNO_WC_SOLDIER_WE2_1_08", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_WC_SOLDIER_WE2_1_07", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_WC_SOLDIER_WE2_1_09")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(1, 1461000, 0, 0, 1, "ITEM_QNO_WC_SOLDIER_WE2_1_01", 1)
  LuaSetAchievedSkillPont(0)
end
