function QNO_JUPITER_SUB_075()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_075")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 116, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_SOLDIER_22")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_SOLDIER_22")
  LuaInsertDependancyQuests(1, "QNO_JUPITER_SUB_074")
  LuaQuestInsertNpc(1, "NPC_JUPITER_SOLDIER_22")
  LuaSetAchievementLimit(0)
  LuaSetMissionDataSize(QUESTID, 2)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_075_1", 1, "MOB_JUPITER_BAAL_FANATICISM_CLONE", 0, 200, 0, 1)
  LuaSetMissionData_EX(QUESTID, 1, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_075_2", 1, "MOB_JUPITER_ANGER_FANATICISM_CLONE", 0, 200, 0, 1)
  InsertQuestMenuStringList("NPC_JUPITER_SOLDIER_22", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_22_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_075_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_075_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_075_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_075_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_075_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_075_06")
end
