function QNO_EU_EASTEU_6()
  QUESTID = LuaGetQuestID("QNO_EU_EASTEU_6")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 13, 3)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_EU_WITCH")
  LuaInsertMissionOrCompleteNpc("NPC_EU_WITCH")
  LuaQuestInsertNpc(1, "NPC_EU_WITCH")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_EU_EASTEU_6", 1, "NPC_EU_WITCH", 1, 1, "ITEM_QNO_EU_EASTEU_6_01", "MOB_EU_KYKLOPES_CLON", 1.4)
  InsertQuestMenuStringList("NPC_EU_WITCH", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_EU_WITCH_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_EU_EASTEU_6_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_EU_EASTEU_6_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_EU_EASTEU_6_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_EU_EASTEU_6_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_EU_EASTEU_6_05", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_EU_EASTEU_6_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_EU_EASTEU_6_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(1, 33660, 5000, 0, 1, "ITEM_QNO_EU_EASTEU_6_02", 1)
  LuaSetAchievedSkillPont(0)
end
