function QNO_JUPITER_SUB_052()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_052")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 117, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_SOLDIER_02")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_SOLDIER_02")
  LuaQuestInsertNpc(1, "NPC_JUPITER_SOLDIER_02")
  LuaInsertDependancyQuests(1, "QNO_JUPITER_MAIN_021")
  LuaSetAchievementLimit(0)
  LuaSetMissionDataSize(QUESTID, 2)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_052_1", 1, "MOB_JUPITER_BAAL_CURSING_FANATICISM", 0, 200, 0, 1)
  LuaSetMissionData_EX(QUESTID, 1, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_052_2", 1, "MOB_JUPITER_BAAL_CURSING_WATCH", 0, 200, 0, 1)
  InsertQuestMenuStringList("NPC_JUPITER_SOLDIER_02", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_02_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_052_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_052_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_052_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_052_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_052_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_052_06")
end
