function QNO_KT_PLUS_012()
  QUESTID = LuaGetQuestID("QNO_KT_PLUS_012")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 49, 44)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_KT_ARMOR")
  LuaInsertMissionOrCompleteNpc("NPC_KT_ARMOR")
  LuaQuestInsertNpc(1, "NPC_KT_ARMOR")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_KT_PLUS_012_1", 1, "NPC_KT_ARMOR", 1, 70, "ITEM_QNO_KT_PLUS_012_1", "MOB_KT_MUJIGI", 25)
  InsertQuestMenuStringList("NPC_KT_ARMOR", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_KT_ARMOR_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_KT_PLUS_012_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_KT_PLUS_012_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_KT_PLUS_012_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_KT_PLUS_012_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_KT_PLUS_012_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_KT_PLUS_012_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 953500, 15000, 79000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
