function QNO_SD_RE_044()
  QUESTID = LuaGetQuestID("QNO_SD_RE_044")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 110, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_SD_M_AREA_HUNTER", "NPC_SD_M_AREA_SENMUTE")
  LuaQuestInsertNpc(2, "NPC_SD_M_AREA_HUNTER", "NPC_SD_M_AREA_SENMUTE")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_SENMUTE")
  LuaInsertDependancyQuests(1, "QNO_SD_RE_034")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDialLogMissionData(QUESTID, 0, MISSION_TYPE_DIALOG, "SN_CON_QNO_SD_RE_044_1", 1, "SN_TALK_QNO_SD_RE_044_05")
  InsertQuestMenuStringList("NPC_SD_M_AREA_HUNTER", 5, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_HUNTER_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_RE_044_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_RE_044_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_RE_044_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_RE_044_04")
  InsertQuestMenuStringList("NPC_SD_M_AREA_SENMUTE", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_SENMUTE_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_RE_044_05")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 6275059, 0, 2559, 0, 0)
  LuaSetAchievedSkillPont(1600)
end
