function QNO_SD_HW_005()
  QUESTID = LuaGetQuestID("QNO_SD_HW_005")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 105, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_M_AREA_LENENUNE")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_LENENUNE")
  LuaQuestInsertNpc(1, "NPC_SD_M_AREA_LENENUNE")
  LuaInsertDependancyQuests(1, "QNO_SD_HW_004")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_SD_HW_005_1", 3, "NPC_SD_M_AREA_LENENUNE", 1, 100, "ITEM_QNO_SD_HW_005_1", "MOB_SD_TELBASTA_2", 100, "MOB_SD_BASTET_2", 100, "MOB_SD_BAST_2", 100)
  InsertQuestMenuStringList("NPC_SD_M_AREA_LENENUNE", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_LENENUNE_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_HW_005_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_HW_005_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_HW_005_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_HW_005_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_HW_005_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_HW_005_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 10825843, 0, 4900, 0, 0)
  LuaSetAchievedSkillPont(1600)
end
