function QNO_JUPITER_MAIN_021()
  QUESTID = LuaGetQuestID("QNO_JUPITER_MAIN_021")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 118, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_INVESTIGATION_01")
  LuaQuestInsertNpc(1, "NPC_JUPITER_INVESTIGATION_01")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_INVESTIGATION_01")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_JUPITER_MAIN_021_1", 15, "NPC_JUPITER_INVESTIGATION_01", 1, 200, "ITEM_QNO_JUPITER_MAIN_021_1", "MOB_JUPITER_BAAL_FANATICISM", 40, "MOB_JUPITER_CRUEL_FANATICISM", 40, "MOB_JUPITER_WILD_FANATICISM", 40, "MOB_JUPITER_RUIN_WATCHER", 40, "MOB_JUPITER_RUIN_CUTTER", 40, "MOB_JUPITER_HELL_BLOODDOG", 40, "MOB_JUPITER_HELL_BLOODWATCH", 40, "MOB_JUPITER_HELL_WATCH", 40, "MOB_JUPITER_HELL_PROTECTION", 40, "MOB_JUPITER_HELL_SERPENT", 40, "MOB_JUPITER_BAAL_CURSING_FANATICISM", 40, "MOB_JUPITER_BAAL_CURSING_WATCH", 40, "MOB_JUPITER_BAAL_MODIFY_FANATICISM", 40, "MOB_JUPITER_BAAL_MODIFY_WATCH", 40, "MOB_JUPITER_HELL_ENCHANTRESS", 40)
  InsertQuestMenuStringList("NPC_JUPITER_INVESTIGATION_01", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_INVESTIGATION_01_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_MAIN_021_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_MAIN_021_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_MAIN_021_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_MAIN_021_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_MAIN_021_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_MAIN_021_06")
end
