function QNO_RM_SLAVE1_2()
  QUESTID = LuaGetQuestID("QNO_RM_SLAVE1_2")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 85, 75)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_RM_SLAVE1")
  LuaInsertMissionOrCompleteNpc("NPC_RM_SLAVE1")
  LuaQuestInsertNpc(1, "NPC_RM_SLAVE1")
  LuaSetAchievementLimit(3)
  LuaSetDifferentString(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_RM_SLAVE1_2", 1, "MOB_RM_WINGTRIBESPEAR_CLON", 0, MONSTER_CLASS_NORMAL, 500, 0)
  InsertQuestMenuStringList("NPC_RM_SLAVE1", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_RM_SLAVE1_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_RM_SLAVE1_2_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_RM_SLAVE1_2_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_RM_SLAVE1_2_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_RM_SLAVE1_2_04", "BASIC_MENUSTRING_ACCEPT_AFTER_ONE_CLEAR", "SN_TALK_QNO_RM_SLAVE1_2_07", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_RM_SLAVE1_2_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_RM_SLAVE1_2_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 3945000, 0, 145000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
