function QNO_WC_GENARAL_BO_1()
  QUESTID = LuaGetQuestID("QNO_WC_GENARAL_BO_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 67, 57)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_WC_GENARAL_BO")
  LuaInsertMissionOrCompleteNpc("NPC_WC_GENARAL_BO")
  LuaQuestInsertNpc(1, "NPC_WC_GENARAL_BO")
  LuaSetAchievementLimit(3)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_WC_GENARAL_BO_1", 2, "NPC_WC_GENARAL_BO", 1, 100, "ITEM_QNO_WC_GENARAL_BO_1", "MOB_DH_BLINDMON_CLON", 20, "MOB_DH_BLINDMON", 20)
  InsertQuestMenuStringList("NPC_WC_GENARAL_BO", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_WC_GENARAL_BO_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_WC_GENARAL_BO_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_WC_GENARAL_BO_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_WC_GENARAL_BO_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_WC_GENARAL_BO_1_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_WC_GENARAL_BO_1_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_WC_GENARAL_BO_1_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 7575100, 0, 0, 0, 0)
  LuaSetAchievedSkillPont(0)
end
