function QNO_SD_GU_003()
  QUESTID = LuaGetQuestID("QNO_SD_GU_003")
  LuaSetStartCodition(3, QSC_QUEST, QSC_LEVEL, QSC_SYSTEM, 105, 105)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_SD_T_AREA_THIEF", "NPC_SD_GUILD_AGENT")
  LuaQuestInsertNpc(2, "NPC_SD_T_AREA_THIEF", "NPC_SD_GUILD_AGENT")
  LuaInsertMissionOrCompleteNpc("NPC_SD_GUILD_AGENT")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetJobTypeStartCondition(1, OBJ_JOBSTATE_ROBBER, 1)
  LuaSetDisableQuest(1)
  LuaSetDialLogMissionData(QUESTID, 0, MISSION_TYPE_DIALOG, "SN_CON_QNO_SD_GU_003_1", 1, "SN_TALK_QNO_SD_GU_003_05")
  InsertQuestMenuStringList("NPC_SD_T_AREA_THIEF", 5, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_T_AREA_THIEF_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_GU_003_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_GU_003_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_GU_003_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_GU_003_04")
  InsertQuestMenuStringList("NPC_SD_GUILD_AGENT", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_GUILD_AGENT_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_GU_003_05")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 5412921, 0, 2340, 0, 0)
  LuaSetAchievedSkillPont(1100)
end
