function QNO_WC_DOCTOR_1()
  QUESTID = LuaGetQuestID("QNO_WC_DOCTOR_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 34, 24)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_WC_DOCTOR")
  LuaInsertMissionOrCompleteNpc("NPC_WC_DOCTOR")
  LuaQuestInsertNpc(1, "NPC_WC_DOCTOR")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_WC_DOCTOR_1", 4, "NPC_WC_DOCTOR", 1, 250, "ITEM_QNO_WC_DOCTOR_1", "MOB_OA_BLACKROBBER", 50, "MOB_OA_BLACKROBBER_CLON", 50, "MOB_OA_BLACKROBBERARCHER", 50, "MOB_OA_BLACKROBBERARCHER_CLON", 50)
  InsertQuestMenuStringList("NPC_WC_DOCTOR", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_WC_DOCTOR_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_WC_DOCTOR_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_WC_DOCTOR_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_WC_DOCTOR_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_WC_DOCTOR_1_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_WC_DOCTOR_1_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_WC_DOCTOR_1_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 1023000, 0, 250000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
