function QNO_JUPITER_SUB_072()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_072")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 115, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_SOLDIER_21")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_SOLDIER_21")
  LuaQuestInsertNpc(1, "NPC_JUPITER_SOLDIER_21")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_072_1", 1, "MOB_JUPITER_RUIN_WATCHER_CLONE", 0, 500, 0, 1)
  InsertQuestMenuStringList("NPC_JUPITER_SOLDIER_21", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_21_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_072_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_072_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_072_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_072_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_072_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_072_06")
end
