function QNO_WC_HORSE_2()
  QUESTID = LuaGetQuestID("QNO_WC_HORSE_2")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 23, 13)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_WC_HORSE")
  LuaInsertMissionOrCompleteNpc("NPC_WC_HORSE")
  LuaQuestInsertNpc(1, "NPC_WC_HORSE")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_WC_HORSE_2", 2, "NPC_WC_HORSE", 1, 50, "ITEM_QNO_WC_HORSE_2_01", "MOB_WC_DEMONHORSE", 14, "MOB_WC_DEMONHORSE_CLON", 14)
  InsertQuestMenuStringList("NPC_WC_HORSE", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_WC_HORSE_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_WC_HORSE_2_02", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_WC_HORSE_2_03", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_WC_HORSE_2_04", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_WC_HORSE_2_05", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_WC_HORSE_2_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_WC_HORSE_2_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 326000, 25000, 35000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
