function QNO_TQ_PIETY_1()
  QUESTID = LuaGetQuestID("QNO_TQ_PIETY_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 94, 84)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CH_SOLDIER_EM1")
  LuaInsertMissionOrCompleteNpc("NPC_CH_SOLDIER_EM1")
  LuaQuestInsertNpc(1, "NPC_CH_SOLDIER_EM1")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_TQ_PIETY_1_01", 1, "NPC_CH_SOLDIER_EM1", 1, 120, "ITEM_QNO_TQ_PIETY_1_01", "MOB_TQ_SNAKEDEMON_CLON2", 25)
  InsertQuestMenuStringList("NPC_CH_SOLDIER_EM1", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_SOLDIER_EM1_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_TQ_PIETY_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_TQ_PIETY_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_TQ_PIETY_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_TQ_PIETY_1_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_TQ_PIETY_1_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_TQ_PIETY_1_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 11200200, 35000, 190000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
