function QNO_WC_SOLDIER_WE1_1()
  QUESTID = LuaGetQuestID("QNO_WC_SOLDIER_WE1_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 33, 23)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_WC_SOLDIER_WE1")
  LuaInsertMissionOrCompleteNpc("NPC_WC_SOLDIER_WE1")
  LuaQuestInsertNpc(1, "NPC_WC_SOLDIER_WE1")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_WC_SOLDIER_WE1_1", 2, "NPC_WC_SOLDIER_WE1", 1, 1, "ITEM_QNO_WC_SOLDIER_WE1_1_01", "MOB_OA_ONG_CLON", 0.5, "MOB_OA_ONG", 0.5)
  InsertQuestMenuStringList("NPC_WC_SOLDIER_WE1", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_WC_SOLDIER_WE1_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_WC_SOLDIER_WE1_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_WC_SOLDIER_WE1_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_WC_SOLDIER_WE1_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_WC_SOLDIER_WE1_1_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_WC_SOLDIER_WE1_1_05", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_WC_SOLDIER_WE1_1_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_WC_SOLDIER_WE1_1_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(5, 257360, 12500, 0, 1, "ITEM_ETC_MP_POTION_03", 50, 1, "ITEM_ETC_MP_POTION_03", 50, 1, "ITEM_ETC_MP_POTION_03", 50, 1, "ITEM_ETC_MP_POTION_03", 50, 1, "ITEM_ETC_MP_POTION_03", 50)
  LuaSetAchievedSkillPont(0)
end
