function QNO_WC_SOLDIER_EA2_2()
  QUESTID = LuaGetQuestID("QNO_WC_SOLDIER_EA2_2")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 23, 13)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_WC_SOLDIER_EA2")
  LuaInsertMissionOrCompleteNpc("NPC_WC_SOLDIER_EA2")
  LuaInsertDependancyQuests(1, "QNO_WC_SOLDIER_EA1_1")
  LuaQuestInsertNpc(1, "NPC_WC_SOLDIER_EA2")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_WC_SOLDIER_EA2_2", 1, "NPC_WC_SOLDIER_EA2", 1, 130, "ITEM_QNO_WC_SOLDIER_EA2_2_01", "MOB_WC_HYUNGNO_CLON", 25)
  InsertQuestMenuStringList("NPC_WC_SOLDIER_EA2", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_WC_SOLDIER_EA2_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_WC_SOLDIER_EA2_2_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_WC_SOLDIER_EA2_2_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_WC_SOLDIER_EA2_2_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_WC_SOLDIER_EA2_2_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_WC_SOLDIER_EA2_2_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_WC_SOLDIER_EA2_2_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 573000, 40000, 0, 0, 0)
  LuaSetAchievedSkillPont(0)
end
