function QNO_EU_CONS_12()
  QUESTID = LuaGetQuestID("QNO_EU_CONS_12")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 10, 1)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_EU_SPECIAL")
  LuaInsertMissionOrCompleteNpc("NPC_EU_SPECIAL")
  LuaQuestInsertNpc(1, "NPC_EU_SPECIAL")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_EU_CONS_12", 1, "NPC_EU_SPECIAL", 1, 15, "ITEM_QNO_EU_CONS_12_01", "MOB_EU_BARPOLLE", 25)
  InsertQuestMenuStringList("NPC_EU_SPECIAL", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_EU_SPECIAL_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_EU_CONS_12_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_EU_CONS_12_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_EU_CONS_12_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_EU_CONS_12_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_EU_CONS_12_05", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_EU_CONS_12_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_EU_CONS_12_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(1, 20680, 4000, 0, 1, "ITEM_QNO_EU_CONS_12_02", 1)
  LuaSetAchievedSkillPont(0)
end
