function QNO_KT_PLUS_040()
  QUESTID = LuaGetQuestID("QNO_KT_PLUS_040")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 78, 73)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_KT_FERRY")
  LuaInsertMissionOrCompleteNpc("NPC_KT_FERRY")
  LuaQuestInsertNpc(1, "NPC_KT_FERRY")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_KT_PLUS_040_1", 1, "MOB_TK_BONEMAGE", 0, MONSTER_CLASS_NORMAL, 300, 0)
  InsertQuestMenuStringList("NPC_KT_FERRY", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_KT_FERRY_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_KT_PLUS_040_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_KT_PLUS_040_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_KT_PLUS_040_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_KT_PLUS_040_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_KT_PLUS_040_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_KT_PLUS_040_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 14494000, 90000, 340000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
