function QNO_KT_PLUS_003()
  QUESTID = LuaGetQuestID("QNO_KT_PLUS_003")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 48, 43)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_KT_SOLDIER_EM1")
  LuaInsertMissionOrCompleteNpc("NPC_KT_SOLDIER_EM1")
  LuaQuestInsertNpc(1, "NPC_KT_SOLDIER_EM1")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_KT_PLUS_003_1", 1, "NPC_KT_SOLDIER_EM1", 1, 30, "ITEM_QNO_KT_PLUS_003_1", "MOB_KT_WHITESPIDER", 10)
  InsertQuestMenuStringList("NPC_KT_SOLDIER_EM1", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_KT_SOLDIER_EM1_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_KT_PLUS_003_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_KT_PLUS_003_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_KT_PLUS_003_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_KT_PLUS_003_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_KT_PLUS_003_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_KT_PLUS_003_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 953500, 20000, 74000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
