function QNO_JUPITER_SUB_015()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_015")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 120, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_SOLDIER_05")
  LuaQuestInsertNpc(1, "NPC_JUPITER_SOLDIER_05")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_SOLDIER_05")
  LuaInsertDependancyQuests(1, "QNO_JUPITER_SUB_014")
  LuaSetAchievementLimit(0)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_JUPITER_SUB_015_1", 2, "NPC_JUPITER_SOLDIER_05", 1, 200, "ITEM_QNO_JUPITER_SUB_015_1", "MOB_JUPITER_HELL_BLOODDOG", 40.8, "MOB_JUPITER_HELL_BLOODWATCH", 40.8)
  InsertQuestMenuStringList("NPC_JUPITER_SOLDIER_05", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_05_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_015_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_015_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_015_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_015_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_015_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_015_06")
end
