function QNO_JUPITER_SUB_059()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_059")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 111, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_SOLDIER_20")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_SOLDIER_20")
  LuaInsertDependancyQuests(1, "QNO_JUPITER_SUB_058")
  LuaQuestInsertNpc(1, "NPC_JUPITER_SOLDIER_20")
  LuaSetAchievementLimit(0)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_059_1", 1, "MOB_JUPITER_TEMPLE_PROTECTION_CLONE", 0, 400, 0, 1)
  InsertQuestMenuStringList("NPC_JUPITER_SOLDIER_20", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_20_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_059_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_059_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_059_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_059_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_059_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_059_06")
end
