function QNO_EU_CONS_8()
  QUESTID = LuaGetQuestID("QNO_EU_CONS_8")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 7, 1)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_EU_UNION1")
  LuaInsertMissionOrCompleteNpc("NPC_EU_UNION1")
  LuaInsertDependancyQuests(1, "QNO_EU_CONS_7")
  LuaQuestInsertNpc(1, "NPC_EU_UNION1")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_EU_CONS_8", 1, "MOB_EU_BAROI_CLON", 0, MONSTER_CLASS_NORMAL, 25, 0)
  InsertQuestMenuStringList("NPC_EU_UNION1", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_EU_UNION1_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_EU_CONS_8_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_EU_CONS_8_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_EU_CONS_8_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_EU_CONS_8_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_EU_CONS_8_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_EU_CONS_8_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 8250, 2000, 1500, 0, 0)
  LuaSetAchievedSkillPont(0)
end
