function QNO_KT_SOLDIER_SO1_1()
  QUESTID = LuaGetQuestID("QNO_KT_SOLDIER_SO1_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 47, 37)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_KT_SOLDIER_SO1")
  LuaInsertMissionOrCompleteNpc("NPC_KT_SOLDIER_SO1")
  LuaQuestInsertNpc(1, "NPC_KT_SOLDIER_SO1")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_KT_SOLDIER_SO1_1", 2, "MOB_KT_WHITESPIDER_CLON", "MOB_KT_WHITESPIDER", 0, 500, 0, 1)
  InsertQuestMenuStringList("NPC_KT_SOLDIER_SO1", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_KT_SOLDIER_SO1_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_KT_SOLDIER_SO1_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_KT_SOLDIER_SO1_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_KT_SOLDIER_SO1_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_KT_SOLDIER_SO1_1_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_KT_SOLDIER_SO1_1_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_KT_SOLDIER_SO1_1_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 1242000, 11300, 0, 0, 0)
  LuaSetAchievedSkillPont(0)
end
