function QNO_SD_RE_008()
  QUESTID = LuaGetQuestID("QNO_SD_RE_008")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 104, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_SD_M_AREA_HUNTER", "NPC_SD_T_AREA_ACCESSORY")
  LuaQuestInsertNpc(2, "NPC_SD_M_AREA_HUNTER", "NPC_SD_T_AREA_ACCESSORY")
  LuaInsertMissionOrCompleteNpc("NPC_SD_T_AREA_ACCESSORY")
  LuaInsertDependancyQuests(1, "QNO_SD_RE_007")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDialLogMissionData(QUESTID, 0, MISSION_TYPE_DIALOG, "SN_CON_QNO_SD_RE_008_1", 1, "SN_TALK_QNO_SD_RE_008_05")
  InsertQuestMenuStringList("NPC_SD_M_AREA_HUNTER", 5, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_HUNTER_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_RE_008_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_RE_008_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_RE_008_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_RE_008_04")
  InsertQuestMenuStringList("NPC_SD_T_AREA_ACCESSORY", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_T_AREA_ACCESSORY_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_RE_008_05")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 5255264, 0, 2428, 0, 0)
  LuaSetAchievedSkillPont(1000)
end
