function QNO_KT_PLUS_009()
  QUESTID = LuaGetQuestID("QNO_KT_PLUS_009")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 49, 44)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_KT_DESIGNER")
  LuaInsertMissionOrCompleteNpc("NPC_KT_DESIGNER")
  LuaQuestInsertNpc(1, "NPC_KT_DESIGNER")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_KT_PLUS_009_1", 1, "MOB_KT_MUJIGI", 0, MONSTER_CLASS_NORMAL, 300, 0)
  InsertQuestMenuStringList("NPC_KT_DESIGNER", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_KT_DESIGNER_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_KT_PLUS_009_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_KT_PLUS_009_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_KT_PLUS_009_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_KT_PLUS_009_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_KT_PLUS_009_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_KT_PLUS_009_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 953500, 15000, 79000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
