function QNO_RM_YOUNGWOMAN2_1()
  QUESTID = LuaGetQuestID("QNO_RM_YOUNGWOMAN2_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 78, 68)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_RM_YOUNGWOMAN2")
  LuaInsertMissionOrCompleteNpc("NPC_RM_YOUNGWOMAN2")
  LuaQuestInsertNpc(1, "NPC_RM_YOUNGWOMAN2")
  LuaSetAchievementLimit(3)
  LuaSetMissionDataSize(QUESTID, 2)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_RM_YOUNGWOMAN2_1_1", 1, "NPC_RM_YOUNGWOMAN2", 1, 150, "ITEM_QNO_RM_YOUNGWOMAN2_1_01", "MOB_RM_WINGTRIBE_CLON", 50)
  LuaSetCollectionItemMissionData(QUESTID, 1, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_RM_YOUNGWOMAN2_1_2", 1, "NPC_RM_YOUNGWOMAN2", 1, 150, "ITEM_QNO_RM_YOUNGWOMAN2_1_02", "MOB_RM_WINGTRIBE_CLON", 50)
  InsertQuestMenuStringList("NPC_RM_YOUNGWOMAN2", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_RM_YOUNGWOMAN2_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_RM_YOUNGWOMAN2_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_RM_YOUNGWOMAN2_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_RM_YOUNGWOMAN2_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_RM_YOUNGWOMAN2_1_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_RM_YOUNGWOMAN2_1_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_RM_YOUNGWOMAN2_1_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 9330000, 0, 450000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
