function QNO_SD_NO_048()
  QUESTID = LuaGetQuestID("QNO_SD_NO_048")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 108, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_M_AREA_SPECIAL")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_SPECIAL")
  LuaQuestInsertNpc(1, "NPC_SD_M_AREA_SPECIAL")
  LuaInsertDependancyQuests(1, "QNO_SD_NO_041")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_SD_NO_048_1", 1, "NPC_SD_M_AREA_SPECIAL", 1, 50, "ITEM_QNO_SD_NO_048_1", "MOB_SD_COELACAN", 50)
  InsertQuestMenuStringList("NPC_SD_M_AREA_SPECIAL", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_SPECIAL_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_NO_048_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_NO_048_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_NO_048_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_NO_048_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_NO_048_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_NO_048_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 11829691, 0, 5031, 0, 0)
  LuaSetAchievedSkillPont(1900)
end
