function QNO_SD_GU_018()
  QUESTID = LuaGetQuestID("QNO_SD_GU_018")
  LuaSetStartCodition(3, QSC_QUEST, QSC_LEVEL, QSC_SYSTEM, 105, 105)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_GUILD_AGENT")
  LuaInsertMissionOrCompleteNpc("NPC_SD_GUILD_AGENT")
  LuaQuestInsertNpc(1, "NPC_SD_GUILD_AGENT")
  LuaSetJobTypeStartCondition(1, OBJ_JOBSTATE_ROBBER, 1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_SD_GU_018_1", 21, "NPC_SD_GUILD_AGENT", 1, 50, "ITEM_QNO_SD_GU_018_1", "MOB_SD_PRIEST_GUARD", 100, "MOB_SD_PRIEST_POWER", 100, "MOB_SD_PRIEST_HEALING", 100, "MOB_SD_PRIEST_GALE", 100, "MOB_SD_PRIEST_FLAME", 100, "MOB_SD_PRIEST_FEAR", 100, "MOB_SD_IMOUTHES", 100, "MOB_SD_PRIEST_REVENGE", 100, "MOB_SD_PRIEST_CHASTISEMENT", 100, "MOB_SD_SPECTOR_GREED", 100, "MOB_SD_SPECTOR_DEMOLITION", 100, "MOB_SD_BLOODKHEPRI", 100, "MOB_SD_DEVIL_SANDMAN", 100, "MOB_SD_SEPTU", 100, "MOB_SD_SOPEDU", 100, "MOB_SD_PETBE", 100, "MOB_SD_SELKION", 100, "MOB_SD_KEISAS_BERSERK", 100, "MOB_SD_HARSAPHETH", 100, "MOB_SD_HARSMESS", 100, "MOB_SD_SANDSCOUT", 100)
  InsertQuestMenuStringList("NPC_SD_GUILD_AGENT", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_GUILD_AGENT_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_GU_018_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_GU_018_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_GU_018_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_GU_018_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_GU_018_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_GU_018_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 1082584, 0, 50000000, 0, 0)
  LuaSetAchievedSkillPont(700)
  LuaSetAchievedPoint(100, "TEMPLE_ANUBIS")
end
