function QNO_KT_PLUS_031()
  QUESTID = LuaGetQuestID("QNO_KT_PLUS_031")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 59, 54)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_KT_SOLDIER_WE2")
  LuaInsertMissionOrCompleteNpc("NPC_KT_SOLDIER_WE2")
  LuaQuestInsertNpc(1, "NPC_KT_SOLDIER_WE2")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_KT_PLUS_031_1", 1, "MOB_KK_YETI", 0, MONSTER_CLASS_NORMAL, 300, 0)
  InsertQuestMenuStringList("NPC_KT_SOLDIER_WE2", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_KT_SOLDIER_WE2_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_KT_PLUS_031_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_KT_PLUS_031_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_KT_PLUS_031_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_KT_PLUS_031_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_KT_PLUS_031_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_KT_PLUS_031_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 2148980, 26000, 84000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
