function QNO_SD_NO_022()
  QUESTID = LuaGetQuestID("QNO_SD_NO_022")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 102, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_M_AREA_ACCESSORY")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_ACCESSORY")
  LuaQuestInsertNpc(1, "NPC_SD_M_AREA_ACCESSORY")
  LuaInsertDependancyQuests(1, "QNO_SD_NO_021")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_SD_NO_022_1", 3, "NPC_SD_M_AREA_ACCESSORY", 1, 100, "ITEM_QNO_SD_NO_022_1", "MOB_SD_TENEN", 100, "MOB_SD_WINDSPIDER", 100, "MOB_SD_DARKSCOUT", 100)
  InsertQuestMenuStringList("NPC_SD_M_AREA_ACCESSORY", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_ACCESSORY_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_NO_022_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_NO_022_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_NO_022_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_NO_022_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_NO_022_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_NO_022_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 9907180, 0, 4768, 0, 0)
  LuaSetAchievedSkillPont(1300)
end
