function QNO_CH_POTION_1()
  QUESTID = LuaGetQuestID("QNO_CH_POTION_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 5, 1)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CH_POTION")
  LuaInsertMissionOrCompleteNpc("NPC_CH_POTION")
  LuaQuestInsertNpc(1, "NPC_CH_POTION")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_CH_POTION_1", 2, "MOB_CH_WATERGHOST_CLON", "MOB_CH_WATERGHOST", 0, 15, 0, 1)
  InsertQuestMenuStringList("NPC_CH_POTION", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_POTION_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_CH_POTION_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_CH_POTION_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_CH_POTION_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_CH_POTION_1_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_CH_POTION_1_05", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_CH_POTION_1_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_CH_POTION_1_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(1, 6160, 0, 0, 1, "ITEM_ETC_HP_POTION_01", 28)
  LuaSetAchievedSkillPont(0)
end
