function QNO_CA_THIEF_1()
  QUESTID = LuaGetQuestID("QNO_CA_THIEF_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 31, 21)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_CA_WAREHOUSE", "NPC_CA_HUNTER")
  LuaQuestInsertNpc(2, "NPC_CA_WAREHOUSE", "NPC_CA_HUNTER")
  LuaInsertMissionOrCompleteNpc("NPC_CA_HUNTER")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDeliverMissionData(QUESTID, 0, MISSION_TYPE_DELIVER_ITEM, "SN_CON_QNO_CA_THIEF_1", "NPC_CA_HUNTER", 1, 1, "ITEM_QNO_CA_THIEF_1_01", 1, "SN_TALK_QNO_CA_THIEF_1_06")
  InsertQuestMenuStringList("NPC_CA_WAREHOUSE", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_CA_WAREHOUSE_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_CA_THIEF_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_CA_THIEF_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_CA_THIEF_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_CA_THIEF_1_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_CA_THIEF_1_05", "BASIC_MENUSTRING_MIDDLE_ACHIEVED", "SN_TALK_QNO_CA_THIEF_1_07")
  InsertQuestMenuStringList("NPC_CA_HUNTER", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_CA_HUNTER_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_CA_THIEF_1_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 3770, 150, 300, 0, 0)
  LuaSetAchievedSkillPont(0)
end
