function QNO_CH_SMITH_2()
  QUESTID = LuaGetQuestID("QNO_CH_SMITH_2")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 13, 3)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CH_SMITH")
  LuaInsertMissionOrCompleteNpc("NPC_CH_SMITH")
  LuaQuestInsertNpc(1, "NPC_CH_SMITH")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_CH_SMITH_2", 1, "MOB_CH_BANDITARCHER_CLON", 0, MONSTER_CLASS_NORMAL, 140, 0)
  InsertQuestMenuStringList("NPC_CH_SMITH", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_SMITH_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_CH_SMITH_2_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_CH_SMITH_2_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_CH_SMITH_2_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_CH_SMITH_2_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_CH_SMITH_2_05", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_CH_SMITH_2_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_CH_SMITH_2_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(1, 68860, 10000, 0, 1, "ITEM_QNO_CH_SMITH_2_01", 1)
  LuaSetAchievedSkillPont(0)
end
