function QNO_WC_WAREHOUSE_M_1()
  QUESTID = LuaGetQuestID("QNO_WC_WAREHOUSE_M_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 70, 60)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_WC_WAREHOUSE_M")
  LuaInsertMissionOrCompleteNpc("NPC_WC_WAREHOUSE_M")
  LuaQuestInsertNpc(1, "NPC_WC_WAREHOUSE_M")
  LuaSetAchievementLimit(3)
  LuaSetMissionDataSize(QUESTID, 2)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_WC_WAREHOUSE_M_1_01", 2, "NPC_WC_WAREHOUSE_M", 1, 130, "ITEM_QNO_WC_WAREHOUSE_M_1_01", "MOB_DH_YACHA_CLON", 25, "MOB_DH_YACHA", 25)
  LuaSetCollectionItemMissionData(QUESTID, 1, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_WC_WAREHOUSE_M_1_02", 2, "NPC_WC_WAREHOUSE_M", 1, 130, "ITEM_QNO_WC_WAREHOUSE_M_1_02", "MOB_DH_YACHA_CLON", 25, "MOB_DH_YACHA", 25)
  InsertQuestMenuStringList("NPC_WC_WAREHOUSE_M", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_WC_WAREHOUSE_M_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_WC_WAREHOUSE_M_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_WC_WAREHOUSE_M_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_WC_WAREHOUSE_M_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_WC_WAREHOUSE_M_1_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_WC_WAREHOUSE_M_1_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_WC_WAREHOUSE_M_1_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 8275100, 0, 375000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
