function QNO_JUPITER_SUB_067()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_067")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 113, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_INVESTIGATION_08")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_INVESTIGATION_08")
  LuaInsertDependancyQuests(1, "QNO_JUPITER_SUB_066")
  LuaQuestInsertNpc(1, "NPC_JUPITER_INVESTIGATION_08")
  LuaSetAchievementLimit(0)
  LuaSetMissionDataSize(QUESTID, 2)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_067_1", 1, "MOB_JUPITER_TEMPLE_LION_CLONE", 0, 200, 0, 1)
  LuaSetMissionData_EX(QUESTID, 1, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_067_2", 1, "MOB_JUPITER_TEMPLE_WILDLION_CLONE", 0, 200, 0, 1)
  InsertQuestMenuStringList("NPC_JUPITER_INVESTIGATION_08", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_INVESTIGATION_08_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_067_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_067_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_067_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_067_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_067_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_067_06")
end
