function QNO_EU_FERRY2_2()
  QUESTID = LuaGetQuestID("QNO_EU_FERRY2_2")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 22, 12)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_EU_FERRY2")
  LuaInsertMissionOrCompleteNpc("NPC_EU_FERRY2")
  LuaQuestInsertNpc(1, "NPC_EU_FERRY2")
  LuaSetAchievementLimit(1)
  LuaInsertDependancyQuests(1, "QNO_EU_FERRY2_1")
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_EU_FERRY2_2", 1, "NPC_EU_FERRY2", 1, 30, "ITEM_QNO_EU_FERRY2_2_01", "MOB_AM_ROGUE_CLON", 25)
  InsertQuestMenuStringList("NPC_EU_FERRY2", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_EU_FERRY2_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_EU_FERRY2_2_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_EU_FERRY2_2_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_EU_FERRY2_2_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_EU_FERRY2_2_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_EU_FERRY2_2_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_EU_FERRY2_2_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 411000, 10000, 16200, 0, 0)
  LuaSetAchievedSkillPont(0)
end
