function QNO_SD_MA_007()
  QUESTID = LuaGetQuestID("QNO_SD_MA_007")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 101, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_M_AREA_MANETO")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_MANETO")
  LuaQuestInsertNpc(1, "NPC_SD_M_AREA_MANETO")
  LuaInsertDependancyQuests(1, "QNO_SD_MA_006")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_SD_MA_007_1", 1, "NPC_SD_M_AREA_MANETO", 1, 1, "ITEM_QNO_SD_MA_007_1", "MOB_SD_TATHEN", 1)
  InsertQuestMenuStringList("NPC_SD_M_AREA_MANETO", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_MANETO_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_MA_007_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_MA_007_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_MA_007_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_MA_007_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_MA_007_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_MA_007_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 19237244, 0, 4725, 0)
  LuaSetAchievedSkillPont(2200)
end
