function QNO_SD_GU_007()
  QUESTID = LuaGetQuestID("QNO_SD_GU_007")
  LuaSetStartCodition(3, QSC_QUEST, QSC_LEVEL, QSC_SYSTEM, 105, 105)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_GUILD_AGENT2")
  LuaInsertMissionOrCompleteNpc("NPC_SD_GUILD_AGENT2")
  LuaQuestInsertNpc(1, "NPC_SD_GUILD_AGENT2")
  LuaSetJobTypeStartCondition(1, OBJ_JOBSTATE_TRADER, 1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_SD_GU_007_1", 21, "NPC_SD_GUILD_AGENT2", 1, 100, "ITEM_QNO_SD_GU_007_1", "MOB_SD_PRIEST_GUARD", 50, "MOB_SD_PRIEST_POWER", 50, "MOB_SD_PRIEST_HEALING", 50, "MOB_SD_PRIEST_GALE", 50, "MOB_SD_PRIEST_FLAME", 50, "MOB_SD_PRIEST_FEAR", 50, "MOB_SD_IMOUTHES", 50, "MOB_SD_PRIEST_REVENGE", 50, "MOB_SD_PRIEST_CHASTISEMENT", 50, "MOB_SD_SPECTOR_GREED", 50, "MOB_SD_SPECTOR_DEMOLITION", 50, "MOB_SD_BLOODKHEPRI", 50, "MOB_SD_DEVIL_SANDMAN", 50, "MOB_SD_SEPTU", 50, "MOB_SD_SOPEDU", 50, "MOB_SD_PETBE", 50, "MOB_SD_SELKION", 50, "MOB_SD_KEISAS_BERSERK", 50, "MOB_SD_HARSAPHETH", 50, "MOB_SD_HARSMESS", 50, "MOB_SD_SANDSCOUT", 50)
  InsertQuestMenuStringList("NPC_SD_GUILD_AGENT2", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_GUILD_AGENT2_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_GU_007_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_GU_007_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_GU_007_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_GU_007_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_GU_007_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_GU_007_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 1082584, 0, 50000000, 0, 0)
  LuaSetAchievedSkillPont(700)
  LuaSetAchievedPoint(200, "TEMPLE_ANUBIS")
end
