function QNO_JUPITER_SUB_012()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_012")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 116, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_SOLDIER_04")
  LuaQuestInsertNpc(1, "NPC_JUPITER_SOLDIER_04")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_SOLDIER_04")
  LuaInsertDependancyQuests(1, "QNO_JUPITER_SUB_007")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_JUPITER_SUB_012_1", 3, "NPC_JUPITER_SOLDIER_04", 1, 110, "ITEM_QNO_JUPITER_SUB_012_1", "MOB_JUPITER_BAAL_FANATICISM", 25, "MOB_JUPITER_CRUEL_FANATICISM", 25, "MOB_JUPITER_WILD_FANATICISM", 25)
  InsertQuestMenuStringList("NPC_JUPITER_SOLDIER_04", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_04_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_012_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_012_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_012_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_012_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_012_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_012_06")
end
