function QNO_SD_SU_036()
  QUESTID = LuaGetQuestID("QNO_SD_SU_036")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 106, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_M_AREA_EYPTSOLIDER_1")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_EYPTSOLIDER_1")
  LuaInsertDependancyQuests(1, "QNO_SD_SU_002")
  LuaQuestInsertNpc(1, "NPC_SD_M_AREA_EYPTSOLIDER_1")
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_SD_SU_036_1", 1, "MOB_SD_MONTKILLER", 0, MONSTER_CLASS_NORMAL, 1000, 0)
  InsertQuestMenuStringList("NPC_SD_M_AREA_EYPTSOLIDER_1", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_EYPTSOLIDER_1_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_SU_036_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_SU_036_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_SU_036_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_SU_036_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_SU_036_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_SU_036_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 8920495, 0, 49437, 0, 0)
  LuaSetAchievedSkillPont(950)
end
