function QNO_CH_CHEF_1()
  QUESTID = LuaGetQuestID("QNO_CH_CHEF_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 1, 1)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CH_CHEF")
  LuaInsertMissionOrCompleteNpc("NPC_CH_CHEF")
  LuaQuestInsertNpc(1, "NPC_CH_CHEF")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_CH_CHEF_1", 2, "NPC_CH_CHEF", 1, 1, "ITEM_QNO_CH_CHEF_1", "MOB_CH_BIGEYEGHOST", 20, "MOB_CH_BIGEYEGHOST_CLON", 20)
  InsertQuestMenuStringList("NPC_CH_CHEF", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_CHEF_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_CH_CHEF_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_CH_CHEF_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_CH_CHEF_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_CH_CHEF_1_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_CH_CHEF_1_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_CH_CHEF_1_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 375, 0, 475, 0, 0)
  LuaSetAchievedSkillPont(0)
end
