function QNO_JUPITER_SUB_064()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_064")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 113, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_INVESTIGATION_07")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_INVESTIGATION_07")
  LuaQuestInsertNpc(1, "NPC_JUPITER_INVESTIGATION_07")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 2)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_064_1", 1, "MOB_JUPITER_TEMPLE_LION_CLONE", 0, 250, 0, 1)
  LuaSetMissionData_EX(QUESTID, 1, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_064_2", 1, "MOB_JUPITER_TEMPLE_WILDLION_CLONE", 0, 250, 0, 1)
  InsertQuestMenuStringList("NPC_JUPITER_INVESTIGATION_07", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_INVESTIGATION_07_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_064_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_064_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_064_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_064_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_064_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_064_06")
end
