function QNO_JUPITER_SUB_046()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_046")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 120, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_BELIEVER_07")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_BELIEVER_07")
  LuaQuestInsertNpc(1, "NPC_JUPITER_BELIEVER_07")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 2)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_046_1", 1, "MOB_JUPITER_BAAL_DEVILDOG", 0, 50, 0, 1)
  LuaSetMissionData_EX(QUESTID, 1, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_046_2", 1, "MOB_JUPITER_BAAL_WATCHDOG", 0, 50, 0, 1)
  InsertQuestMenuStringList("NPC_JUPITER_BELIEVER_07", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_BELIEVER_07_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_046_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_046_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_046_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_046_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_046_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_046_06")
end
