function QNO_SD_NO_007()
  QUESTID = LuaGetQuestID("QNO_SD_NO_007")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 101, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_SD_M_AREA_MANETO", "NPC_SD_M_AREA_SPECIAL")
  LuaQuestInsertNpc(2, "NPC_SD_M_AREA_MANETO", "NPC_SD_M_AREA_SPECIAL")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_SPECIAL")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDeliverMissionData(QUESTID, 0, MISSION_TYPE_DELIVER_ITEM, "SN_CON_QNO_SD_NO_007_1", "NPC_SD_M_AREA_SPECIAL", 1, 1, "ITEM_QNO_SD_NO_007_1", 1, "SN_TALK_QNO_SD_NO_007_06")
  InsertQuestMenuStringList("NPC_SD_M_AREA_MANETO", 6, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_MANETO_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_NO_007_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_NO_007_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_NO_007_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_NO_007_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_SD_NO_007_05")
  InsertQuestMenuStringList("NPC_SD_M_AREA_SPECIAL", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_SPECIAL_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_NO_007_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 4809311, 0, 2362, 0, 0)
  LuaSetAchievedSkillPont(700)
end
