function QNO_JUPITER_SUB_023()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_023")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 112, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_INVESTIGATION_03")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_INVESTIGATION_03")
  LuaQuestInsertNpc(1, "NPC_JUPITER_INVESTIGATION_03")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 2)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_023_1", 1, "MOB_JUPITER_APOLLO_LION", 0, 20, 0, 1)
  LuaSetMissionData_EX(QUESTID, 1, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_023_2", 1, "MOB_JUPITER_NIKE_LION", 0, 40, 0, 1)
  InsertQuestMenuStringList("NPC_JUPITER_INVESTIGATION_03", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_INVESTIGATION_03_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_023_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_023_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_023_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_023_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_023_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_023_06")
end
