function QNO_TQ_BAEKRYOUNG_8()
  QUESTID = LuaGetQuestID("QNO_TQ_BAEKRYOUNG_8")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 98, 88)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CH_GENARAL_SP")
  LuaInsertMissionOrCompleteNpc("NPC_CH_GENARAL_SP")
  LuaQuestInsertNpc(1, "NPC_CH_GENARAL_SP")
  LuaSetAchievementLimit(1)
  LuaInsertDependancyQuests(1, "QNO_TQ_BAEKRYOUNG_7")
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_TQ_BAEKRYOUNG_8_01", 1, "NPC_CH_GENARAL_SP", 1, 20, "ITEM_QNO_TQ_BAEKRYEONG_8_01", "MOB_TQ_SNAKEDEMON", 20)
  InsertQuestMenuStringList("NPC_CH_GENARAL_SP", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_GENARAL_SP_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_TQ_BAEKRYEONG_8_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_TQ_BAEKRYEONG_8_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_TQ_BAEKRYEONG_8_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_TQ_BAEKRYEONG_8_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_TQ_BAEKRYEONG_8_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_TQ_BAEKRYEONG_8_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 5040200, 0, 0, 0, 0)
  LuaSetAchievedSkillPont(0)
end
