function QNO_CH_SPECIAL_2()
  QUESTID = LuaGetQuestID("QNO_CH_SPECIAL_2")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 18, 3)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CH_SPECIAL")
  LuaInsertMissionOrCompleteNpc("NPC_CH_SPECIAL")
  LuaQuestInsertNpc(1, "NPC_CH_SPECIAL")
  LuaSetAchievementLimit(2)
  LuaSetDifferentString(1)
  LuaInsertDependancyQuests(1, "QNO_CH_SPECIAL_1")
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_CH_SPECIAL_2", 1, "NPC_CH_SPECIAL", 1, 70, "ITEM_QNO_CH_SPECIAL_2_01", "MOB_CH_WHITETIGER", 50)
  InsertQuestMenuStringList("NPC_CH_SPECIAL", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_SPECIAL_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_CH_SPECIAL_2_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_CH_SPECIAL_2_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_CH_SPECIAL_2_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_CH_SPECIAL_2_04", "BASIC_MENUSTRING_ACCEPT_AFTER_ONE_CLEAR", "SN_TALK_QNO_CH_SPECIAL_2_07", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_CH_SPECIAL_2_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_CH_SPECIAL_2_09")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 93060, 10000, 10900, 0, 0)
  LuaSetAchievedSkillPont(0)
end
