function QNO_SD_RE_025()
  QUESTID = LuaGetQuestID("QNO_SD_RE_025")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 107, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_M_AREA_SPECIAL")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_SPECIAL")
  LuaQuestInsertNpc(1, "NPC_SD_M_AREA_SPECIAL")
  LuaInsertDependancyQuests(1, "QNO_SD_RE_024")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 2)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_SD_RE_025_1", 1, "NPC_SD_M_AREA_SPECIAL", 1, 50, "ITEM_QNO_SD_RE_025_1", "MOB_SD_COELACANTH", 100)
  LuaSetCollectionItemMissionData(QUESTID, 1, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_SD_RE_025_2", 1, "NPC_SD_M_AREA_SPECIAL", 1, 50, "ITEM_QNO_SD_RE_025_2", "MOB_SD_ACHNISH", 100)
  InsertQuestMenuStringList("NPC_SD_M_AREA_SPECIAL", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_SPECIAL_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_RE_025_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_RE_025_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_RE_025_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_RE_025_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_RE_025_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_RE_025_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 11485137, 0, 4987, 0, 0)
  LuaSetAchievedSkillPont(1800)
end
