function QNO_KT_PLUS_013()
  QUESTID = LuaGetQuestID("QNO_KT_PLUS_013")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 44, 39)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_KT_POTION")
  LuaInsertMissionOrCompleteNpc("NPC_KT_POTION")
  LuaQuestInsertNpc(1, "NPC_KT_POTION")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_KT_PLUS_013_1", 1, "NPC_KT_POTION", 1, 30, "ITEM_QNO_KT_PLUS_013_1", "MOB_KT_ONG_CLON2", 10)
  InsertQuestMenuStringList("NPC_KT_POTION", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_KT_POTION_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_KT_PLUS_013_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_KT_PLUS_013_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_KT_PLUS_013_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_KT_PLUS_013_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_KT_PLUS_013_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_KT_PLUS_013_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 953500, 18000, 76000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
