function QNO_JUPITER_SUB_069()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_069")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 114, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_SOLDIER_21")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_SOLDIER_21")
  LuaInsertDependancyQuests(1, "QNO_JUPITER_SUB_068")
  LuaQuestInsertNpc(1, "NPC_JUPITER_SOLDIER_21")
  LuaSetAchievementLimit(0)
  LuaSetMissionDataSize(QUESTID, 2)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_069_1", 1, "MOB_JUPITER_FIRE_PROTECTION_CLONE", 0, 200, 0, 1)
  LuaSetMissionData_EX(QUESTID, 1, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_069_2", 1, "MOB_JUPITER_WATER_PROTECTION_CLONE", 0, 200, 0, 1)
  InsertQuestMenuStringList("NPC_JUPITER_SOLDIER_21", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_21_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_069_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_069_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_069_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_069_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_069_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_069_06")
end
