function QNO_JUPITER_MAIN_036()
  QUESTID = LuaGetQuestID("QNO_JUPITER_MAIN_036")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 116, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_JUPITER_SOLDIER_19", "NPC_JUPITER_SOLDIER_16")
  LuaQuestInsertNpc(2, "NPC_JUPITER_SOLDIER_19", "NPC_JUPITER_SOLDIER_16")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_SOLDIER_16")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDialLogMissionData(QUESTID, 0, MISSION_TYPE_DIALOG, "SN_CON_QNO_JUPITER_MAIN_036_1", 1, "SN_TALK_QNO_JUPITER_MAIN_036_05")
  InsertQuestMenuStringList("NPC_JUPITER_SOLDIER_19", 5, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_19_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_MAIN_036_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_MAIN_036_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_MAIN_036_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_MAIN_036_04")
  InsertQuestMenuStringList("NPC_JUPITER_INVESTIGATION_01", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_16_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_MAIN_036_05")
end
