function QNO_KT_POTION_1()
  QUESTID = LuaGetQuestID("QNO_KT_POTION_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 52, 42)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_KT_POTION")
  LuaInsertMissionOrCompleteNpc("NPC_KT_POTION")
  LuaQuestInsertNpc(1, "NPC_KT_POTION")
  LuaSetAchievementLimit(3)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_KT_POTION_1", 2, "NPC_KT_POTION", 1, 100, "ITEM_QNO_KT_POTION_1", "MOB_KK_SPIDER", 20, "MOB_KK_SPIDER_CLON", 20)
  InsertQuestMenuStringList("NPC_KT_POTION", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_KT_POTION_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_KT_POTION_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_KT_POTION_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_KT_POTION_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_KT_POTION_1_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_KT_POTION_1_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_KT_POTION_1_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 1650000, 0, 100000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
