function QNO_EU_CONS_1()
  QUESTID = LuaGetQuestID("QNO_EU_CONS_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 3, 1)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_EU_POTION")
  LuaInsertMissionOrCompleteNpc("NPC_EU_POTION")
  LuaQuestInsertNpc(1, "NPC_EU_POTION")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_EU_CONS_1", 1, "MOB_EU_EDENP_CLON", 0, MONSTER_CLASS_NORMAL, 15, 0)
  InsertQuestMenuStringList("NPC_EU_POTION", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_EU_POTION_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_EU_CONS_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_EU_CONS_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_EU_CONS_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_EU_CONS_1_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_EU_CONS_1_05", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_EU_CONS_1_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_EU_CONS_1_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(1, 1410, 100, 0, 1, "ITEM_QNO_EU_CONS_1_01", 1)
  LuaSetAchievedSkillPont(0)
end
