function QNO_JUPITER_SUB_027()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_027")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 113, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_SOLDIER_08")
  LuaQuestInsertNpc(1, "NPC_JUPITER_SOLDIER_08")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_SOLDIER_08")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_JUPITER_SUB_027_1", 1, "NPC_JUPITER_SOLDIER_08", 1, 10, "ITEM_QNO_JUPITER_SUB_027_1", "MOB_JUPITER_MINO", 10)
  InsertQuestMenuStringList("NPC_JUPITER_SOLDIER_08", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_08_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_027_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_027_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_027_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_027_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_027_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_027_06")
end
