function QNO_SD_NO_023()
  QUESTID = LuaGetQuestID("QNO_SD_NO_023")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 102, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_SD_M_AREA_ACCESSORY", "NPC_SD_M_AREA_LIGHTHOUSE")
  LuaQuestInsertNpc(2, "NPC_SD_M_AREA_ACCESSORY", "NPC_SD_M_AREA_LIGHTHOUSE")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_LIGHTHOUSE")
  LuaInsertDependancyQuests(1, "QNO_SD_NO_022")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDeliverMissionData(QUESTID, 0, MISSION_TYPE_DELIVER_ITEM, "SN_CON_QNO_SD_NO_023_1", "NPC_SD_M_AREA_LIGHTHOUSE", 1, 1, "ITEM_QNO_SD_NO_023_1", 1, "SN_TALK_QNO_SD_NO_023_06")
  InsertQuestMenuStringList("NPC_SD_M_AREA_ACCESSORY", 6, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_ACCESSORY_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_NO_023_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_NO_023_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_NO_023_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_NO_023_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_SD_NO_023_05")
  InsertQuestMenuStringList("NPC_SD_M_AREA_LIGHTHOUSE", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_LIGHTHOUSE_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_NO_023_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 4953590, 0, 2384, 0, 0)
  LuaSetAchievedSkillPont(800)
end
