function QNO_JUPITER_SUB_022()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_022")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 115, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_INVESTIGATION_02")
  LuaQuestInsertNpc(1, "NPC_JUPITER_INVESTIGATION_02")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_INVESTIGATION_02")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_JUPITER_SUB_022_1", 6, "NPC_JUPITER_INVESTIGATION_02", 1, 100, "ITEM_QNO_JUPITER_SUB_022_1", "MOB_JUPITER_SOUL_CUTER", 20, "MOB_JUPITER_SOUL_BREAKER", 20, "MOB_JUPITER_SOUL_WATCHER", 20, "MOB_JUPITER_APOLLO_LION", 20, "MOB_JUPITER_NIKE_LION", 20, "MOB_JUPITER_MINO", 20)
  InsertQuestMenuStringList("NPC_JUPITER_INVESTIGATION_02", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_INVESTIGATION_02_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_022_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_022_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_022_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_022_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_022_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_022_06")
end
