function QNO_SD_HW_008()
  QUESTID = LuaGetQuestID("QNO_SD_HW_008")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 105, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_M_AREA_LENENUNE")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_LENENUNE")
  LuaQuestInsertNpc(1, "NPC_SD_M_AREA_LENENUNE")
  LuaInsertDependancyQuests(1, "QNO_SD_HW_007")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_SD_HW_008_1", 5, "NPC_SD_M_AREA_LENENUNE", 1, 50, "ITEM_QNO_SD_HW_008_1", "MOB_SD_SPHINX_2", 100, "MOB_SD_NEPHTHYS_2", 100, "MOB_SD_SEKHMET_2", 100, "MOB_SD_HORUS_2", 100, "MOB_SD_OSIRIS_2", 100)
  InsertQuestMenuStringList("NPC_SD_M_AREA_LENENUNE", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_LENENUNE_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_HW_008_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_HW_008_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_HW_008_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_HW_008_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_HW_008_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_HW_008_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 54129218, 0, 49437, 0, 0)
  LuaSetAchievedSkillPont(3100)
end
