function QNO_SD_MA_006()
  QUESTID = LuaGetQuestID("QNO_SD_MA_006")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 101, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_SD_M_AREA_LENENUNE", "NPC_SD_M_AREA_MANETO")
  LuaQuestInsertNpc(2, "NPC_SD_M_AREA_LENENUNE", "NPC_SD_M_AREA_MANETO")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_MANETO")
  LuaInsertDependancyQuests(1, "QNO_SD_MA_005")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDialLogMissionData(QUESTID, 0, MISSION_TYPE_DIALOG, "SN_CON_QNO_SD_MA_006_1", 1, "SN_TALK_QNO_SD_MA_006_05")
  InsertQuestMenuStringList("NPC_SD_M_AREA_LENENUNE", 5, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_LENENUNE_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_MA_006_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_MA_006_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_MA_006_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_MA_006_04")
  InsertQuestMenuStringList("NPC_SD_M_AREA_MANETO", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_MANETO_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_MA_006_05")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 9618622, 0, 2362, 0, 0)
  LuaSetAchievedSkillPont(1200)
end
