function QNO_CA_TREASURE_1()
  QUESTID = LuaGetQuestID("QNO_CA_TREASURE_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 33, 23)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_CA_SMITH", "NPC_CA_WAREHOUSE")
  LuaQuestInsertNpc(2, "NPC_CA_SMITH", "NPC_CA_WAREHOUSE")
  LuaInsertMissionOrCompleteNpc("NPC_CA_WAREHOUSE")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDialLogMissionData(QUESTID, 0, MISSION_TYPE_DIALOG, "SN_CON_QNO_CA_TREASURE_1", 1, "SN_TALK_QNO_CA_TREASURE_1_05")
  InsertQuestMenuStringList("NPC_CA_SMITH", 6, "BASIC_MENUSTRING_GREETING", "SN_QNO_RM_OLDWOMAN_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_CA_TREASURE_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_CA_TREASURE_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_CA_TREASURE_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_CA_TREASURE_1_04", "BASIC_MENUSTRING_MIDDLE_ACHIEVED", "SN_TALK_QNO_CA_TREASURE_1_06")
  InsertQuestMenuStringList("NPC_CA_WAREHOUSE", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_CA_WAREHOUSE_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_CA_TREASURE_1_05")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 4350, 150, 300, 0, 0)
  LuaSetAchievedSkillPont(0)
end
