function QNO_JUPITER_SUB_032()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_032")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 115, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_SOLDIER_14")
  LuaQuestInsertNpc(1, "NPC_JUPITER_SOLDIER_14")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_SOLDIER_14")
  LuaInsertDependancyQuests(1, "QNO_JUPITER_SUB_031")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_JUPITER_SUB_032_1", 1, "NPC_JUPITER_SOLDIER_14", 1, 1, "ITEM_QNO_JUPITER_SUB_032_1", "MOB_JUPITER_IMMOTAL_GRIFFIN", 1)
  InsertQuestMenuStringList("NPC_JUPITER_SOLDIER_14", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_14_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_032_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_032_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_032_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_032_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_032_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_032_06")
end
