function QNO_SD_NO_003()
  QUESTID = LuaGetQuestID("QNO_SD_NO_003")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 100, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_M_AREA_FERRY")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_FERRY")
  LuaQuestInsertNpc(1, "NPC_SD_M_AREA_FERRY")
  LuaSetAchievementLimit(1)
  MISSION_TYPE_KILL_MONSTER = 2
  MONSTER_CLASS_CHAMPION = 1
  MONSTER_CLASS_NORMAL = 0
  LuaSetMissionDataSize(QUESTID, 2)
  LuaSetMissionData(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_SD_NO_003_1", 1, "MOB_SD_UNEG", 0, MONSTER_CLASS_NORMAL, 100, 0)
  LuaSetMissionData(QUESTID, 1, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_SD_NO_003_2", 1, "MOB_SD_WENEG", 0, MONSTER_CLASS_NORMAL, 100, 1)
  InsertQuestMenuStringList("NPC_SD_M_AREA_FERRY", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_FERRY_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_NO_003_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_NO_003_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_NO_003_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_NO_003_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_NO_003_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_NO_003_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 28015403, 0, 9362, 0, 0)
  LuaSetAchievedSkillPont(1600)
end
