function QNO_EU_GENERAL_4()
  QUESTID = LuaGetQuestID("QNO_EU_GENERAL_4")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 24, 14)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_EU_GENERAL")
  LuaInsertMissionOrCompleteNpc("NPC_EU_GENERAL")
  LuaQuestInsertNpc(1, "NPC_EU_GENERAL")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 3)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_EU_GENERAL_4_01", 1, "NPC_EU_GENERAL", 1, 10, "ITEM_QNO_EU_GENERAL_4_01", "MOB_AM_WOLF_CLON", 25)
  LuaSetCollectionItemMissionData(QUESTID, 1, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_EU_GENERAL_4_02", 1, "NPC_EU_GENERAL", 1, 20, "ITEM_QNO_EU_GENERAL_4_02", "MOB_AM_WOLF_CLON", 25)
  LuaSetCollectionItemMissionData(QUESTID, 2, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_EU_GENERAL_4_03", 1, "NPC_EU_GENERAL", 1, 20, "ITEM_QNO_EU_GENERAL_4_03", "MOB_AM_WOLF_CLON", 25)
  InsertQuestMenuStringList("NPC_EU_GENERAL", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_EU_GENERAL_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_EU_GENERAL_4_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_EU_GENERAL_4_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_EU_GENERAL_4_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_EU_GENERAL_4_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_EU_GENERAL_4_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_EU_GENERAL_4_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 724240, 15000, 26000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
