function QNO_JUPITER_MAIN_019()
  QUESTID = LuaGetQuestID("QNO_JUPITER_MAIN_019")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 113, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_JUPITER_INVESTIGATION_01", "NPC_EU_GENERAL")
  LuaQuestInsertNpc(2, "NPC_JUPITER_INVESTIGATION_01", "NPC_EU_GENERAL")
  LuaInsertMissionOrCompleteNpc("NPC_EU_GENERAL")
  LuaInsertDependancyQuests(1, "QNO_JUPITER_MAIN_017")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDeliverMissionData(QUESTID, 0, MISSION_TYPE_DELIVER_ITEM, "SN_CON_QNO_JUPITER_MAIN_019_1", "NPC_EU_GENERAL", 1, 1, "ITEM_QNO_JUPITER_MAIN_019_1", 1, "SN_TALK_QNO_JUPITER_MAIN_019_06")
  InsertQuestMenuStringList("NPC_JUPITER_INVESTIGATION_01", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_INVESTIGATION_01_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_MAIN_019_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_MAIN_019_02", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_JUPITER_MAIN_019_03", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_MAIN_019_04", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_MAIN_019_05", "BASIC_MENUSTRING_MIDDLE_ACHIEVED", "SN_TALK_QNO_JUPITER_MAIN_019_07")
  InsertQuestMenuStringList("NPC_EU_GENERAL", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_EU_GENERAL_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_MAIN_019_06")
end
