function QNO_SD_MA_021()
  QUESTID = LuaGetQuestID("QNO_SD_MA_021")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 109, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_M_AREA_SENMUTE")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_SENMUTE")
  LuaQuestInsertNpc(1, "NPC_SD_M_AREA_SENMUTE")
  LuaInsertDependancyQuests(1, "QNO_SD_MA_020")
  LuaSetAchievementLimit(1)
  LuaSetDivideType(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_SD_MA_021_1", 1, "NPC_SD_M_AREA_SENMUTE", 1, 1, "ITEM_QNO_SD_MA_021_1", "MOB_SD_OSIRIS", 100)
  InsertQuestMenuStringList("NPC_SD_M_AREA_SENMUTE", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_SENMUTE_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_MA_021_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_MA_021_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_MA_021_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_MA_021_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_MA_021_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_MA_021_06", "BASIC_MENUSTRING_NOT_PARTY", "SN_TALK_QNO_SD_MA_021_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 73107492, 0, 15225, 0)
  LuaSetAchievedSkillPont(4000)
end
