function QNO_WC_HORSE_3()
  QUESTID = LuaGetQuestID("QNO_WC_HORSE_3")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 27, 17)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_WC_HORSE")
  LuaInsertMissionOrCompleteNpc("NPC_WC_HORSE")
  LuaQuestInsertNpc(1, "NPC_WC_HORSE")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_WC_HORSE_3", 1, "MOB_WC_EARTHGHOST", 0, MONSTER_CLASS_NORMAL, 350, 0)
  InsertQuestMenuStringList("NPC_WC_HORSE", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_WC_HORSE_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_WC_HORSE_3_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_WC_HORSE_3_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_WC_HORSE_3_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_WC_HORSE_3_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_WC_HORSE_3_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_WC_HORSE_3_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 390100, 25000, 0, 0, 0)
  LuaSetAchievedSkillPont(0)
end
