function QNO_EU_EASTEU_10()
  QUESTID = LuaGetQuestID("QNO_EU_EASTEU_10")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 15, 5)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_EU_HUNTER")
  LuaInsertMissionOrCompleteNpc("NPC_EU_HUNTER")
  LuaQuestInsertNpc(1, "NPC_EU_HUNTER")
  LuaSetAchievementLimit(1)
  LuaInsertDependancyQuests(1, "QNO_EU_EASTEU_9")
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_EU_EASTEU_10", 1, "NPC_EU_HUNTER", 1, 30, "ITEM_QNO_EU_EASTEU_10_01", "MOB_EU_KYKLOPES", 20)
  InsertQuestMenuStringList("NPC_EU_HUNTER", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_EU_HUNTER_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_EU_EASTEU_10_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_EU_EASTEU_10_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_EU_EASTEU_10_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_EU_EASTEU_10_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_EU_EASTEU_10_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_EU_EASTEU_10_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 77360, 10000, 0, 0, 0)
  LuaSetAchievedSkillPont(0)
end
