function QNO_TQ_SAMPLEARMOR_3()
  QUESTID = LuaGetQuestID("QNO_TQ_SAMPLEARMOR_3")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 83, 73)
  LuaSetDifferentString(1)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CH_ARMOR")
  LuaInsertMissionOrCompleteNpc("NPC_CH_ARMOR")
  LuaQuestInsertNpc(1, "NPC_CH_ARMOR")
  LuaSetAchievementLimit(3)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_TQ_SAMPLEARMOR_3_01", 1, "NPC_CH_ARMOR", 1, 100, "ITEM_QNO_TQ_SAMPLEARMOR_3_01", "MOB_TQ_TOMBSOLDIER", 20)
  InsertQuestMenuStringList("NPC_CH_ARMOR", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_ARMOR_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_TQ_SAMPLEARMOR_3_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_TQ_SAMPLEARMOR_3_03", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_TQ_SAMPLEARMOR_3_04", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_TQ_SAMPLEARMOR_3_05", "BASIC_MENUSTRING_ACCEPT_AFTER_ONE_CLEAR", "SN_TALK_QNO_TQ_SAMPLEARMOR_3_02", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_TQ_SAMPLEARMOR_3_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_TQ_SAMPLEARMOR_3_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 3995000, 0, 150000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
