function QNO_JUPITER_SUB_076()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_076")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 116, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_SOLDIER_22")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_SOLDIER_22")
  LuaQuestInsertNpc(1, "NPC_JUPITER_SOLDIER_22")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_076_1", 1, "MOB_JUPITER_CRUEL_FANATICISM_CLONE", 0, 500, 0, 1)
  InsertQuestMenuStringList("NPC_JUPITER_SOLDIER_22", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_22_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_076_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_076_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_076_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_076_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_076_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_076_06")
end
