function QNO_EU_GENERAL_3()
  QUESTID = LuaGetQuestID("QNO_EU_GENERAL_3")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 23, 13)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_EU_GENERAL", "NPC_EU_PRIEST")
  LuaQuestInsertNpc(2, "NPC_EU_GENERAL", "NPC_EU_PRIEST")
  LuaInsertMissionOrCompleteNpc("NPC_EU_PRIEST")
  LuaInsertDependancyQuests(1, "QNO_EU_GENERAL_2")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDeliverMissionData(QUESTID, 0, MISSION_TYPE_DELIVER_ITEM, "SN_CON_QNO_EU_GENERAL_3", "NPC_EU_PRIEST", 1, 1, "ITEM_QNO_EU_GENERAL_3_01", 1, "SN_TALK_QNO_EU_GENERAL_3_05")
  InsertQuestMenuStringList("NPC_EU_GENERAL", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_EU_GENERAL_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_EU_GENERAL_3_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_EU_GENERAL_3_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_EU_GENERAL_3_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_EU_GENERAL_3_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_EU_GENERAL_3_07", "BASIC_MENUSTRING_MIDDLE_ACHIEVED", "SN_TALK_QNO_EU_GENERAL_3_06")
  InsertQuestMenuStringList("NPC_EU_PRIEST", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_EU_PRIEST_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_EU_GENERAL_3_05")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 11100, 500, 800, 0, 0)
  LuaSetAchievedSkillPont(0)
end
