function QNO_TQ_STONEBOARD_3()
  QUESTID = LuaGetQuestID("QNO_TQ_STONEBOARD_3")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 90, 80)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_CH_GENARAL_SW", "NPC_CH_SHAMAN")
  LuaQuestInsertNpc(2, "NPC_CH_GENARAL_SW", "NPC_CH_SHAMAN")
  LuaInsertMissionOrCompleteNpc("NPC_CH_SHAMAN")
  LuaInsertDependancyQuests(1, "QNO_TQ_STONEBOARD_2")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDeliverMissionData(QUESTID, 0, MISSION_TYPE_DELIVER_ITEM, "SN_CON_QNO_TQ_STONEBOARD_3_01", "NPC_CH_SHAMAN", 1, 1, "ITEM_QNO_TQ_STONEBOARD_3_01", 1, "SN_TALK_QNO_TQ_STONEBOARD_3_06")
  InsertQuestMenuStringList("NPC_CH_GENARAL_SW", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_GENARAL_SW_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_TQ_STONEBOARD_3_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_TQ_STONEBOARD_3_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_TQ_STONEBOARD_3_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_TQ_STONEBOARD_3_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_TQ_STONEBOARD_3_05", "BASIC_MENUSTRING_MIDDLE_ACHIEVED", "SN_TALK_QNO_TQ_STONEBOARD_3_07")
  InsertQuestMenuStringList("NPC_CH_SHAMAN", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_SHAMAN_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_TQ_STONEBOARD_3_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 2601000, 0, 0, 0, 0)
  LuaSetAchievedSkillPont(0)
end
