function QNO_CA_GORIA_5()
  QUESTID = LuaGetQuestID("QNO_CA_GORIA_5")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 40, 29)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CA_HUNTER")
  LuaInsertMissionOrCompleteNpc("NPC_CA_HUNTER")
  LuaQuestInsertNpc(1, "NPC_CA_HUNTER")
  LuaSetAchievementLimit(1)
  LuaInsertDependancyQuests(1, "QNO_CA_GORIA_4")
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_CA_GORIA_5", 1, "NPC_CA_HUNTER", 1, 1, "ITEM_QNO_CA_GORIA_5_01", "MOB_QT_01_MONKEY", 100)
  InsertQuestMenuStringList("NPC_CA_HUNTER", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_CA_HUNTER_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_CA_GORIA_5_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_CA_GORIA_5_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_CA_GORIA_5_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_CA_GORIA_5_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_CA_GORIA_5_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_CA_GORIA_5_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 31900, 800, 2000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
