function QNO_JOB_THIEF_KILL_HUNTER()
  QUESTID = LuaGetQuestID("QNO_JOB_THIEF_KILL_HUNTER")
  LuaSetStartCodition(3, QSC_QUEST, QSC_LEVEL, QSC_SYSTEM, 100, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_GUILD_AGENT")
  LuaInsertMissionOrCompleteNpc("NPC_SD_GUILD_AGENT")
  LuaQuestInsertNpc(1, "NPC_SD_GUILD_AGENT")
  LuaSetAchievementLimit(1)
  LuaSetJobTypeStartCondition(1, OBJ_JOBSTATE_ROBBER, 1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetKillPlayerMissionData(QUESTID, 0, MISSION_TYPE_KILL_PLAYER, "SN_CON_QNO_JOB_THIEF_KILL_HUNTER_1", 1, "NPC_SD_GUILD_AGENT", 100, 3, MKP_LEVEL, MKP_JOB, MKP_REGION, -32752, 100, 2, OBJ_JOBSTATE_TRADER, OBJ_JOBSTATE_HUNTER)
  InsertQuestMenuStringList("NPC_SD_GUILD_AGENT", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_GUILD_AGENT_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JOB_THIEF_KILL_HUNTER_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JOB_THIEF_KILL_HUNTER_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JOB_THIEF_KILL_HUNTER_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JOB_THIEF_KILL_HUNTER_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JOB_THIEF_KILL_HUNTER_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JOB_THIEF_KILL_HUNTER_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 5082584, 0, 49000000, ITEM_ETC_ARENA_COIN, 100)
  LuaSetAchievedSkillPont(40000)
  LuaSetAchievedPoint(300, "TEMPLE_ANUBIS")
end
