function QNO_SD_MA_011()
  QUESTID = LuaGetQuestID("QNO_SD_MA_011")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 101, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_SD_M_AREA_SENMUTE", "NPC_SD_M_AREA_LENENUNE")
  LuaQuestInsertNpc(2, "NPC_SD_M_AREA_SENMUTE", "NPC_SD_M_AREA_LENENUNE")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_LENENUNE")
  LuaInsertDependancyQuests(1, "QNO_SD_MA_010")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDialLogMissionData(QUESTID, 0, MISSION_TYPE_DIALOG, "SN_CON_QNO_SD_MA_011_1", 1, "SN_TALK_QNO_SD_MA_011_05")
  InsertQuestMenuStringList("NPC_SD_M_AREA_SENMUTE", 5, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_SENMUTE_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_MA_011_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_MA_011_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_MA_011_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_MA_011_04")
  InsertQuestMenuStringList("NPC_SD_M_AREA_LENENUNE", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_LENENUNE_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_MA_011_05")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 9618622, 0, 2362, 0, 0)
  LuaSetAchievedSkillPont(1200)
end
