function QNO_JUPITER_SOLDIER_01_02()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SOLDIER_01_02")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 1, 1)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_SOLDIER_01")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_SOLDIER_01")
  LuaQuestInsertNpc(1, "NPC_JUPITER_SOLDIER_01")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SOLDIER_01_02", 9, "MOB_JUPITER_SOUL_CUTER", "MOB_JUPITER_TEMPLE_PROTECTION", "MOB_JUPITER_IMMOTAL_WATCH", "MOB_JUPITER_SOUL_BREAKER", "MOB_JUPITER_SOUL_WATCHER", "MOB_JUPITER_TEMPLE_GUARD", "MOB_JUPITER_TEMPLE_GUARD_CLONE", "MOB_JUPITER_TEMPLE_WATCH", "MOB_JUPITER_TEMPLE_WATCH_CLONE", 0, 3500, 0, 1)
  InsertQuestMenuStringList("NPC_JUPITER_SOLDIER_01", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_01_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SOLDIER_01_02_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SOLDIER_01_02_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SOLDIER_01_02_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SOLDIER_01_02_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SOLDIER_01_02_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SOLDIER_01_02_06")
  LuaSetMissionCompleteNum(0)
  LuaSetAchievedItem(0, 10082584, 0, 100000000, ITEM_ETC_ARENA_COIN, 200)
end
