function QNO_CH_SOLDIER_EA1_1()
  QUESTID = LuaGetQuestID("QNO_CH_SOLDIER_EA1_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 3, 1)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CH_SOLDIER_EA1")
  LuaInsertMissionOrCompleteNpc("NPC_CH_SOLDIER_EA1")
  LuaQuestInsertNpc(1, "NPC_CH_SOLDIER_EA1")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_CH_SOLDIER_EA1_1", 2, "MOB_CH_GYO_CLON", "MOB_CH_GYO", 0, 14, 0, 1)
  InsertQuestMenuStringList("NPC_CH_SOLDIER_EA1", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_SOLDIER_EA1_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_CH_SOLDIER_EA1_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_CH_SOLDIER_EA1_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_CH_SOLDIER_EA1_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_CH_SOLDIER_EA1_1_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_CH_SOLDIER_EA1_1_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_CH_SOLDIER_EA1_1_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 2752, 0, 1000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
