function QNO_EU_CONS_3()
  QUESTID = LuaGetQuestID("QNO_EU_CONS_3")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 4, 1)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_EU_MERCHANT")
  LuaInsertMissionOrCompleteNpc("NPC_EU_MERCHANT")
  LuaQuestInsertNpc(1, "NPC_EU_MERCHANT")
  LuaSetAchievementLimit(1)
  LuaInsertDependancyQuests(1, "QNO_EU_CONS_2")
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_EU_CONS_3", 1, "NPC_EU_MERCHANT", 1, 2, "ITEM_QNO_EU_CONS_3_01", "MOB_EU_EDENP", 12)
  InsertQuestMenuStringList("NPC_EU_MERCHANT", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_EU_MERCHANT_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_EU_CONS_3_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_EU_CONS_3_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_EU_CONS_3_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_EU_CONS_3_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_EU_CONS_3_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_EU_CONS_3_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 350, 200, 200, 0, 0)
  LuaSetAchievedSkillPont(0)
end
