function QNO_EU_PRIEST_1()
  QUESTID = LuaGetQuestID("QNO_EU_PRIEST_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 23, 13)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_EU_PRIEST", "NPC_EU_GENERAL")
  LuaQuestInsertNpc(2, "NPC_EU_PRIEST", "NPC_EU_GENERAL")
  LuaInsertMissionOrCompleteNpc("NPC_EU_GENERAL")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDialLogMissionData(QUESTID, 0, MISSION_TYPE_DIALOG, "SN_CON_QNO_EU_PRIEST_1", 1, "SN_TALK_QNO_EU_PRIEST_1_05")
  InsertQuestMenuStringList("NPC_EU_PRIEST", 6, "BASIC_MENUSTRING_GREETING", "SN_NPC_EU_PRIEST_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_EU_PRIEST_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_EU_PRIEST_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_EU_PRIEST_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_EU_PRIEST_1_04", "BASIC_MENUSTRING_MIDDLE_ACHIEVED", "SN_TALK_QNO_EU_PRIEST_1_06")
  InsertQuestMenuStringList("NPC_EU_GENERAL", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_EU_GENERAL_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_EU_PRIEST_1_05")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 11100, 500, 800, 0, 0)
  LuaSetAchievedSkillPont(0)
end
