function QNO_CH_GENARAL_2()
  QUESTID = LuaGetQuestID("QNO_CH_GENARAL_2")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 13, 3)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CH_GENARAL")
  LuaInsertMissionOrCompleteNpc("NPC_CH_GENARAL")
  LuaInsertDependancyQuests(1, "QNO_CH_GENARAL_1")
  LuaQuestInsertNpc(1, "NPC_CH_GENARAL")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 3)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_CH_GENARAL_2_01", 1, "MOB_CH_TIGER", 1, MONSTER_CLASS_CHAMPION, 3, 1, 1)
  LuaSetMissionData_EX(QUESTID, 1, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_CH_GENARAL_2_02", 1, "MOB_CH_TIGER", 1, MONSTER_CLASS_NORMAL, 30, 1, 1)
  LuaSetMissionData_EX(QUESTID, 2, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_CH_GENARAL_2_03", 1, "MOB_CH_TIGER_CLON", 1, MONSTER_CLASS_NORMAL, 15, 1, 1)
  InsertQuestMenuStringList("NPC_CH_GENARAL", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_GENARAL_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_CH_GENARAL_2_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_CH_GENARAL_2_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_CH_GENARAL_2_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_CH_GENARAL_2_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_CH_GENARAL_2_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_CH_GENARAL_2_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 19680, 3200, 3600, 0, 0)
  LuaSetAchievedSkillPont(0)
end
