function QNO_JUPITER_SUB_039()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_039")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 118, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_SOLDIER_18")
  LuaQuestInsertNpc(1, "NPC_JUPITER_SOLDIER_18")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_SOLDIER_18")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_JUPITER_SUB_039_1", 9, "NPC_JUPITER_SOLDIER_18", 1, 50, "ITEM_QNO_JUPITER_SUB_039_1", "MOB_JUPITER_BAAL_DEVILDOG", 20, "MOB_JUPITER_BAAL_WATCHDOG", 20, "MOB_JUPITER_DEVIL_DARK", 20, "MOB_JUPITER_BLOOD_WITCH", 20, "MOB_JUPITER_DEVIL_HELL", 20, "MOB_JUPITER_CHARM_WITCH", 20, "MOB_JUPITER_DESIRE_WATCH", 20, "MOB_JUPITER_NIGHTMARE_SERPENT", 20, "MOB_JUPITER_FEAR_SERPENT", 20)
  InsertQuestMenuStringList("NPC_JUPITER_SOLDIER_18", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_18_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_039_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_039_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_039_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_039_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_039_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_039_06")
end
