function QNO_SD_GU_021()
  QUESTID = LuaGetQuestID("QNO_SD_GU_021")
  LuaSetStartCodition(3, QSC_QUEST, QSC_LEVEL, QSC_SYSTEM, 105, 105)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_GUILD_AGENT")
  LuaInsertMissionOrCompleteNpc("NPC_SD_GUILD_AGENT")
  LuaQuestInsertNpc(1, "NPC_SD_GUILD_AGENT")
  LuaSetAchievementLimit(1)
  LuaSetJobTypeStartCondition(1, OBJ_JOBSTATE_ROBBER, 1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetKillPlayerMissionData(QUESTID, 0, MISSION_TYPE_KILL_PLAYER, "SN_CON_QNO_SD_GU_021_1", 1, "NPC_SD_GUILD_AGENT", 100, 3, MKP_LEVEL, MKP_JOB, MKP_REGION, -32752, 105, 2, OBJ_JOBSTATE_TRADER, OBJ_JOBSTATE_HUNTER)
  InsertQuestMenuStringList("NPC_SD_GUILD_AGENT", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_GUILD_AGENT_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_GU_021_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_GU_021_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_GU_021_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_GU_021_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_GU_021_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_GU_021_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 5082584, 0, 60000000, ITEM_ETC_ARENA_COIN, 150)
  LuaSetAchievedSkillPont(20000)
  LuaSetAchievedPoint(600, "TEMPLE_ANUBIS")
end
