function QNO_JUPITER_SOLDIER_01_01()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SOLDIER_01_01")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 1, 1)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_SOLDIER_01")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_SOLDIER_01")
  LuaQuestInsertNpc(1, "NPC_JUPITER_SOLDIER_01")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SOLDIER_01_01", 8, "MOB_JUPITER_IMMOTAL_GRIFFIN", "MOB_JUPITER_DESPAIR_MINO", "MOB_JUPITER_ANATU_LION", "MOB_JUPITER_IMMOTAL_GUARD", "MOB_JUPITER_IMMOTAL_WATCH", "MOB_JUPITER_IMMOTAL_GRIFFIN_CONQUEROR", "MOB_JUPITER_IMMOTAL_GRIFFIN_GUARD", "MOB_JUPITER_ASHERAH_LION", 0, 2000, 0, 1)
  InsertQuestMenuStringList("NPC_JUPITER_SOLDIER_01", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_GUILD_AGENT2_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SOLDIER_01_01_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SOLDIER_01_01_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SOLDIER_01_01_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SOLDIER_01_01_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SOLDIER_01_01_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SOLDIER_01_01_06")
  LuaSetMissionCompleteNum(0)
  LuaSetAchievedItem(0, 10082584, 0, 100000000, ITEM_ETC_SD_TOKEN_01, 200)
end
