function QNO_KT_ACCESSORY_1()
  QUESTID = LuaGetQuestID("QNO_KT_ACCESSORY_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 65, 55)
  LuaSetLimitTimeStartCondition(120)
  LuaSetDifferentString(1)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_KT_ACCESSORY")
  LuaInsertMissionOrCompleteNpc("NPC_KT_ACCESSORY")
  LuaQuestInsertNpc(1, "NPC_KT_ACCESSORY")
  LuaSetAchievementLimit(3)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_KT_ACCESSORY_1", 2, "NPC_KT_ACCESSORY", 1, 20, "ITEM_QNO_KT_ACCESSORY_1_01", "MOB_TK_DEATHKARA_CLON", 10, "MOB_TK_DEATHKARA", 10)
  InsertQuestMenuStringList("NPC_KT_ACCESSORY", 9, "BASIC_MENUSTRING_GREETING", "SN_NPC_KT_ACCESSORY_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_KT_ACCESSORY_1_02", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_KT_ACCESSORY_1_03", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_KT_ACCESSORY_1_04", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_KT_ACCESSORY_1_05", "BASIC_MENUSTRING_ACCEPT_AFTER_ONE_CLEAR", "SN_TALK_QNO_KT_ACCESSORY_1_06", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_KT_ACCESSORY_1_08", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_KT_ACCESSORY_1_07", "BASIC_MENUSTRING_TIME_LIMIT_AUTO_ABORT", "SN_TALK_QNO_KT_ACCESSORY_1_09")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 3325000, 12500, 40000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
