function QNO_CH_SPECIAL_1()
  QUESTID = LuaGetQuestID("QNO_CH_SPECIAL_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 13, 3)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CH_SPECIAL")
  LuaInsertMissionOrCompleteNpc("NPC_CH_SPECIAL")
  LuaQuestInsertNpc(1, "NPC_CH_SPECIAL")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_CH_SPECIAL_1", 2, "NPC_CH_SPECIAL", 1, 7, "ITEM_QNO_CH_SPECIAL_1_01", "MOB_CH_TIGER", 10, "MOB_CH_TIGER_CLON", 10)
  InsertQuestMenuStringList("NPC_CH_SPECIAL", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_SPECIAL_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_CH_SPECIAL_1_02", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_CH_SPECIAL_1_03", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_CH_SPECIAL_1_04", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_CH_SPECIAL_1_05", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_CH_SPECIAL_1_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_CH_SPECIAL_1_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 33660, 5000, 4400, 0, 0)
  LuaSetAchievedSkillPont(0)
end
