function QNO_SD_RE_039()
  QUESTID = LuaGetQuestID("QNO_SD_RE_039")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 110, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_T_AREA_POTION")
  LuaInsertMissionOrCompleteNpc("NPC_SD_T_AREA_POTION")
  LuaQuestInsertNpc(1, "NPC_SD_T_AREA_POTION")
  LuaInsertDependancyQuests(1, "QNO_SD_RE_038")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_SD_RE_039_1", 1, "NPC_SD_T_AREA_POTION", 1, 30, "ITEM_QNO_SD_RE_039_1", "MOB_SD_DEVILWORM", 30)
  InsertQuestMenuStringList("NPC_SD_T_AREA_POTION", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_T_AREA_POTION_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_RE_039_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_RE_039_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_RE_039_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_RE_039_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_RE_039_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_RE_039_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 12550119, 0, 5118, 0)
  LuaSetAchievedSkillPont(2100)
end
