function QNO_JUPITER_SUB_005()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_005")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 113, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_SOLDIER_02")
  LuaQuestInsertNpc(1, "NPC_JUPITER_SOLDIER_02")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_SOLDIER_02")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_JUPITER_SUB_005_1", 1, "NPC_JUPITER_SOLDIER_02", 1, 100, "ITEM_QNO_JUPITER_SUB_005_1", "MOB_JUPITER_TEMPLE_LION", 25)
  InsertQuestMenuStringList("NPC_JUPITER_SOLDIER_02", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_02_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_005_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_005_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_005_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_005_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_005_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_005_06")
end
