function QNO_KT_PLUS_025()
  QUESTID = LuaGetQuestID("QNO_KT_PLUS_025")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 57, 52)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_KT_FERRY")
  LuaInsertMissionOrCompleteNpc("NPC_KT_FERRY")
  LuaQuestInsertNpc(1, "NPC_KT_FERRY")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_KT_PLUS_025_1", 1, "NPC_KT_FERRY", 1, 150, "ITEM_QNO_KT_PLUS_025_1", "MOB_KK_GWHITESPIDER_CLON", 50)
  InsertQuestMenuStringList("NPC_KT_FERRY", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_KT_FERRY_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_KT_PLUS_025_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_KT_PLUS_025_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_KT_PLUS_025_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_KT_PLUS_025_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_KT_PLUS_025_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_KT_PLUS_025_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 2148980, 20000, 90000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
