function QNO_WC_DOCTOR_2()
  QUESTID = LuaGetQuestID("QNO_WC_DOCTOR_2")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 22, 12)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_WC_DOCTOR")
  LuaInsertMissionOrCompleteNpc("NPC_WC_DOCTOR")
  LuaQuestInsertNpc(1, "NPC_WC_DOCTOR")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_WC_DOCTOR_2", 1, "NPC_WC_DOCTOR", 1, 70, "ITEM_QNO_WC_DOCTOR_2_01", "MOB_WC_DEVILBUG", 20)
  InsertQuestMenuStringList("NPC_WC_DOCTOR", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_WC_DOCTOR_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_WC_DOCTOR_2_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_WC_DOCTOR_2_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_WC_DOCTOR_2_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_WC_DOCTOR_2_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_WC_DOCTOR_2_05", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_WC_DOCTOR_2_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_WC_DOCTOR_2_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(1, 290400, 25000, 0, 1, "ITEM_QNO_WC_DOCTOR_2_02", 1)
  LuaSetAchievedSkillPont(0)
end
