function QNO_AM_FERRY1_2()
  QUESTID = LuaGetQuestID("QNO_AM_FERRY1_2")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 23, 13)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_AM_FERRY1", "NPC_EU_GENERAL")
  LuaQuestInsertNpc(2, "NPC_AM_FERRY1", "NPC_EU_GENERAL")
  LuaInsertMissionOrCompleteNpc("NPC_EU_GENERAL")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDeliverMissionData(QUESTID, 0, MISSION_TYPE_DELIVER_ITEM, "SN_CON_QNO_AM_FERRY1_2", "NPC_EU_GENERAL", 1, 1, "ITEM_QNO_AM_FERRY1_2_01", 1, "SN_TALK_QNO_AM_FERRY1_2_05")
  InsertQuestMenuStringList("NPC_AM_FERRY1", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_AM_FERRY1_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_AM_FERRY1_2_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_AM_FERRY1_2_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_AM_FERRY1_2_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_AM_FERRY1_2_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_AM_FERRY1_2_07", "BASIC_MENUSTRING_MIDDLE_ACHIEVED", "SN_TALK_QNO_AM_FERRY1_2_06")
  InsertQuestMenuStringList("NPC_EU_GENERAL", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_EU_GENERAL_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_AM_FERRY1_2_05")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 21830, 2100, 2700, 0, 0)
  LuaSetAchievedSkillPont(0)
end
