function QNO_KT_ARMOR_1()
  QUESTID = LuaGetQuestID("QNO_KT_ARMOR_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 51, 41)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_KT_ARMOR")
  LuaInsertMissionOrCompleteNpc("NPC_KT_ARMOR")
  LuaQuestInsertNpc(1, "NPC_KT_ARMOR")
  LuaSetAchievementLimit(1)
  LuaInsertDependancyQuests(1, "QNO_WC_ARMOR_1")
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_KT_ARMOR_1", 2, "NPC_KT_ARMOR", 1, 130, "ITEM_QNO_KT_ARMOR_1", "MOB_KK_ISHADE", 25, "MOB_KK_ISHADE_CLON", 25)
  InsertQuestMenuStringList("NPC_KT_ARMOR", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_KT_ARMOR_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_KT_ARMOR_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_KT_ARMOR_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_KT_ARMOR_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_KT_ARMOR_1_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_KT_ARMOR_1_05", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_KT_ARMOR_1_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_KT_ARMOR_1_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(1, 2286300, 0, 0, 1, "ITEM_ETC_ALL_SPOTION_01", 50)
  LuaSetAchievedSkillPont(0)
end
