function QNO_SD_MA_003()
  QUESTID = LuaGetQuestID("QNO_SD_MA_003")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 100, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_SD_M_AREA_MANETO", "NPC_SD_M_AREA_SENMUTE")
  LuaQuestInsertNpc(2, "NPC_SD_M_AREA_MANETO", "NPC_SD_M_AREA_SENMUTE")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_SENMUTE")
  LuaInsertDependancyQuests(1, "QNO_SD_MA_002")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDeliverMissionData(QUESTID, 0, MISSION_TYPE_DELIVER_ITEM, "SN_CON_QNO_SD_MA_003_1", "NPC_SD_M_AREA_SENMUTE", 1, 1, "ITEM_QNO_SD_MA_003_1", 1, "SN_TALK_QNO_SD_MA_003_06")
  InsertQuestMenuStringList("NPC_SD_M_AREA_MANETO", 6, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_MANETO_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_MA_003_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_MA_003_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_MA_003_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_MA_003_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_SD_MA_003_05")
  InsertQuestMenuStringList("NPC_SD_M_AREA_SENMUTE", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_SENMUTE_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_MA_003_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 9338467, 0, 2340, 0, 0)
  LuaSetAchievedSkillPont(1100)
end
