function QNO_SD_MA_010()
  QUESTID = LuaGetQuestID("QNO_SD_MA_010")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 101, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_SD_M_AREA_MANETO", "NPC_SD_M_AREA_SENMUTE")
  LuaQuestInsertNpc(2, "NPC_SD_M_AREA_MANETO", "NPC_SD_M_AREA_SENMUTE")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_SENMUTE")
  LuaInsertDependancyQuests(1, "QNO_SD_MA_009")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDialLogMissionData(QUESTID, 0, MISSION_TYPE_DIALOG, "SN_CON_QNO_SD_MA_010_1", 1, "SN_TALK_QNO_SD_MA_010_05")
  InsertQuestMenuStringList("NPC_SD_M_AREA_MANETO", 5, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_MANETO_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_MA_010_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_MA_010_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_MA_010_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_MA_010_04")
  InsertQuestMenuStringList("NPC_SD_M_AREA_SENMUTE", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_SENMUTE_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_MA_010_05")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 9618622, 0, 2362, 0, 0)
  LuaSetAchievedSkillPont(1200)
end
