function QNO_CA_THIEF_6_1()
  QUESTID = LuaGetQuestID("QNO_CA_THIEF_6_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 32, 21)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_CA_SPECIAL", "NPC_CA_HUNTER")
  LuaQuestInsertNpc(2, "NPC_CA_SPECIAL", "NPC_CA_HUNTER")
  LuaInsertMissionOrCompleteNpc("NPC_CA_HUNTER")
  LuaInsertDependancyQuests(1, "QNO_CA_THIEF_5")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDeliverMissionData(QUESTID, 0, MISSION_TYPE_DELIVER_ITEM, "SN_CON_QNO_CA_THIEF_6_1", "NPC_CA_HUNTER", 1, 10, "ITEM_QNO_CA_THIEF_2_01", 1, "SN_TALK_QNO_CA_THIEF_6_1_06")
  InsertQuestMenuStringList("NPC_CA_SPECIAL", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_CA_SPECIAL_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_CA_THIEF_6_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_CA_THIEF_6_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_CA_THIEF_6_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_CA_THIEF_6_1_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_CA_THIEF_6_1_05", "BASIC_MENUSTRING_MIDDLE_ACHIEVED", "SN_TALK_QNO_CA_THIEF_6_1_07")
  InsertQuestMenuStringList("NPC_CA_HUNTER", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_CA_HUNTER_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_CA_THIEF_6_1_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 120060, 4200, 10300, 0, 0)
  LuaSetAchievedSkillPont(0)
end
