function QNO_SD_RE_030()
  QUESTID = LuaGetQuestID("QNO_SD_RE_030")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 107, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_SD_M_AREA_MERCHANT", "NPC_SD_M_AREA_SMITH")
  LuaQuestInsertNpc(2, "NPC_SD_M_AREA_MERCHANT", "NPC_SD_M_AREA_SMITH")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_SMITH")
  LuaInsertDependancyQuests(1, "QNO_SD_RE_029")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDeliverMissionData(QUESTID, 0, MISSION_TYPE_DELIVER_ITEM, "SN_CON_QNO_SD_RE_030_1", "NPC_SD_M_AREA_SMITH", 1, 1, "ITEM_QNO_SD_RE_030_1", 1, "SN_TALK_QNO_SD_RE_030_06")
  InsertQuestMenuStringList("NPC_SD_M_AREA_MERCHANT", 6, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_MERCHANT_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_RE_030_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_RE_030_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_RE_030_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_RE_030_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_SD_RE_030_05")
  InsertQuestMenuStringList("NPC_SD_M_AREA_SMITH", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_SMITH_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_RE_030_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 5742568, 0, 2493, 0, 0)
  LuaSetAchievedSkillPont(1300)
end
