function QNO_WC_SMITH_2()
  QUESTID = LuaGetQuestID("QNO_WC_SMITH_2")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 40, 30)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_WC_SMITH")
  LuaInsertMissionOrCompleteNpc("NPC_WC_SMITH")
  LuaInsertDependancyQuests(1, "QNO_WC_FERRY3_1")
  LuaQuestInsertNpc(1, "NPC_WC_SMITH")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_WC_SMITH_2", 2, "NPC_WC_SMITH", 1, 70, "ITEM_QNO_WC_SMITH_2_01", "MOB_OA_REDEYEGHOST", 20, "MOB_OA_REDEYEGHOST_CLON", 20)
  InsertQuestMenuStringList("NPC_WC_SMITH", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_WC_SMITH_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_WC_SMITH_2_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_WC_SMITH_2_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_WC_SMITH_2_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_WC_SMITH_2_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_WC_SMITH_2_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_WC_SMITH_2_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 589300, 0, 0, 0, 0)
  LuaSetAchievedSkillPont(0)
end
