function QNO_JUPITER_MAIN_034()
  QUESTID = LuaGetQuestID("QNO_JUPITER_MAIN_034")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 113, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_JUPITER_SOLDIER_19", "NPC_JUPITER_SOLDIER_13")
  LuaQuestInsertNpc(2, "NPC_JUPITER_SOLDIER_19", "NPC_JUPITER_SOLDIER_13")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_SOLDIER_13")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDialLogMissionData(QUESTID, 0, MISSION_TYPE_DIALOG, "SN_CON_QNO_JUPITER_MAIN_034_1", 1, "SN_TALK_QNO_JUPITER_MAIN_034_05")
  InsertQuestMenuStringList("NPC_JUPITER_SOLDIER_19", 5, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_19_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_MAIN_034_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_MAIN_034_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_MAIN_034_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_MAIN_034_04")
  InsertQuestMenuStringList("NPC_JUPITER_SOLDIER_13", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_13_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_MAIN_034_05")
end
