function QNO_RM_OLDWOMAN_1()
  QUESTID = LuaGetQuestID("QNO_RM_OLDWOMAN_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 89, 79)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_RM_OLDWOMAN", "NPC_RM_VILLAGECHIEF")
  LuaQuestInsertNpc(2, "NPC_RM_OLDWOMAN", "NPC_RM_VILLAGECHIEF")
  LuaInsertMissionOrCompleteNpc("NPC_RM_VILLAGECHIEF")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDialLogMissionData(QUESTID, 0, MISSION_TYPE_DIALOG, "SN_CON_QNO_RM_OLDWOMAN_1", 1, "SN_TALK_QNO_RM_OLDWOMAN_1_05")
  InsertQuestMenuStringList("NPC_RM_OLDWOMAN", 6, "BASIC_MENUSTRING_GREETING", "SN_NPC_RM_OLDWOMAN_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_RM_OLDWOMAN_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_RM_OLDWOMAN_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_RM_OLDWOMAN_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_RM_OLDWOMAN_1_04", "BASIC_MENUSTRING_MIDDLE_ACHIEVED", "SN_TALK_QNO_RM_OLDWOMAN_1_06")
  InsertQuestMenuStringList("NPC_RM_VILLAGECHIEF", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_RM_VILLAGECHIEF_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_RM_OLDWOMAN_1_05")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 2634000, 0, 0, 0, 0)
  LuaSetAchievedSkillPont(0)
end
