function QNO_FW_BA1_009()
  QUESTID = LuaGetQuestID("QNO_FW_BA1_009")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 83, 81)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_KT_MINISTER")
  LuaInsertMissionOrCompleteNpc("NPC_KT_MINISTER")
  LuaQuestInsertNpc(1, "NPC_KT_MINISTER")
  LuaSetAchievementLimit(1)
  LuaSetDivideType(5)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_FW_BA1_009_1", 4, "MOB_GOD_FLAME_GIGANTIC_B1", "MOB_GOD_FLAME_GIGANTIC_B2", "MOB_GOD_FLAME_GIGANTIC_B3", "MOB_GOD_FLAME_GIGANTIC_B4", 0, 120, 0, 1)
  InsertQuestMenuStringList("NPC_KT_MINISTER", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_KT_MINISTER_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_FW_BA1_009_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_FW_BA1_009_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_FW_BA1_009_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_FW_BA1_009_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_FW_BA1_009_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_FW_BA1_009_06")
  LuaSetMissionCompleteNum(0)
end
