function QNO_SD_NO_030()
  QUESTID = LuaGetQuestID("QNO_SD_NO_030")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 104, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_SD_M_AREA_POTION", "NPC_SD_M_AREA_HORSE")
  LuaQuestInsertNpc(2, "NPC_SD_M_AREA_POTION", "NPC_SD_M_AREA_HORSE")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_HORSE")
  LuaInsertDependancyQuests(1, "QNO_SD_NO_029")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDeliverMissionData(QUESTID, 0, MISSION_TYPE_DELIVER_ITEM, "SN_CON_QNO_SD_NO_030_1", "NPC_SD_M_AREA_HORSE", 1, 1, "ITEM_QNO_SD_NO_030_1", 1, "SN_TALK_QNO_SD_NO_030_06")
  InsertQuestMenuStringList("NPC_SD_M_AREA_POTION", 6, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_POTION_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_NO_030_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_NO_030_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_NO_030_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_NO_030_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_SD_NO_030_05")
  InsertQuestMenuStringList("NPC_SD_M_AREA_HORSE", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_HORSE_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_NO_030_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 5255264, 0, 2428, 0, 0)
  LuaSetAchievedSkillPont(1000)
end
