function QNO_JUPITER_MAIN_029()
  QUESTID = LuaGetQuestID("QNO_JUPITER_MAIN_029")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 118, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_JUPITER_BELIEVER_05", "NPC_JUPITER_BELIEVER_07")
  LuaQuestInsertNpc(2, "NPC_JUPITER_BELIEVER_05", "NPC_JUPITER_BELIEVER_07")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_BELIEVER_07")
  LuaInsertDependancyQuests(1, "QNO_JUPITER_MAIN_028")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDialLogMissionData(QUESTID, 0, MISSION_TYPE_DIALOG, "SN_CON_QNO_JUPITER_MAIN_029_1", 1, "SN_TALK_QNO_JUPITER_MAIN_029_05")
  InsertQuestMenuStringList("NPC_JUPITER_BELIEVER_05", 5, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_BELIEVER_05_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_MAIN_029_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_MAIN_029_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_MAIN_029_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_MAIN_029_04")
  InsertQuestMenuStringList("NPC_JUPITER_BELIEVER_07", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_BELIEVER_07_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_MAIN_029_05")
end
