function QNO_SD_MA_024()
  QUESTID = LuaGetQuestID("QNO_SD_MA_024")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 108, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_M_AREA_LENENUNE")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_LENENUNE")
  LuaQuestInsertNpc(1, "NPC_SD_M_AREA_LENENUNE")
  LuaInsertDependancyQuests(1, "QNO_SD_MA_023")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 3)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_SD_MA_024_1", 1, "NPC_SD_M_AREA_LENENUNE", 1, 50, "ITEM_QNO_SD_MA_024_1", "MOB_SD_ACHNISH", 100)
  LuaSetCollectionItemMissionData(QUESTID, 1, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_SD_MA_024_2", 1, "NPC_SD_M_AREA_LENENUNE", 1, 50, "ITEM_QNO_SD_MA_024_2", "MOB_SD_SANDSTING", 100)
  LuaSetCollectionItemMissionData(QUESTID, 2, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_SD_MA_024_3", 1, "NPC_SD_M_AREA_LENENUNE", 1, 50, "ITEM_QNO_SD_MA_024_3", "MOB_SD_EVILBUG", 100)
  InsertQuestMenuStringList("NPC_SD_M_AREA_LENENUNE", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_LENENUNE_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_MA_024_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_MA_024_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_MA_024_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_MA_024_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_MA_024_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_MA_024_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 70978148, 0, 7546, 0, 0)
  LuaSetAchievedSkillPont(3900)
end
