function QNO_SD_MA_001()
  QUESTID = LuaGetQuestID("QNO_SD_MA_001")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 100, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_M_AREA_SENMUTE")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_SENMUTE")
  LuaQuestInsertNpc(1, "NPC_SD_M_AREA_SENMUTE")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_SD_MA_001_1", 1, "NPC_SD_M_AREA_SENMUTE", 1, 50, "ITEM_QNO_SD_MA_001_1", "MOB_SD_UNEG", 50)
  InsertQuestMenuStringList("NPC_SD_M_AREA_SENMUTE", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_SENMUTE_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_MA_001_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_MA_001_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_MA_001_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_MA_001_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_MA_001_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_MA_001_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 18676935, 0, 4681, 0)
  LuaSetAchievedSkillPont(2100)
end
