function QNO_SD_NO_041()
  QUESTID = LuaGetQuestID("QNO_SD_NO_041")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 106, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_M_AREA_SPECIAL")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_SPECIAL")
  LuaQuestInsertNpc(1, "NPC_SD_M_AREA_SPECIAL")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_SD_NO_041_1", 1, "NPC_SD_M_AREA_SPECIAL", 1, 30, "ITEM_QNO_SD_NO_041_1", "MOB_SD_SANDBUG", 30)
  InsertQuestMenuStringList("NPC_SD_M_AREA_SPECIAL", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_SPECIAL_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_NO_041_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_NO_041_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_NO_041_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_NO_041_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_NO_041_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_NO_041_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 11150619, 0, 4943, 0, 0)
  LuaSetAchievedSkillPont(1700)
end
