function QNO_CH_SOLDIER_EA2_1()
  QUESTID = LuaGetQuestID("QNO_CH_SOLDIER_EA2_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 7, 1)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CH_SOLDIER_EA2")
  LuaInsertMissionOrCompleteNpc("NPC_CH_SOLDIER_EA2")
  LuaQuestInsertNpc(1, "NPC_CH_SOLDIER_EA2")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_CH_SOLDIER_EA2_1", 2, "MOB_CH_STONEGHOST_CLON", "MOB_CH_STONEGHOST", 0, 20, 0, 1)
  InsertQuestMenuStringList("NPC_CH_SOLDIER_EA2", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_SOLDIER_EA2_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_CH_SOLDIER_EA2_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_CH_SOLDIER_EA2_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_CH_SOLDIER_EA2_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_CH_SOLDIER_EA2_1_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_CH_SOLDIER_EA2_1_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_CH_SOLDIER_EA2_1_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 6150, 0, 1900, 0, 0)
  LuaSetAchievedSkillPont(0)
end
