function QNO_JUPITER_SUB_031()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_031")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 115, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_SOLDIER_14")
  LuaQuestInsertNpc(1, "NPC_JUPITER_SOLDIER_14")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_SOLDIER_14")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_JUPITER_SUB_031_1", 2, "NPC_JUPITER_SOLDIER_14", 1, 1, "ITEM_QNO_JUPITER_SUB_031_1", "MOB_JUPITER_IMMOTAL_GUARD", 1, "MOB_JUPITER_IMMOTAL_WATCH", 1)
  InsertQuestMenuStringList("NPC_JUPITER_SOLDIER_14", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_14_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_031_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_031_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_031_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_031_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_031_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_031_06")
end
