function QNO_JUPITER_MAIN_008()
  QUESTID = LuaGetQuestID("QNO_JUPITER_MAIN_008")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 111, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_JUPITER_INVESTIGATION_04", "NPC_JUPITER_INVESTIGATION_05")
  LuaQuestInsertNpc(2, "NPC_JUPITER_INVESTIGATION_04", "NPC_JUPITER_INVESTIGATION_05")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_INVESTIGATION_05")
  LuaInsertDependancyQuests(1, "QNO_JUPITER_MAIN_007")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDeliverMissionData(QUESTID, 0, MISSION_TYPE_DELIVER_ITEM, "SN_CON_QNO_JUPITER_MAIN_008_1", "NPC_JUPITER_INVESTIGATION_05", 1, 1, "ITEM_QNO_JUPITER_MAIN_008_1", 1, "SN_TALK_QNO_JUPITER_MAIN_008_06")
  InsertQuestMenuStringList("NPC_JUPITER_INVESTIGATION_04", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_INVESTIGATION_04_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_MAIN_008_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_MAIN_008_02", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_JUPITER_MAIN_008_03", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_MAIN_008_04", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_MAIN_008_05", "BASIC_MENUSTRING_MIDDLE_ACHIEVED", "SN_TALK_QNO_JUPITER_MAIN_008_07")
  InsertQuestMenuStringList("NPC_JUPITER_INVESTIGATION_05", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_INVESTIGATION_05_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_MAIN_008_06")
end
