function QNO_RM_FLYSHIP1_1()
  QUESTID = LuaGetQuestID("QNO_RM_FLYSHIP1_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 82, 72)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_RM_FLYSHIP1")
  LuaInsertMissionOrCompleteNpc("NPC_RM_FLYSHIP1")
  LuaQuestInsertNpc(1, "NPC_RM_FLYSHIP1")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_RM_FLYSHIP1_1", 1, "NPC_RM_FLYSHIP1", 1, 100, "ITEM_QNO_RM_FLYSHIP1_1_01", "MOB_RM_ANTELOPE_CLON", 20)
  InsertQuestMenuStringList("NPC_RM_FLYSHIP1", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_RM_FLYSHIP1_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_RM_FLYSHIP1_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_RM_FLYSHIP1_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_RM_FLYSHIP1_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_RM_FLYSHIP1_1_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_RM_FLYSHIP1_1_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_RM_FLYSHIP1_1_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 11917400, 100000, 467000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
