function QNO_SD_GU_030()
  QUESTID = LuaGetQuestID("QNO_SD_GU_030")
  LuaSetStartCodition(3, QSC_QUEST, QSC_LEVEL, QSC_SYSTEM, 105, 105)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_GUILD_AGENT3")
  LuaInsertMissionOrCompleteNpc("NPC_SD_GUILD_AGENT3")
  LuaQuestInsertNpc(1, "NPC_SD_GUILD_AGENT3")
  LuaSetJobTypeStartCondition(1, OBJ_JOBSTATE_HUNTER, 1)
  LuaSetMissionDataSize(QUESTID, 2)
  LuaSetMissionData(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_SD_GU_030_1", 1, "MOB_SD_DEVIL_SANDMAN", 0, MONSTER_CLASS_NORMAL, 1000, 0)
  LuaSetMissionData(QUESTID, 1, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_SD_GU_030_2", 1, "MOB_SD_SELKION", 0, MONSTER_CLASS_NORMAL, 1000, 1)
  InsertQuestMenuStringList("NPC_SD_GUILD_AGENT3", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_GUILD_AGENT3_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_GU_030_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_GU_030_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_GU_030_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_GU_030_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_GU_030_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_GU_030_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 3247753, 0, 40000000, 0, 0)
  LuaSetAchievedSkillPont(750)
  LuaSetAchievedPoint(1000, "TEMPLE_HAROERIS")
end
