function QNO_TG_SLAYER()
  QUESTID = LuaGetQuestID("QNO_TG_SLAYER")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 1, 1)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CH_KISAENG3")
  LuaInsertMissionOrCompleteNpc("NPC_CH_KISAENG3")
  LuaQuestInsertNpc(1, "NPC_CH_KISAENG3")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_TG_SLAYER", 2, "MOB_CH_TIGERWOMAN", "MOB_CH_TIGERWOMAN_STR", 0, 20, 0, 1)
  InsertQuestMenuStringList("NPC_CH_KISAENG3", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_POTION_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_TG_SLAYER_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_TG_SLAYER_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_TG_SLAYER_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_TG_SLAYER_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_TG_SLAYER_05", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_TG_SLAYER_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_TG_SLAYER_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(1, 7200, 0, 0, 1, "ITEM_MALL_GLOBAL_CHATTING", 10)
  LuaSetAchievedSkillPont(0)
end
