function QNO_EU_SOLDIER_EA2_1()
  QUESTID = LuaGetQuestID("QNO_EU_SOLDIER_EA2_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 27, 17)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_EU_SOLDIER_EA2")
  LuaInsertMissionOrCompleteNpc("NPC_EU_SOLDIER_EA2")
  LuaQuestInsertNpc(1, "NPC_EU_SOLDIER_EA2")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 4)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_EU_SOLDIER_EA2_1_01", 1, "NPC_EU_SOLDIER_EA2", 1, 1, "ITEM_QNO_EU_SOLDIER_EA2_1_01", "MOB_AM_SOLDIER_CLON", 8)
  LuaSetCollectionItemMissionData(QUESTID, 1, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_EU_SOLDIER_EA2_1_02", 1, "NPC_EU_SOLDIER_EA2", 1, 1, "ITEM_QNO_EU_SOLDIER_EA2_1_02", "MOB_AM_SOLDIER_CLON", 8)
  LuaSetCollectionItemMissionData(QUESTID, 2, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_EU_SOLDIER_EA2_1_03", 1, "NPC_EU_SOLDIER_EA2", 1, 2, "ITEM_QNO_EU_SOLDIER_EA2_1_03", "MOB_AM_SOLDIER_CLON", 8)
  LuaSetCollectionItemMissionData(QUESTID, 3, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_EU_SOLDIER_EA2_1_04", 1, "NPC_EU_SOLDIER_EA2", 1, 2, "ITEM_QNO_EU_SOLDIER_EA2_1_04", "MOB_AM_SOLDIER_CLON", 8)
  InsertQuestMenuStringList("NPC_EU_SOLDIER_EA2", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_EU_SOLDIER_EA2_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_EU_SOLDIER_EA2_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_EU_SOLDIER_EA2_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_EU_SOLDIER_EA2_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_EU_SOLDIER_EA2_1_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_EU_SOLDIER_EA2_1_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_EU_SOLDIER_EA2_1_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 340000, 6000, 12000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
