function QNO_RM_SLAVE1_1()
  QUESTID = LuaGetQuestID("QNO_RM_SLAVE1_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 83, 73)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_RM_SLAVE1")
  LuaInsertMissionOrCompleteNpc("NPC_RM_SLAVE1")
  LuaQuestInsertNpc(1, "NPC_RM_SLAVE1")
  LuaSetAchievementLimit(3)
  LuaSetDifferentString(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_RM_SLAVE1_1", 1, "MOB_RM_ANTELOPE", 0, MONSTER_CLASS_NORMAL, 500, 0)
  InsertQuestMenuStringList("NPC_RM_SLAVE1", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_RM_SLAVE1_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_RM_SLAVE1_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_RM_SLAVE1_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_RM_SLAVE1_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_RM_SLAVE1_1_04", "BASIC_MENUSTRING_ACCEPT_AFTER_ONE_CLEAR", "SN_TALK_QNO_RM_SLAVE1_1_06", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_RM_SLAVE1_1_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_RM_SLAVE1_1_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 11532400, 0, 425000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
