function QNO_JUPITER_MAIN_026()
  QUESTID = LuaGetQuestID("QNO_JUPITER_MAIN_026")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 116, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_JUPITER_SOLDIER_17", "NPC_JUPITER_BELIEVER_04")
  LuaQuestInsertNpc(2, "NPC_JUPITER_SOLDIER_17", "NPC_JUPITER_BELIEVER_04")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_BELIEVER_04")
  LuaInsertDependancyQuests(1, "QNO_JUPITER_MAIN_025")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDialLogMissionData(QUESTID, 0, MISSION_TYPE_DIALOG, "SN_CON_QNO_JUPITER_MAIN_026_1", 1, "SN_TALK_QNO_JUPITER_MAIN_026_05")
  InsertQuestMenuStringList("NPC_JUPITER_SOLDIER_17", 5, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_17_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_MAIN_026_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_MAIN_026_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_MAIN_026_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_MAIN_026_04")
  InsertQuestMenuStringList("NPC_JUPITER_BELIEVER_04", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_BELIEVER_04_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_MAIN_026_05")
end
