function QNO_SD_NO_028()
  QUESTID = LuaGetQuestID("QNO_SD_NO_028")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 104, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_SD_M_AREA_HORSE", "NPC_SD_M_AREA_POTION")
  LuaQuestInsertNpc(2, "NPC_SD_M_AREA_HORSE", "NPC_SD_M_AREA_POTION")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_POTION")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDialLogMissionData(QUESTID, 0, MISSION_TYPE_DIALOG, "SN_CON_QNO_SD_NO_028_1", 1, "SN_TALK_QNO_SD_NO_028_05")
  InsertQuestMenuStringList("NPC_SD_M_AREA_HORSE", 5, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_HORSE_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_NO_028_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_NO_028_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_NO_028_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_NO_028_04")
  InsertQuestMenuStringList("NPC_SD_M_AREA_POTION", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_POTION_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_NO_028_05")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 5255264, 0, 2428, 0, 0)
  LuaSetAchievedSkillPont(1000)
end
