function QNO_AM_FERRY1_1()
  QUESTID = LuaGetQuestID("QNO_AM_FERRY1_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 23, 13)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_AM_FERRY1")
  LuaInsertMissionOrCompleteNpc("NPC_AM_FERRY1")
  LuaQuestInsertNpc(1, "NPC_AM_FERRY1")
  LuaSetAchievementLimit(3)
  LuaSetDifferentString(1)
  LuaSetMissionDataSize(QUESTID, 2)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_AM_FERRY1_1_01", 1, "MOB_AM_CRAB", 1, MONSTER_CLASS_NORMAL, 30, 1, 1)
  LuaSetMissionData_EX(QUESTID, 1, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_AM_FERRY1_1_02", 1, "MOB_AM_CRAB", 1, MONSTER_CLASS_CHAMPION, 10, 1, 1)
  InsertQuestMenuStringList("NPC_AM_FERRY1", 8, "BASIC_MENUSTRING_GREETING", "SN_QNO_AM_FERRY1_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_AM_FERRY1_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_AM_FERRY1_1_03", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_AM_FERRY1_1_04", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_AM_FERRY1_1_05", "BASIC_MENUSTRING_ACCEPT_AFTER_ONE_CLEAR", "SN_TALK_QNO_AM_FERRY1_1_02", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_AM_FERRY1_1_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_AM_FERRY1_1_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 176120, 0, 7000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
