function QNO_KT_PLUS_016()
  QUESTID = LuaGetQuestID("QNO_KT_PLUS_016")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 54, 49)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_KT_SPECIAL")
  LuaInsertMissionOrCompleteNpc("NPC_KT_SPECIAL")
  LuaQuestInsertNpc(1, "NPC_KT_SPECIAL")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_KT_PLUS_016_1", 1, "MOB_KK_PENON_F", 0, MONSTER_CLASS_NORMAL, 300, 0)
  InsertQuestMenuStringList("NPC_KT_SPECIAL", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_KT_SPECIAL_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_KT_PLUS_016_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_KT_PLUS_016_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_KT_PLUS_016_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_KT_PLUS_016_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_KT_PLUS_016_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_KT_PLUS_016_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 2148980, 25000, 85000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
