function QNO_CA_TREASURE_2()
  QUESTID = LuaGetQuestID("QNO_CA_TREASURE_2")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 33, 23)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CA_WAREHOUSE")
  LuaInsertMissionOrCompleteNpc("NPC_CA_WAREHOUSE")
  LuaQuestInsertNpc(1, "NPC_CA_WAREHOUSE")
  LuaSetAchievementLimit(1)
  LuaInsertDependancyQuests(1, "QNO_CA_TREASURE_1")
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_CA_TREASURE_2", 1, "NPC_CA_WAREHOUSE", 1, 20, "ITEM_QNO_CA_TREASURE_2_01", "MOB_CA_ONG_CLON", 20)
  InsertQuestMenuStringList("NPC_CA_WAREHOUSE", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_CA_WAREHOUSE_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_CA_TREASURE_2_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_CA_TREASURE_2_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_CA_TREASURE_2_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_CA_TREASURE_2_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_CA_TREASURE_2_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_CA_TREASURE_2_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 437700, 7500, 18000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
