function QNO_KT_PLUS_007()
  QUESTID = LuaGetQuestID("QNO_KT_PLUS_007")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 44, 39)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_KT_MINISTER")
  LuaInsertMissionOrCompleteNpc("NPC_KT_MINISTER")
  LuaQuestInsertNpc(1, "NPC_KT_MINISTER")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_KT_PLUS_007_1", 1, "NPC_KT_MINISTER", 1, 150, "ITEM_QNO_KT_PLUS_007_1", "MOB_KT_BUNWANG_CLON", 50)
  InsertQuestMenuStringList("NPC_KT_MINISTER", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_KT_MINISTER_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_KT_PLUS_007_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_KT_PLUS_007_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_KT_PLUS_007_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_KT_PLUS_007_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_KT_PLUS_007_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_KT_PLUS_007_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 953500, 15000, 79000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
