function QNO_SD_MA_026()
  QUESTID = LuaGetQuestID("QNO_SD_MA_026")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 109, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_M_AREA_LENENUNE")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_LENENUNE")
  LuaQuestInsertNpc(1, "NPC_SD_M_AREA_LENENUNE")
  LuaInsertDependancyQuests(1, "QNO_SD_MA_025")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_SD_MA_026_2", 1, "NPC_SD_M_AREA_LENENUNE", 1, 100, "ITEM_QNO_SD_MA_026_2", "MOB_SD_AKERU", 100)
  InsertQuestMenuStringList("NPC_SD_M_AREA_LENENUNE", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_LENENUNE_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_MA_026_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_MA_026_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_MA_026_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_MA_026_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_MA_026_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_MA_026_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 24369164, 0, 5075, 0, 0)
  LuaSetAchievedSkillPont(3000)
end
