function QNO_EU_EASTEU_13()
  QUESTID = LuaGetQuestID("QNO_EU_EASTEU_13")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 16, 6)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_EU_ADVENTURER")
  LuaInsertMissionOrCompleteNpc("NPC_EU_ADVENTURER")
  LuaInsertDependancyQuests(1, "QNO_EU_EASTEU_12")
  LuaQuestInsertNpc(1, "NPC_EU_ADVENTURER")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_EU_EASTEU_13", 1, "NPC_EU_ADVENTURER", 1, 20, "ITEM_QNO_EU_EASTEU_13_01", "MOB_EU_LADON", 14)
  InsertQuestMenuStringList("NPC_EU_ADVENTURER", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_EU_ADVENTURER_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_EU_EASTEU_13_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_EU_EASTEU_13_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_EU_EASTEU_13_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_EU_EASTEU_13_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_EU_EASTEU_13_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_EU_EASTEU_13_06")
  LuaSetMissionCompleteNum(1)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 77360, 12500, 0, 0, 0)
  LuaSetAchievedSkillPont(0)
end
