function QNO_SD_RE_033()
  QUESTID = LuaGetQuestID("QNO_SD_RE_033")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 108, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_M_AREA_AHHA")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_AHHA")
  LuaInsertDependancyQuests(1, "QNO_SD_RE_032")
  LuaQuestInsertNpc(1, "NPC_SD_M_AREA_AHHA")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_SD_RE_033_1", 1, "MOB_SD_COELACAN", 0, MONSTER_CLASS_NORMAL, 100, 0)
  InsertQuestMenuStringList("NPC_SD_M_AREA_AHHA", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_AHHA_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_RE_033_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_RE_033_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_RE_033_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_RE_033_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_RE_033_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_RE_033_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 11829691, 0, 5031, 0, 0)
  LuaSetAchievedSkillPont(1900)
end
