function QNO_EU_EASTEU_7()
  QUESTID = LuaGetQuestID("QNO_EU_EASTEU_7")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 14, 4)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_EU_WITCH")
  LuaInsertMissionOrCompleteNpc("NPC_EU_WITCH")
  LuaQuestInsertNpc(1, "NPC_EU_WITCH")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_EU_EASTEU_7", 1, "NPC_EU_WITCH", 1, 50, "ITEM_QNO_EU_EASTEU_7_01", "MOB_EU_LADON_CLON", 27)
  InsertQuestMenuStringList("NPC_EU_WITCH", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_EU_WITCH_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_EU_EASTEU_7_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_EU_EASTEU_7_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_EU_EASTEU_7_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_EU_EASTEU_7_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_EU_EASTEU_7_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_EU_EASTEU_7_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 87060, 12500, 14000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
