function QNO_FW_RS1_001()
  QUESTID = LuaGetQuestID("QNO_FW_RS1_001")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 110, 1)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_M_AREA_SENMUTE")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_SENMUTE")
  LuaQuestInsertNpc(1, "NPC_SD_M_AREA_SENMUTE")
  LuaSetAchievementLimit(1)
  LuaSetDivideType(5)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetTalismanMissionData(QUESTID, 0, MISSION_TYPE_TALISMANCOLLECTION, "SN_CON_QNO_FW_RS1_001_1", "NPC_SD_M_AREA_SENMUTE", "THEME_GOD_WRECK_BLAME_SEE", 1)
  InsertQuestMenuStringList("NPC_SD_M_AREA_SENMUTE", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_SENMUTE_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_FW_RS1_001_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_FW_RS1_001_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_FW_RS1_001_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_FW_RS1_001_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_FW_RS1_001_05", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_FW_RS1_001_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_FW_RS1_001_07")
  LuaSetMissionCompleteNum(0)
end
