function QNO_PGN_TALISMAN_ANUBIS()
  QUESTID = LuaGetQuestID("QNO_PGN_TALISMAN_ANUBIS")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 1, 1)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_M_AREA_SENMUTE")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_SENMUTE")
  LuaQuestInsertNpc(1, "NPC_SD_M_AREA_SENMUTE")
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_PGN_TALISMAN_ANUBIS", 1, "MOB_SD_ANUBIS", 0, 1, 0, 1)
  InsertQuestMenuStringList("NPC_SD_M_AREA_SENMUTE", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_POTION_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_PGN_TALISMAN_ANUBIS_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_PGN_TALISMAN_ANUBIS_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_PGN_TALISMAN_ANUBIS_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_PGN_TALISMAN_ANUBIS_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_PGN_TALISMAN_ANUBIS_05", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_PGN_TALISMAN_ANUBIS_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_PGN_TALISMAN_ANUBIS_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(1, 7200, 0, 0, 1, "ITEM_TALISMAN_WRECK_B_BROKEN_KEY", 1)
  LuaSetAchievedSkillPont(0)
end
