function QNO_FW_BA1_001()
  QUESTID = LuaGetQuestID("QNO_FW_BA1_001")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 90, 71)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_KT_MINISTER")
  LuaInsertMissionOrCompleteNpc("NPC_KT_MINISTER")
  LuaQuestInsertNpc(1, "NPC_KT_MINISTER")
  LuaSetAchievementLimit(1)
  LuaSetDivideType(5)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetTalismanMissionData(QUESTID, 0, MISSION_TYPE_TALISMANCOLLECTION, "SN_CON_QNO_FW_BA1_001_1", "NPC_KT_MINISTER", "THEME_GOD_FLAME_BURNING_ABYSS", 1)
  InsertQuestMenuStringList("NPC_KT_MINISTER", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_KT_MINISTER_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_FW_BA1_001_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_FW_BA1_001_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_FW_BA1_001_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_FW_BA1_001_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_FW_BA1_001_05", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_FW_BA1_001_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_FW_BA1_001_07")
  LuaSetMissionCompleteNum(0)
end
