function QNO_KT_PLUS_036()
  QUESTID = LuaGetQuestID("QNO_KT_PLUS_036")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 74, 69)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_KT_SOLDIER_EA2")
  LuaInsertMissionOrCompleteNpc("NPC_KT_SOLDIER_EA2")
  LuaQuestInsertNpc(1, "NPC_KT_SOLDIER_EA2")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_KT_PLUS_036_1", 1, "NPC_KT_SOLDIER_EA2", 1, 150, "ITEM_QNO_KT_PLUS_036_1", "MOB_TK_BONEHUNTER_CLON", 50)
  InsertQuestMenuStringList("NPC_KT_SOLDIER_EA2", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_KT_SOLDIER_EA2_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_KT_PLUS_036_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_KT_PLUS_036_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_KT_PLUS_036_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_KT_PLUS_036_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_KT_PLUS_036_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_KT_PLUS_036_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 14494000, 91000, 339000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
