function QNO_JUPITER_SUB_036()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_036")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 117, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_SOLDIER_17")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_SOLDIER_17")
  LuaQuestInsertNpc(1, "NPC_JUPITER_SOLDIER_17")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 2)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_036_1", 1, "MOB_JUPITER_VAMPIRE_DEVILDOG", 0, 50, 0, 1)
  LuaSetMissionData_EX(QUESTID, 1, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_036_2", 1, "MOB_JUPITER_VAMPIRE_WATCHDOG", 0, 50, 0, 1)
  InsertQuestMenuStringList("NPC_JUPITER_SOLDIER_17", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_17_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_036_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_036_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_036_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_036_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_036_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_036_06")
end
