function QNO_KT_PLUS_008()
  QUESTID = LuaGetQuestID("QNO_KT_PLUS_008")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 46, 41)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_KT_SOLDIER_SO2")
  LuaInsertMissionOrCompleteNpc("NPC_KT_SOLDIER_SO2")
  LuaQuestInsertNpc(1, "NPC_KT_SOLDIER_SO2")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_KT_PLUS_008_1", 1, "MOB_KT_DESERTTRUNKZ_CLON", 0, MONSTER_CLASS_NORMAL, 300, 0)
  InsertQuestMenuStringList("NPC_KT_SOLDIER_SO2", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_KT_SOLDIER_SO2_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_KT_PLUS_008_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_KT_PLUS_008_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_KT_PLUS_008_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_KT_PLUS_008_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_KT_PLUS_008_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_KT_PLUS_008_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 953500, 21000, 73000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
