function QNO_CH_SMITH_1()
  QUESTID = LuaGetQuestID("QNO_CH_SMITH_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 1, 1)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_CH_SMITH", "NPC_CH_SOLDIER_SO1")
  LuaQuestInsertNpc(2, "NPC_CH_SMITH", "NPC_CH_SOLDIER_SO1")
  LuaInsertMissionOrCompleteNpc("NPC_CH_SMITH")
  LuaInsertMissionNPC("NPC_CH_SOLDIER_SO1")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDeliverMissionData_EX(QUESTID, 0, MISSION_TYPE_DELIVER_ITEM, "SN_CON_QNO_CH_SMITH_1", "NPC_CH_SOLDIER_SO1", 0, 4, "SN_TALK_QNO_CH_SMITH_1_06", "SN_TALK_QNO_CH_SMITH_1_07", "SN_TALK_QNO_CH_SMITH_1_05", "", 1, 1, "ITEM_QNO_CH_SMITH_1", 0, "", 1, 0, 1, 0, 0, 0)
  InsertQuestMenuStringList("NPC_CH_SMITH", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_SMITH_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_CH_SMITH_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_CH_SMITH_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_CH_SMITH_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_CH_SMITH_1_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_CH_SMITH_1_08", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_CH_SMITH_1_09")
  InsertQuestMenuStringList("NPC_CH_SOLDIER_SO1", 1, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_SOLDIER_SO1_QS")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 270, 0, 205, 0, 0)
  LuaSetAchievedSkillPont(0)
end
