function QNO_SD_SU_009()
  QUESTID = LuaGetQuestID("QNO_SD_SU_009")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 102, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_M_AREA_EYPTSOLIDER_3")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_EYPTSOLIDER_3")
  LuaInsertDependancyQuests(1, "QNO_SD_SU_002")
  LuaQuestInsertNpc(1, "NPC_SD_M_AREA_EYPTSOLIDER_3")
  MISSION_TYPE_KILL_MONSTER = 2
  MONSTER_CLASS_CHAMPION = 1
  MONSTER_CLASS_NORMAL = 0
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_SD_SU_009_1", 1, "MOB_SD_DARKSCOUT", 0, MONSTER_CLASS_NORMAL, 500, 0)
  InsertQuestMenuStringList("NPC_SD_M_AREA_EYPTSOLIDER_3", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_EYPTSOLIDER_3_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_SU_009_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_SU_009_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_SU_009_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_SU_009_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_SU_009_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_SU_009_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 4953590, 0, 23843, 0, 0)
  LuaSetAchievedSkillPont(500)
end
