function QNO_CA_MERCHANT_1()
  QUESTID = LuaGetQuestID("QNO_CA_MERCHANT_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 38, 28)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CA_MERCHANT")
  LuaInsertMissionOrCompleteNpc("NPC_CA_MERCHANT")
  LuaQuestInsertNpc(1, "NPC_CA_MERCHANT")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_CA_MERCHANT_1", 1, "NPC_CA_MERCHANT", 1, 18, "ITEM_QNO_CA_MERCHANT_1_01", "MOB_CA_MONKEY", 10)
  InsertQuestMenuStringList("NPC_CA_MERCHANT", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_CA_MERCHANT_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_CA_MERCHANT_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_CA_MERCHANT_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_CA_MERCHANT_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_CA_MERCHANT_1_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_CA_MERCHANT_1_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_CA_MERCHANT_1_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 1005140, 12500, 30000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
