function QNO_JUPITER_SUB_088()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_088")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 120, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_BELIEVER_09")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_BELIEVER_09")
  LuaQuestInsertNpc(1, "NPC_JUPITER_BELIEVER_09")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 3)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_088_1", 1, "MOB_JUPITER_HELL_BLOODDOG_CLONE", 0, 150, 0, 1)
  LuaSetMissionData_EX(QUESTID, 1, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_088_2", 1, "MOB_JUPITER_HELL_BLOODWATCH_CLONE", 0, 150, 0, 1)
  LuaSetMissionData_EX(QUESTID, 2, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_088_3", 1, "MOB_JUPITER_DEMON_SERPENT_CLONE", 0, 150, 0, 1)
  InsertQuestMenuStringList("NPC_JUPITER_BELIEVER_09", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_BELIEVER_09_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_088_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_088_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_088_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_088_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_088_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_088_06")
end
