function QNO_JUPITER_SUB_043()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_043")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 120, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_BELIEVER_07")
  LuaQuestInsertNpc(1, "NPC_JUPITER_BELIEVER_07")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_BELIEVER_07")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_JUPITER_SUB_043_1", 1, "NPC_JUPITER_BELIEVER_07", 1, 1, "ITEM_QNO_JUPITER_SUB_043_1", "MOB_JUPITER_BAAL", 100)
  InsertQuestMenuStringList("NPC_JUPITER_BELIEVER_07", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_BELIEVER_07_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_043_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_043_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_043_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_043_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_043_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_043_06")
end
