function QNO_WC_GENARAL_SW_1()
  QUESTID = LuaGetQuestID("QNO_WC_GENARAL_SW_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 63, 53)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_WC_GENARAL_SW")
  LuaInsertMissionOrCompleteNpc("NPC_WC_GENARAL_SW")
  LuaQuestInsertNpc(1, "NPC_WC_GENARAL_SW")
  LuaSetDayOrNight(2)
  LuaStartDayLimit(5)
  LuaSetAchievementLimit(3)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_WC_GENARAL_SW_1", 2, "MOB_DH_WORKEARTHGHOST_CLON", "MOB_DH_WORKEARTHGHOST", 0, 500, 0, 1)
  InsertQuestMenuStringList("NPC_WC_GENARAL_SW", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_WC_GENARAL_SW_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_WC_GENARAL_SW_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_WC_GENARAL_SW_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_WC_GENARAL_SW_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_WC_GENARAL_SW_1_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_WC_GENARAL_SW_1_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_WC_GENARAL_SW_1_07", "BASIC_MENUSTRING_COUNT_LIMIT", "SN_TALK_QNO_WC_GENARAL_SW_1_05")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 5420100, 0, 250000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
