function QNO_EU_CONS_9()
  QUESTID = LuaGetQuestID("QNO_EU_CONS_9")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 8, 1)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_EU_UNION1")
  LuaInsertMissionOrCompleteNpc("NPC_EU_UNION1")
  LuaQuestInsertNpc(1, "NPC_EU_UNION1")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_EU_CONS_9", 1, "NPC_EU_UNION1", 1, 7, "ITEM_QNO_EU_CONS_9_01", "MOB_EU_BARPOLLE_CLON", 20)
  InsertQuestMenuStringList("NPC_EU_UNION1", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_EU_UNION1_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_EU_CONS_9_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_EU_CONS_9_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_EU_CONS_9_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_EU_CONS_9_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_EU_CONS_9_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_EU_CONS_9_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 10340, 2500, 2000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
