function QNO_CA_THIEF_3()
  QUESTID = LuaGetQuestID("QNO_CA_THIEF_3")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 31, 21)
  LuaSetDifferentString(1)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CA_HUNTER")
  LuaInsertMissionOrCompleteNpc("NPC_CA_HUNTER")
  LuaQuestInsertNpc(1, "NPC_CA_HUNTER")
  LuaSetAchievementLimit(3)
  LuaInsertDependancyQuests(1, "QNO_CA_THIEF_2")
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_CA_THIEF_3", 1, "NPC_CA_HUNTER", 1, 20, "ITEM_QNO_CA_THIEF_3_01", "MOB_CA_PERYTON_CLON", 20)
  InsertQuestMenuStringList("NPC_CA_HUNTER", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_CA_HUNTER_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_CA_THIEF_3_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_CA_THIEF_3_03", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_CA_THIEF_3_04", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_CA_THIEF_3_05", "BASIC_MENUSTRING_ACCEPT_AFTER_ONE_CLEAR", "SN_TALK_QNO_CA_THIEF_3_02", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_CA_THIEF_3_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_CA_THIEF_3_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 396500, 0, 15000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
