function QNO_SD_RE_032()
  QUESTID = LuaGetQuestID("QNO_SD_RE_032")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 108, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_SD_M_AREA_HUNTER", "NPC_SD_M_AREA_AHHA")
  LuaQuestInsertNpc(2, "NPC_SD_M_AREA_HUNTER", "NPC_SD_M_AREA_AHHA")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_AHHA")
  LuaInsertDependancyQuests(1, "QNO_SD_RE_013")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDialLogMissionData(QUESTID, 0, MISSION_TYPE_DIALOG, "SN_CON_QNO_SD_RE_032_1", 1, "SN_TALK_QNO_SD_RE_032_05")
  InsertQuestMenuStringList("NPC_SD_M_AREA_HUNTER", 5, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_HUNTER_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_RE_032_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_RE_032_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_RE_032_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_RE_032_04")
  InsertQuestMenuStringList("NPC_SD_M_AREA_AHHA", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_AHHA_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_RE_032_05")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 5914845, 0, 2515, 0, 0)
  LuaSetAchievedSkillPont(1400)
end
