function QNO_KT_WAREHOUSE_1()
  QUESTID = LuaGetQuestID("QNO_KT_WAREHOUSE_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 46, 36)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_KT_WAREHOUSE")
  LuaInsertMissionOrCompleteNpc("NPC_KT_WAREHOUSE")
  LuaQuestInsertNpc(1, "NPC_KT_WAREHOUSE")
  LuaSetAchievementLimit(3)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_KT_WAREHOUSE_1", 1, "MOB_KT_DESERTTRUNKZ_CLON", 0, MONSTER_CLASS_NORMAL, 500, 0)
  InsertQuestMenuStringList("NPC_KT_WAREHOUSE", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_KT_WAREHOUSE_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_KT_WAREHOUSE_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_KT_WAREHOUSE_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_KT_WAREHOUSE_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_KT_WAREHOUSE_1_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_KT_WAREHOUSE_1_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_KT_WAREHOUSE_1_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 900000, 0, 0, 0, 0)
  LuaSetAchievedSkillPont(0)
end
