function QNO_CA_POTION_1()
  QUESTID = LuaGetQuestID("QNO_CA_POTION_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 34, 24)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CA_POTION")
  LuaInsertMissionOrCompleteNpc("NPC_CA_POTION")
  LuaQuestInsertNpc(1, "NPC_CA_POTION")
  LuaSetAchievementLimit(3)
  LuaSetDifferentString(1)
  LuaSetMissionDataSize(QUESTID, 3)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_CA_POTION_1_01", 1, "MOB_CA_ONG", 1, MONSTER_CLASS_NORMAL, 25, 1, 1)
  LuaSetMissionData_EX(QUESTID, 1, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_CA_POTION_1_02", 1, "MOB_CA_ONG", 1, MONSTER_CLASS_CHAMPION, 10, 1, 1)
  LuaSetMissionData_EX(QUESTID, 2, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_CA_POTION_1_03", 1, "MOB_CA_ONG", 1, MONSTER_CLASS_GIANT, 1.5, 1, 1)
  InsertQuestMenuStringList("NPC_CA_POTION", 9, "BASIC_MENUSTRING_GREETING", "SN_NPC_CA_POTION_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_CA_POTION_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_CA_POTION_1_03", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_CA_POTION_1_04", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_CA_POTION_1_05", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_CA_POTION_1_08", "BASIC_MENUSTRING_ACCEPT_AFTER_ONE_CLEAR", "SN_TALK_QNO_CA_POTION_1_02", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_CA_POTION_1_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_CA_POTION_1_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(1, 190500, 0, 0, 1, "ITEM_QNO_CA_POTION_1_01", 1)
  LuaSetAchievedSkillPont(0)
end
