function QNO_CA_SPECIAL_1()
  QUESTID = LuaGetQuestID("QNO_CA_SPECIAL_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 36, 26)
  LuaSetDifferentString(1)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CA_SPECIAL")
  LuaInsertMissionOrCompleteNpc("NPC_CA_SPECIAL")
  LuaQuestInsertNpc(1, "NPC_CA_SPECIAL")
  LuaSetAchievementLimit(3)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_CA_SPECIAL_1", 1, "NPC_CA_SPECIAL", 1, 14, "ITEM_QNO_CA_SPECIAL_1_01", "MOB_CA_HUNARCHER", 10)
  InsertQuestMenuStringList("NPC_CA_SPECIAL", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_CA_SPECIAL_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_CA_SPECIAL_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_CA_SPECIAL_1_03", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_CA_SPECIAL_1_04", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_CA_SPECIAL_1_05", "BASIC_MENUSTRING_ACCEPT_AFTER_ONE_CLEAR", "SN_TALK_QNO_CA_SPECIAL_1_02", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_CA_SPECIAL_1_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_CA_SPECIAL_1_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 749250, 0, 23000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
