function QNO_JUPITER_MAIN_020()
  QUESTID = LuaGetQuestID("QNO_JUPITER_MAIN_020")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 113, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_EU_GENERAL", "NPC_JUPITER_INVESTIGATION_01")
  LuaQuestInsertNpc(2, "NPC_EU_GENERAL", "NPC_JUPITER_INVESTIGATION_01")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_INVESTIGATION_01")
  LuaInsertDependancyQuests(1, "QNO_JUPITER_MAIN_019")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDeliverMissionData(QUESTID, 0, MISSION_TYPE_DELIVER_ITEM, "SN_CON_QNO_JUPITER_MAIN_020_1", "NPC_JUPITER_INVESTIGATION_01", 1, 1, "ITEM_QNO_JUPITER_MAIN_020_1", 1, "SN_TALK_QNO_JUPITER_MAIN_020_06")
  InsertQuestMenuStringList("NPC_EU_GENERAL", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_EU_GENERAL_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_MAIN_020_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_MAIN_020_02", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_JUPITER_MAIN_020_03", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_MAIN_020_04", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_MAIN_020_05", "BASIC_MENUSTRING_MIDDLE_ACHIEVED", "SN_TALK_QNO_JUPITER_MAIN_020_07")
  InsertQuestMenuStringList("NPC_JUPITER_INVESTIGATION_01", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_INVESTIGATION_01_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_MAIN_020_06")
end
