function QNO_SD_GU_001()
  QUESTID = LuaGetQuestID("QNO_SD_GU_001")
  LuaSetStartCodition(3, QSC_QUEST, QSC_LEVEL, QSC_SYSTEM, 105, 105)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_SD_M_AREA_MERCHANT", "NPC_SD_GUILD_AGENT2")
  LuaQuestInsertNpc(2, "NPC_SD_M_AREA_MERCHANT", "NPC_SD_GUILD_AGENT2")
  LuaInsertMissionOrCompleteNpc("NPC_SD_GUILD_AGENT2")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetJobTypeStartCondition(1, OBJ_JOBSTATE_TRADER, 1)
  LuaSetDisableQuest(1)
  LuaSetDialLogMissionData(QUESTID, 0, MISSION_TYPE_DIALOG, "SN_CON_QNO_SD_GU_001_1", 1, "SN_TALK_QNO_SD_GU_001_05")
  InsertQuestMenuStringList("NPC_SD_M_AREA_MERCHANT", 5, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_MERCHANT_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_GU_001_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_GU_001_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_GU_001_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_GU_001_04")
  InsertQuestMenuStringList("NPC_SD_GUILD_AGENT2", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_GUILD_AGENT2_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_GU_001_05")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 5412921, 0, 2340, 0, 0)
  LuaSetAchievedSkillPont(1100)
end
