function QNO_JUPITER_SUB_003()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_003")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 112, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_SOLDIER_01")
  LuaQuestInsertNpc(1, "NPC_JUPITER_SOLDIER_01")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_SOLDIER_01")
  LuaInsertDependancyQuests(1, "QNO_JUPITER_SUB_002")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_JUPITER_SUB_003_1", 1, "NPC_JUPITER_SOLDIER_01", 1, 130, "ITEM_QNO_JUPITER_SUB_003_1", "MOB_JUPITER_TEMPLE_WATCH", 36)
  InsertQuestMenuStringList("NPC_JUPITER_SOLDIER_01", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_01_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_003_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_003_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_003_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_003_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_003_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_003_06")
end
