function QNO_WC_DOCTOR_3()
  QUESTID = LuaGetQuestID("QNO_WC_DOCTOR_3")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 35, 25)
  LuaSetDifferentString(1)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_WC_DOCTOR")
  LuaInsertMissionOrCompleteNpc("NPC_WC_DOCTOR")
  LuaQuestInsertNpc(1, "NPC_WC_DOCTOR")
  LuaSetAchievementLimit(3)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_WC_DOCTOR_3", 2, "NPC_WC_DOCTOR", 1, 200, "ITEM_QNO_WC_DOCTOR_3_01", "MOB_OA_YEOWA_CLON", 50, "MOB_OA_YEOWA", 50)
  InsertQuestMenuStringList("NPC_WC_DOCTOR", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_WC_DOCTOR_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_WC_DOCTOR_3_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_WC_DOCTOR_3_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_WC_DOCTOR_3_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_WC_DOCTOR_3_04", "BASIC_MENUSTRING_ACCEPT_AFTER_ONE_CLEAR", "SN_TALK_QNO_WC_DOCTOR_3_06", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_WC_DOCTOR_3_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_WC_DOCTOR_3_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 1782507, 0, 55200, 0, 0)
  LuaSetAchievedSkillPont(0)
end
