function QNO_TQ_BAEKRYOUNG_18()
  QUESTID = LuaGetQuestID("QNO_TQ_BAEKRYOUNG_18")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 100, 90)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_CH_MOONSHADOW", "NPC_CH_BEGGARBOY")
  LuaQuestInsertNpc(2, "NPC_CH_MOONSHADOW", "NPC_CH_BEGGARBOY")
  LuaInsertMissionOrCompleteNpc("NPC_CH_BEGGARBOY")
  LuaInsertDependancyQuests(1, "QNO_TQ_BAEKRYOUNG_17")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDeliverMissionData(QUESTID, 0, MISSION_TYPE_DELIVER_ITEM, "SN_CON_QNO_TQ_BAEKRYOUNG_18_01", "NPC_CH_BEGGARBOY", 1, 1, "ITEM_QNO_TQ_BAEKRYEONG_17_02", 1, "SN_TALK_QNO_TQ_BAEKRYEONG_18_06")
  InsertQuestMenuStringList("NPC_CH_MOONSHADOW", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_MOONSHADOW_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_TQ_BAEKRYEONG_18_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_TQ_BAEKRYEONG_18_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_TQ_BAEKRYEONG_18_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_TQ_BAEKRYEONG_18_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_TQ_BAEKRYEONG_18_05", "BASIC_MENUSTRING_MIDDLE_ACHIEVED", "SN_TALK_QNO_TQ_BAEKRYEONG_18_07")
  InsertQuestMenuStringList("NPC_CH_BEGGARBOY", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_BEGGARBOY_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_TQ_BAEKRYEONG_18_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 4865100, 10000, 0, 0, 0)
  LuaSetAchievedSkillPont(0)
end
