function QNO_KT_PLUS_038()
  QUESTID = LuaGetQuestID("QNO_KT_PLUS_038")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 79, 74)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_KT_SMITH")
  LuaInsertMissionOrCompleteNpc("NPC_KT_SMITH")
  LuaQuestInsertNpc(1, "NPC_KT_SMITH")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_KT_PLUS_038_1", 1, "NPC_KT_SMITH", 1, 70, "ITEM_QNO_KT_PLUS_038_1", "MOB_TK_BONEGENERAL_CLON", 25)
  InsertQuestMenuStringList("NPC_KT_SMITH", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_KT_SMITH_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_KT_PLUS_038_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_KT_PLUS_038_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_KT_PLUS_038_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_KT_PLUS_038_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_KT_PLUS_038_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_KT_PLUS_038_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 14494000, 91000, 339000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
