function QNO_JUPITER_MAIN_010()
  QUESTID = LuaGetQuestID("QNO_JUPITER_MAIN_010")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 120, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_SOLDIER_19")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_SOLDIER_19")
  LuaQuestInsertNpc(1, "NPC_JUPITER_SOLDIER_19")
  LuaInsertDependancyQuests(1, "QNO_JUPITER_MAIN_005")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_MAIN_010_1", 1, "MOB_JUPITER_THE_EARTH1", 0, 1, 0, 1)
  InsertQuestMenuStringList("NPC_JUPITER_SOLDIER_19", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_19_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_MAIN_010_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_MAIN_010_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_MAIN_010_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_MAIN_010_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_MAIN_010_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_MAIN_010_06")
end
