function QNO_SD_NO_011()
  QUESTID = LuaGetQuestID("QNO_SD_NO_011")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 101, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_SD_M_AREA_ACCESSORY", "NPC_SD_M_AREA_MANETO")
  LuaQuestInsertNpc(2, "NPC_SD_M_AREA_ACCESSORY", "NPC_SD_M_AREA_MANETO")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_MANETO")
  LuaInsertDependancyQuests(1, "QNO_SD_NO_010")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDeliverMissionData(QUESTID, 0, MISSION_TYPE_DELIVER_ITEM, "SN_CON_QNO_SD_NO_011_1", "NPC_SD_M_AREA_MANETO", 1, 1, "ITEM_QNO_SD_NO_011_1", 1, "SN_TALK_QNO_SD_NO_011_06")
  InsertQuestMenuStringList("NPC_SD_M_AREA_ACCESSORY", 6, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_ACCESSORY_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_NO_011_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_NO_011_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_NO_011_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_NO_011_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_SD_NO_011_05")
  InsertQuestMenuStringList("NPC_SD_M_AREA_MANETO", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_MANETO_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_NO_011_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 4809311, 0, 2362, 0, 0)
  LuaSetAchievedSkillPont(700)
end
