function QNO_TQ_BAEKRYOUNG_7()
  QUESTID = LuaGetQuestID("QNO_TQ_BAEKRYOUNG_7")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 98, 88)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_CH_BEGGARBOY", "NPC_CH_GENARAL_SP")
  LuaQuestInsertNpc(2, "NPC_CH_BEGGARBOY", "NPC_CH_GENARAL_SP")
  LuaInsertMissionOrCompleteNpc("NPC_CH_GENARAL_SP")
  LuaSetAchievementLimit(1)
  LuaInsertDependancyQuests(1, "QNO_TQ_BAEKRYOUNG_6")
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDialLogMissionData(QUESTID, 0, MISSION_TYPE_DIALOG, "SN_CON_QNO_TQ_BAEKRYOUNG_7_01", 1, "SN_TALK_QNO_TQ_BAEKRYEONG_7_05")
  InsertQuestMenuStringList("NPC_CH_BEGGARBOY", 6, "BASIC_MENUSTRING_GREETING", "SN_QNO_RM_OLDWOMAN_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_TQ_BAEKRYEONG_7_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_TQ_BAEKRYEONG_7_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_TQ_BAEKRYEONG_7_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_TQ_BAEKRYEONG_7_04", "BASIC_MENUSTRING_MIDDLE_ACHIEVED", "SN_TALK_QNO_TQ_BAEKRYEONG_7_06")
  InsertQuestMenuStringList("NPC_CH_GENARAL_SP", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_GENARAL_SP_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_TQ_BAEKRYEONG_7_05")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 4016100, 0, 0, 0, 0)
  LuaSetAchievedSkillPont(0)
end
