function QNO_SD_SU_028()
  QUESTID = LuaGetQuestID("QNO_SD_SU_028")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 109, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_M_AREA_EYPTSOLIDER_3")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_EYPTSOLIDER_3")
  LuaInsertDependancyQuests(1, "QNO_SD_SU_002")
  LuaQuestInsertNpc(1, "NPC_SD_M_AREA_EYPTSOLIDER_3")
  LuaSetDivideType(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_SD_SU_028_1", 1, "MOB_SD_SEKHMET_2", 0, MONSTER_CLASS_UNIQUE, 10, 0)
  InsertQuestMenuStringList("NPC_SD_M_AREA_EYPTSOLIDER_3", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_EYPTSOLIDER_3_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_SU_028_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_SU_028_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_SU_028_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_SU_028_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_SU_028_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_SU_028_06", "BASIC_MENUSTRING_NOT_PARTY", "SN_TALK_QNO_SD_SU_028_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 3655374, 0, 15225, 0, 0)
  LuaSetAchievedSkillPont(1150)
end
