function QNO_SD_RE_034()
  QUESTID = LuaGetQuestID("QNO_SD_RE_034")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 108, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_SD_M_AREA_AHHA", "NPC_SD_M_AREA_HUNTER")
  LuaQuestInsertNpc(2, "NPC_SD_M_AREA_AHHA", "NPC_SD_M_AREA_HUNTER")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_HUNTER")
  LuaInsertDependancyQuests(1, "QNO_SD_RE_033")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDeliverMissionData(QUESTID, 0, MISSION_TYPE_DELIVER_ITEM, "SN_CON_QNO_SD_RE_034_1", "NPC_SD_M_AREA_HUNTER", 1, 1, "ITEM_QNO_SD_RE_034_1", 1, "SN_TALK_QNO_SD_RE_034_06")
  InsertQuestMenuStringList("NPC_SD_M_AREA_AHHA", 6, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_AHHA_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_RE_034_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_RE_034_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_RE_034_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_RE_034_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_SD_RE_034_05")
  InsertQuestMenuStringList("NPC_SD_M_AREA_HUNTER", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_HUNTER_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_RE_034_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 5914845, 0, 2515, 0, 0)
  LuaSetAchievedSkillPont(1400)
end
