function QNO_SD_RE_035()
  QUESTID = LuaGetQuestID("QNO_SD_RE_035")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 109, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_M_AREA_HORSE")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_HORSE")
  LuaQuestInsertNpc(1, "NPC_SD_M_AREA_HORSE")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 2)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_SD_RE_035_1", 1, "NPC_SD_M_AREA_HORSE", 1, 30, "ITEM_QNO_SD_RE_035_1", "MOB_SD_AKERU", 50)
  LuaSetCollectionItemMissionData(QUESTID, 1, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_SD_RE_035_2", 1, "NPC_SD_M_AREA_HORSE", 1, 50, "ITEM_QNO_SD_RE_035_2", "MOB_SD_AKERU", 100)
  InsertQuestMenuStringList("NPC_SD_M_AREA_HORSE", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_HORSE_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_RE_035_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_RE_035_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_RE_035_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_RE_035_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_RE_035_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_RE_035_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 12184582, 0, 5075, 0, 0)
  LuaSetAchievedSkillPont(2000)
end
