function QNO_SD_RE_014()
  QUESTID = LuaGetQuestID("QNO_SD_RE_014")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 107, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_SD_M_AREA_SMITH", "NPC_SD_M_AREA_WAREHOUSE")
  LuaQuestInsertNpc(2, "NPC_SD_M_AREA_SMITH", "NPC_SD_M_AREA_WAREHOUSE")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_WAREHOUSE")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDialLogMissionData(QUESTID, 0, MISSION_TYPE_DIALOG, "SN_CON_QNO_SD_RE_014_1", 1, "SN_TALK_QNO_SD_RE_014_05")
  InsertQuestMenuStringList("NPC_SD_M_AREA_SMITH", 5, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_SMITH_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_RE_014_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_RE_014_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_RE_014_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_RE_014_04")
  InsertQuestMenuStringList("NPC_SD_M_AREA_WAREHOUSE", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_WAREHOUSE_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_RE_014_05")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 5742568, 0, 2493, 0, 0)
  LuaSetAchievedSkillPont(1300)
end
