function QNO_EU_EASTEU_18()
  QUESTID = LuaGetQuestID("QNO_EU_EASTEU_18")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 18, 8)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_EU_WITCH")
  LuaInsertMissionOrCompleteNpc("NPC_EU_WITCH")
  LuaQuestInsertNpc(1, "NPC_EU_WITCH")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_EU_EASTEU_18", 1, "MOB_EU_SIREN_CLON", 0, MONSTER_CLASS_NORMAL, 70, 0)
  InsertQuestMenuStringList("NPC_EU_WITCH", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_EU_WITCH_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_EU_EASTEU_18_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_EU_EASTEU_18_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_EU_EASTEU_18_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_EU_EASTEU_18_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_EU_EASTEU_18_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_EU_EASTEU_18_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 27480, 5000, 6500, 0, 0)
  LuaSetAchievedSkillPont(0)
end
