function QNO_EU_WAREHOUSE_1()
  QUESTID = LuaGetQuestID("QNO_EU_WAREHOUSE_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 21, 11)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_EU_WAREHOUSE")
  LuaInsertMissionOrCompleteNpc("NPC_EU_WAREHOUSE")
  LuaQuestInsertNpc(1, "NPC_EU_WAREHOUSE")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_EU_WAREHOUSE_1", 1, "NPC_EU_WAREHOUSE", 1, 20, "ITEM_QNO_EU_WAREHOUSE_1_01", "MOB_AM_CRAB_CLON", 25)
  InsertQuestMenuStringList("NPC_EU_WAREHOUSE", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_EU_WAREHOUSE_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_EU_WAREHOUSE_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_EU_WAREHOUSE_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_EU_WAREHOUSE_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_EU_WAREHOUSE_1_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_EU_WAREHOUSE_1_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_EU_WAREHOUSE_1_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 251100, 6700, 11000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
