function QNO_WC_SMITH_1()
  QUESTID = LuaGetQuestID("QNO_WC_SMITH_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 39, 29)
  LuaSetLimitTimeStartCondition(120)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_WC_SMITH")
  LuaInsertMissionOrCompleteNpc("NPC_WC_SMITH")
  LuaQuestInsertNpc(1, "NPC_WC_SMITH")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_WC_SMITH_1", 2, "MOB_OA_REDEYEGHOST_CLON", "MOB_OA_REDEYEGHOST", 0, 40, 0, 1)
  InsertQuestMenuStringList("NPC_WC_SMITH", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_WC_SMITH_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_WC_SMITH_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_WC_SMITH_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_WC_SMITH_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_WC_SMITH_1_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_WC_SMITH_1_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_WC_SMITH_1_06", "BASIC_MENUSTRING_TIME_LIMIT_AUTO_ABORT", "SN_TALK_QNO_WC_SMITH_1_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 135000, 0, 6000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
