function QNO_TQ_PRESENT_2()
  QUESTID = LuaGetQuestID("QNO_TQ_PRESENT_2")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 93, 83)
  LuaSetDifferentString(1)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CH_ISLAM")
  LuaInsertMissionOrCompleteNpc("NPC_CH_ISLAM")
  LuaQuestInsertNpc(1, "NPC_CH_ISLAM")
  LuaSetAchievementLimit(3)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_TQ_PRESENT_2_01", 1, "NPC_CH_ISLAM", 1, 20, "ITEM_QNO_TQ_PRESENT_2_01", "MOB_TQ_SNAKESLAVE_CLON", 4)
  InsertQuestMenuStringList("NPC_CH_ISLAM", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_ISLAM_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_TQ_PRESENT_2_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_TQ_PRESENT_2_03", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_TQ_PRESENT_2_04", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_TQ_PRESENT_2_05", "BASIC_MENUSTRING_ACCEPT_AFTER_ONE_CLEAR", "SN_TALK_QNO_TQ_PRESENT_2_02", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_TQ_PRESENT_2_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_TQ_PRESENT_2_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 5333400, 40000, 130000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
