function QNO_SD_NO_055()
  QUESTID = LuaGetQuestID("QNO_SD_NO_055")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 110, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_M_AREA_SPECIAL3")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_SPECIAL3")
  LuaQuestInsertNpc(1, "NPC_SD_M_AREA_SPECIAL3")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_SD_NO_055_1", 1, "NPC_SD_M_AREA_SPECIAL3", 1, 10, "ITEM_QNO_SD_NO_055_1", "MOB_SD_DEVILWORM", 10)
  InsertQuestMenuStringList("NPC_SD_M_AREA_SPECIAL3", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_SPECIAL3_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_NO_055_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_NO_055_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_NO_055_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_NO_055_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_NO_055_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_NO_055_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 12550119, 0, 5118, 0, 0)
  LuaSetAchievedSkillPont(2100)
end
