function QNO_TQ_BAEKRYOUNG_1()
  QUESTID = LuaGetQuestID("QNO_TQ_BAEKRYOUNG_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 98, 88)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_CH_BEGGARBOY", "NPC_CH_POTION")
  LuaQuestInsertNpc(2, "NPC_CH_BEGGARBOY", "NPC_CH_POTION")
  LuaInsertMissionOrCompleteNpc("NPC_CH_POTION")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDeliverMissionData(QUESTID, 0, MISSION_TYPE_DELIVER_ITEM, "SN_CON_QNO_TQ_BAEKRYOUNG_1_01", "NPC_CH_POTION", 1, 1, "ITEM_QNO_TQ_BAEKRYEONG_1_01", 1, "SN_TALK_QNO_TQ_BAEKRYEONG_1_06")
  InsertQuestMenuStringList("NPC_CH_BEGGARBOY", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_BEGGARBOY_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_TQ_BAEKRYEONG_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_TQ_BAEKRYEONG_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_TQ_BAEKRYEONG_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_TQ_BAEKRYEONG_1_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_TQ_BAEKRYEONG_1_05", "BASIC_MENUSTRING_MIDDLE_ACHIEVED", "SN_TALK_QNO_TQ_BAEKRYEONG_1_07")
  InsertQuestMenuStringList("NPC_CH_POTION", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_POTION_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_TQ_BAEKRYEONG_1_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 4016100, 0, 0, 0, 0)
  LuaSetAchievedSkillPont(0)
end
