function QNO_KT_PLUS_011()
  QUESTID = LuaGetQuestID("QNO_KT_PLUS_011")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 45, 40)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_KT_SPECIAL")
  LuaInsertMissionOrCompleteNpc("NPC_KT_SPECIAL")
  LuaQuestInsertNpc(1, "NPC_KT_SPECIAL")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_KT_PLUS_011_1", 1, "NPC_KT_SPECIAL", 1, 250, "ITEM_QNO_KT_PLUS_011_1", "MOB_KT_BUNWANG", 80)
  InsertQuestMenuStringList("NPC_KT_SPECIAL", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_KT_SPECIAL_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_KT_PLUS_011_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_KT_PLUS_011_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_KT_PLUS_011_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_KT_PLUS_011_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_KT_PLUS_011_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_KT_PLUS_011_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 953500, 20000, 74000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
