function QNO_CH_EUROPE_2()
  QUESTID = LuaGetQuestID("QNO_CH_EUROPE_2")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 17, 1)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CH_EUROPE")
  LuaInsertMissionOrCompleteNpc("NPC_CH_EUROPE")
  LuaQuestInsertNpc(1, "NPC_CH_EUROPE")
  LuaSetAchievementLimit(1)
  LuaInsertDependancyQuests(1, "QNO_CH_EUROPE_1")
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_CH_EUROPE_2", 1, "NPC_CH_EUROPE", 1, 40, "ITEM_QNO_CH_EUROPE_2_01", "MOB_CH_WHITETIGER_CLON", 20)
  InsertQuestMenuStringList("NPC_CH_EUROPE", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_EUROPE_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_CH_EUROPE_2_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_CH_EUROPE_2_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_CH_EUROPE_2_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_CH_EUROPE_2_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_CH_EUROPE_2_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_CH_EUROPE_2_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 132000, 15000, 15700, 0, 0)
  LuaSetAchievedSkillPont(0)
end
