function QNO_JUPITER_SUB_014()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_014")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 115, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_JUPITER_SOLDIER_03", "NPC_JUPITER_SOLDIER_05")
  LuaQuestInsertNpc(2, "NPC_JUPITER_SOLDIER_03", "NPC_JUPITER_SOLDIER_05")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_SOLDIER_05")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDialLogMissionData(QUESTID, 0, MISSION_TYPE_DIALOG, "SN_CON_QNO_JUPITER_SUB_014_1", 1, "SN_TALK_QNO_JUPITER_SUB_014_05")
  InsertQuestMenuStringList("NPC_JUPITER_SOLDIER_03", 5, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_03_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_014_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_014_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_014_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_014_04")
  InsertQuestMenuStringList("NPC_JUPITER_SOLDIER_05", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_05_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_014_05")
end
