function QNO_CH_GENARAL_SW_1()
  QUESTID = LuaGetQuestID("QNO_CH_GENARAL_SW_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 16, 6)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CH_GENARAL_SW")
  LuaInsertMissionOrCompleteNpc("NPC_CH_GENARAL_SW")
  LuaQuestInsertNpc(1, "NPC_CH_GENARAL_SW")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_CH_GENARAL_SW_1", 1, "NPC_CH_GENARAL_SW", 1, 1, "ITEM_QNO_CH_GENARAL_SW_1_01", "MOB_CH_BANDIT", 1.5)
  InsertQuestMenuStringList("NPC_CH_GENARAL_SW", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_GENARAL_SW_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_CH_GENARAL_SW_1_02", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_CH_GENARAL_SW_1_03", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_CH_GENARAL_SW_1_04", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_CH_GENARAL_SW_1_05", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_CH_GENARAL_SW_1_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_CH_GENARAL_SW_1_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 41360, 5000, 5050, 0, 0)
  LuaSetAchievedSkillPont(0)
end
