function QNO_EU_EASTEU_20()
  QUESTID = LuaGetQuestID("QNO_EU_EASTEU_20")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 19, 9)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_EU_WITCH")
  LuaInsertMissionOrCompleteNpc("NPC_EU_WITCH")
  LuaQuestInsertNpc(1, "NPC_EU_WITCH")
  LuaSetAchievementLimit(1)
  LuaInsertDependancyQuests(1, "QNO_EU_EASTEU_19")
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_EU_EASTEU_20", 1, "NPC_EU_WITCH", 1, 40, "ITEM_QNO_EU_EASTEU_20_01", "MOB_EU_LION", 25)
  InsertQuestMenuStringList("NPC_EU_WITCH", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_EU_WITCH_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_EU_EASTEU_20_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_EU_EASTEU_20_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_EU_EASTEU_20_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_EU_EASTEU_20_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_EU_EASTEU_20_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_EU_EASTEU_20_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 122580, 13400, 0, 0, 0)
  LuaSetAchievedSkillPont(0)
end
