function QNO_TQ_GREATBOW_1()
  QUESTID = LuaGetQuestID("QNO_TQ_GREATBOW_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 86, 76)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CH_SOLDIER_EA1")
  LuaInsertMissionOrCompleteNpc("NPC_CH_SOLDIER_EA1")
  LuaQuestInsertNpc(1, "NPC_CH_SOLDIER_EA1")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_TQ_GREATBOW_1_01", 1, "NPC_CH_SOLDIER_EA1", 1, 25, "ITEM_QNO_TQ_GREATBOW_1_01", "MOB_TQ_TOMBARCHER", 5)
  InsertQuestMenuStringList("NPC_CH_SOLDIER_EA1", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_SOLDIER_EA1_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_TQ_GREATBOW_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_TQ_GREATBOW_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_TQ_GREATBOW_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_TQ_GREATBOW_1_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_TQ_GREATBOW_1_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_TQ_GREATBOW_1_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 8332400, 30000, 150000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
