function QNO_JUPITER_MAIN_003()
  QUESTID = LuaGetQuestID("QNO_JUPITER_MAIN_003")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 113, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_INVESTIGATION_01")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_INVESTIGATION_01")
  LuaInsertDependancyQuests(1, "QNO_JUPITER_MAIN_002")
  LuaQuestInsertNpc(1, "NPC_JUPITER_INVESTIGATION_01")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 2)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_MAIN_003_1", 1, "MOB_JUPITER_TEMPLE_LION", 0, 200, 0, 1)
  LuaSetMissionData_EX(QUESTID, 1, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_MAIN_003_2", 1, "MOB_JUPITER_TEMPLE_BABYLION", 0, 300, 0, 1)
  InsertQuestMenuStringList("NPC_JUPITER_INVESTIGATION_01", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_INVESTIGATION_01_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_MAIN_003_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_MAIN_003_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_MAIN_003_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_MAIN_003_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_MAIN_003_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_MAIN_003_06")
end
