function QNO_RM_SLAVE1_4()
  QUESTID = LuaGetQuestID("QNO_RM_SLAVE1_4")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 85, 75)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_RM_SLAVE1", "NPC_RM_SLAVE2")
  LuaQuestInsertNpc(2, "NPC_RM_SLAVE1", "NPC_RM_SLAVE2")
  LuaInsertMissionOrCompleteNpc("NPC_RM_SLAVE2")
  LuaInsertDependancyQuests(1, "QNO_RM_SLAVE1_3")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDeliverMissionData(QUESTID, 0, MISSION_TYPE_DELIVER_ITEM, "SN_CON_QNO_RM_SLAVE1_4", "NPC_RM_SLAVE2", 1, 1, "ITEM_QNO_RM_SLAVE1_4_01", 1, "SN_TALK_QNO_RM_SLAVE1_4_06")
  InsertQuestMenuStringList("NPC_RM_SLAVE1", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_RM_SLAVE1_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_RM_SLAVE1_4_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_RM_SLAVE1_4_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_RM_SLAVE1_4_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_RM_SLAVE1_4_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_RM_SLAVE1_4_05", "BASIC_MENUSTRING_MIDDLE_ACHIEVED", "SN_TALK_QNO_RM_SLAVE1_4_07")
  InsertQuestMenuStringList("NPC_RM_SLAVE2", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_RM_SLAVE2_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_RM_SLAVE1_4_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 2609000, 0, 0, 0, 0)
  LuaSetAchievedSkillPont(0)
end
