function QNO_KT_PLUS_015()
  QUESTID = LuaGetQuestID("QNO_KT_PLUS_015")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 57, 52)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_KT_MINISTER")
  LuaInsertMissionOrCompleteNpc("NPC_KT_MINISTER")
  LuaQuestInsertNpc(1, "NPC_KT_MINISTER")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_KT_PLUS_015_1", 1, "MOB_KK_GWHITESPIDER_CLON", 0, MONSTER_CLASS_NORMAL, 300, 0)
  InsertQuestMenuStringList("NPC_KT_MINISTER", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_KT_MINISTER_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_KT_PLUS_015_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_KT_PLUS_015_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_KT_PLUS_015_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_KT_PLUS_015_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_KT_PLUS_015_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_KT_PLUS_015_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 2148980, 20000, 90000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
