function QNO_EU_CONS_5()
  QUESTID = LuaGetQuestID("QNO_EU_CONS_5")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 5, 1)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_EU_SPECIAL")
  LuaInsertMissionOrCompleteNpc("NPC_EU_SPECIAL")
  LuaQuestInsertNpc(1, "NPC_EU_SPECIAL")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_EU_CONS_5", 1, "MOB_EU_BARUSWOLF_CLON", 0, MONSTER_CLASS_NORMAL, 20, 0)
  InsertQuestMenuStringList("NPC_EU_SPECIAL", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_EU_SPECIAL_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_EU_CONS_5_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_EU_CONS_5_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_EU_CONS_5_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_EU_CONS_5_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_EU_CONS_5_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_EU_CONS_5_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 4160, 1500, 950, 0, 0)
  LuaSetAchievedSkillPont(0)
end
