function QNO_WC_FERRY2_1()
  QUESTID = LuaGetQuestID("QNO_WC_FERRY2_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 19, 9)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_WC_FERRY2")
  LuaInsertMissionOrCompleteNpc("NPC_WC_FERRY2")
  LuaQuestInsertNpc(1, "NPC_WC_FERRY2")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_WC_FERRY2_1", 2, "MOB_CH_CHAKJI_CLON", "MOB_CH_CHAKJI", 0, 420, 0, 1)
  InsertQuestMenuStringList("NPC_WC_FERRY2", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_WC_FERRY2_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_WC_FERRY2_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_WC_FERRY2_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_WC_FERRY2_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_WC_FERRY2_1_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_WC_FERRY2_1_05", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_WC_FERRY2_1_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_WC_FERRY2_1_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(1, 301920, 30000, 0, 1, "ITEM_QNO_WC_FERRY2_1_01", 1)
  LuaSetAchievedSkillPont(0)
end
