function QNO_TQ_HIREDSOLDIER_1()
  QUESTID = LuaGetQuestID("QNO_TQ_HIREDSOLDIER_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 81, 71)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CH_GENARAL")
  LuaInsertMissionOrCompleteNpc("NPC_CH_GENARAL")
  LuaQuestInsertNpc(1, "NPC_CH_GENARAL")
  LuaSetAchievementLimit(3)
  LuaSetDifferentString(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_TQ_HIREDSOLDIER_1_01", 1, "MOB_TQ_QINSHITOMBSTONE_CLON2", 0, MONSTER_CLASS_NORMAL, 300, 0)
  InsertQuestMenuStringList("NPC_CH_GENARAL", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_GENARAL_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_TQ_HIREDSOLDIER_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_TQ_HIREDSOLDIER_1_03", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_TQ_HIREDSOLDIER_1_04", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_TQ_HIREDSOLDIER_1_05", "BASIC_MENUSTRING_ACCEPT_AFTER_ONE_CLEAR", "SN_TALK_QNO_TQ_HIREDSOLDIER_1_02", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_TQ_HIREDSOLDIER_1_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_TQ_HIREDSOLDIER_1_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 2520000, 0, 70000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
