function QNO_JUPITER_SUB_060()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_060")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 112, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_SOLDIER_20")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_SOLDIER_20")
  LuaQuestInsertNpc(1, "NPC_JUPITER_SOLDIER_20")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 2)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_060_1", 1, "MOB_JUPITER_TEMPLE_WATCH_CLONE", 0, 250, 0, 1)
  LuaSetMissionData_EX(QUESTID, 1, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_060_2", 1, "MOB_JUPITER_TEMPLE_GUARD_CLONE", 0, 250, 0, 1)
  InsertQuestMenuStringList("NPC_JUPITER_SOLDIER_20", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_20_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_060_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_060_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_060_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_060_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_060_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_060_06")
end
