function QNO_JUPITER_MAIN_012()
  QUESTID = LuaGetQuestID("QNO_JUPITER_MAIN_012")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 114, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_SOLDIER_13")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_SOLDIER_13")
  LuaQuestInsertNpc(1, "NPC_JUPITER_SOLDIER_13")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 2)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_MAIN_012_1", 1, "MOB_JUPITER_ANATU_LION", 0, 10, 0, 1)
  LuaSetMissionData_EX(QUESTID, 1, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_MAIN_012_2", 1, "MOB_JUPITER_ASHERAH_LION", 0, 30, 0, 1)
  InsertQuestMenuStringList("NPC_JUPITER_SOLDIER_13", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_13_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_MAIN_012_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_MAIN_012_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_MAIN_012_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_MAIN_012_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_MAIN_012_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_MAIN_012_06")
end
