function QNO_WC_GENARAL_SW_2()
  QUESTID = LuaGetQuestID("QNO_WC_GENARAL_SW_2")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 36, 26)
  LuaSetDifferentString(1)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_WC_GENARAL_SW")
  LuaInsertMissionOrCompleteNpc("NPC_WC_GENARAL_SW")
  LuaQuestInsertNpc(1, "NPC_WC_GENARAL_SW")
  LuaSetAchievementLimit(3)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_WC_GENARAL_SW_2", 1, "NPC_WC_GENARAL_SW", 1, 100, "ITEM_QNO_WC_GENARAL_SW_2_01", "MOB_OA_BLACKROBBERARCHER", 20)
  InsertQuestMenuStringList("NPC_WC_GENARAL_SW", 8, "BASIC_MENUSTRING_GREETING", "SN_NPC_WC_GENARAL_SW_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_WC_GENARAL_SW_2_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_WC_GENARAL_SW_2_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_WC_GENARAL_SW_2_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_WC_GENARAL_SW_2_04", "BASIC_MENUSTRING_ACCEPT_AFTER_ONE_CLEAR", "SN_TALK_QNO_WC_GENARAL_SW_2_06", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_WC_GENARAL_SW_2_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_WC_GENARAL_SW_2_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 3527000, 50000, 94000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
