function QNO_JUPITER_SUB_028()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_028")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 115, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_INVESTIGATION_06")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_INVESTIGATION_06")
  LuaQuestInsertNpc(1, "NPC_JUPITER_INVESTIGATION_06")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 3)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_028_1", 1, "MOB_JUPITER_IMMOTAL_PROTECTION", 0, 30, 0, 1)
  LuaSetMissionData_EX(QUESTID, 1, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_028_2", 1, "MOB_JUPITER_IMMOTAL_GUARD", 0, 40, 0, 1)
  LuaSetMissionData_EX(QUESTID, 2, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_028_3", 1, "MOB_JUPITER_IMMOTAL_WATCH", 0, 40, 0, 1)
  InsertQuestMenuStringList("NPC_JUPITER_INVESTIGATION_06", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_INVESTIGATION_06_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_028_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_028_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_028_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_028_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_028_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_028_06")
end
