function QNO_WC_POTION_1()
  QUESTID = LuaGetQuestID("QNO_WC_POTION_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 19, 9)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_WC_POTION")
  LuaInsertMissionOrCompleteNpc("NPC_WC_POTION")
  LuaQuestInsertNpc(1, "NPC_WC_POTION")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_WC_POTION_1", 2, "NPC_WC_POTION", 1, 10, "ITEM_QNO_WC_POTION_1", "MOB_WC_GHOSTBUG", 33, "MOB_WC_DEVILBUG", 33)
  InsertQuestMenuStringList("NPC_WC_POTION", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_WC_POTION_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_WC_POTION_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_WC_POTION_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_WC_POTION_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_WC_POTION_1_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_WC_POTION_1_06", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_WC_POTION_1_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 23740, 0, 3800, 0, 0)
  LuaSetAchievedSkillPont(0)
end
