function QNO_EU_GENERAL_5()
  QUESTID = LuaGetQuestID("QNO_EU_GENERAL_5")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 25, 14)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_EU_GENERAL", "NPC_EU_WITCH")
  LuaQuestInsertNpc(2, "NPC_EU_GENERAL", "NPC_EU_WITCH")
  LuaInsertMissionOrCompleteNpc("NPC_EU_WITCH")
  LuaInsertDependancyQuests(1, "QNO_EU_GENERAL_4")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDeliverMissionData(QUESTID, 0, MISSION_TYPE_DELIVER_ITEM, "SN_CON_QNO_EU_GENERAL_5", "NPC_EU_WITCH", 1, 60, "ITEM_QNO_EU_GENERAL_5_01", 1, "SN_TALK_QNO_EU_GENERAL_5_06")
  InsertQuestMenuStringList("NPC_EU_GENERAL", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_EU_GENERAL_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_EU_GENERAL_5_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_EU_GENERAL_5_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_EU_GENERAL_5_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_EU_GENERAL_5_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_EU_GENERAL_5_05", "BASIC_MENUSTRING_MIDDLE_ACHIEVED", "SN_TALK_QNO_EU_GENERAL_5_07")
  InsertQuestMenuStringList("NPC_EU_WITCH", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_EU_WITCH_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_EU_GENERAL_5_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 17390, 800, 1300, 0, 0)
  LuaSetAchievedSkillPont(0)
end
