function QNO_RM_VILLAGECHIEF_1()
  QUESTID = LuaGetQuestID("QNO_RM_VILLAGECHIEF_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 70, 60)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_RM_VILLAGECHIEF")
  LuaInsertMissionOrCompleteNpc("NPC_RM_VILLAGECHIEF")
  LuaQuestInsertNpc(1, "NPC_RM_VILLAGECHIEF")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 2)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_RM_VILLAGECHIEF_1_01", 1, "NPC_RM_VILLAGECHIEF", 1, 150, "ITEM_QNO_RM_VILLAGECHIEF_1_01", "MOB_RM_FEATHERMASK_CLON", 50)
  LuaSetCollectionItemMissionData(QUESTID, 1, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_RM_VILLAGECHIEF_1_02", 1, "NPC_RM_VILLAGECHIEF", 1, 100, "ITEM_QNO_RM_VILLAGECHIEF_1_02", "MOB_RM_FEATHERMASK_CLON", 50)
  InsertQuestMenuStringList("NPC_RM_VILLAGECHIEF", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_RM_VILLAGECHIEF_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_RM_VILLAGECHIEF_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_RM_VILLAGECHIEF_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_RM_VILLAGECHIEF_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_RM_VILLAGECHIEF_1_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_RM_VILLAGECHIEF_1_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_RM_VILLAGECHIEF_1_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 14375300, 50000, 240000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
