function QNO_TQ_STONEBOARD_5()
  QUESTID = LuaGetQuestID("QNO_TQ_STONEBOARD_5")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 90, 80)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_CH_SHAMAN", "NPC_CH_GENARAL_SW")
  LuaQuestInsertNpc(2, "NPC_CH_SHAMAN", "NPC_CH_GENARAL_SW")
  LuaInsertMissionOrCompleteNpc("NPC_CH_GENARAL_SW")
  LuaInsertDependancyQuests(1, "QNO_TQ_STONEBOARD_4")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDeliverMissionData(QUESTID, 0, MISSION_TYPE_DELIVER_ITEM, "SN_CON_QNO_TQ_STONEBOARD_5_01", "NPC_CH_GENARAL_SW", 1, 1, "ITEM_QNO_TQ_STONEBOARD_5_01", 1, "SN_TALK_QNO_TQ_STONEBOARD_5_07")
  InsertQuestMenuStringList("NPC_CH_SHAMAN", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_SHAMAN_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_TQ_STONEBOARD_5_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_TQ_STONEBOARD_5_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_TQ_STONEBOARD_5_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_TQ_STONEBOARD_5_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_TQ_STONEBOARD_5_05", "BASIC_MENUSTRING_MIDDLE_ACHIEVED", "SN_TALK_QNO_TQ_STONEBOARD_5_08")
  InsertQuestMenuStringList("NPC_CH_GENARAL_SW", 3, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_GENARAL_SW_QS", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_TQ_STONEBOARD_5_06", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_TQ_STONEBOARD_5_07")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(1, 2601000, 0, 0, 1, "ITEM_QNO_TQ_STONEBOARD_5_02", 1)
  LuaSetAchievedSkillPont(0)
end
