function QNO_JUPITER_SUB_084()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_084")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 119, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_BELIEVER_09")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_BELIEVER_09")
  LuaQuestInsertNpc(1, "NPC_JUPITER_BELIEVER_09")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 2)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_084_1", 1, "MOB_JUPITER_VAMPIRE_WATCHDOG_CLONE", 0, 250, 0, 1)
  LuaSetMissionData_EX(QUESTID, 1, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_084_2", 1, "MOB_JUPITER_HELL_ENCHANTRESS_CLONE", 0, 250, 0, 1)
  InsertQuestMenuStringList("NPC_JUPITER_BELIEVER_09", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_BELIEVER_09_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_084_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_084_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_084_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_084_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_084_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_084_06")
end
