function QNO_SD_GU_032()
  QUESTID = LuaGetQuestID("QNO_SD_GU_032")
  LuaSetStartCodition(3, QSC_QUEST, QSC_LEVEL, QSC_SYSTEM, 105, 105)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_SD_GUILD_AGENT3")
  LuaInsertMissionOrCompleteNpc("NPC_SD_GUILD_AGENT3")
  LuaQuestInsertNpc(1, "NPC_SD_GUILD_AGENT3")
  LuaSetJobTypeStartCondition(1, OBJ_JOBSTATE_HUNTER, 1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_SD_GU_032_1", 21, "NPC_SD_GUILD_AGENT3", 1, 250, "ITEM_QNO_SD_GU_032_1", "MOB_SD_PRIEST_GUARD", 30, "MOB_SD_PRIEST_POWER", 30, "MOB_SD_PRIEST_HEALING", 30, "MOB_SD_PRIEST_GALE", 30, "MOB_SD_PRIEST_FLAME", 30, "MOB_SD_PRIEST_FEAR", 30, "MOB_SD_IMOUTHES", 30, "MOB_SD_PRIEST_REVENGE", 30, "MOB_SD_PRIEST_CHASTISEMENT", 30, "MOB_SD_SPECTOR_GREED", 30, "MOB_SD_SPECTOR_DEMOLITION", 30, "MOB_SD_BLOODKHEPRI", 30, "MOB_SD_DEVIL_SANDMAN", 30, "MOB_SD_SEPTU", 30, "MOB_SD_SOPEDU", 30, "MOB_SD_PETBE", 30, "MOB_SD_SELKION", 30, "MOB_SD_KEISAS_BERSERK", 30, "MOB_SD_HARSAPHETH", 30, "MOB_SD_HARSMESS", 30, "MOB_SD_SANDSCOUT", 30)
  InsertQuestMenuStringList("NPC_SD_GUILD_AGENT3", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_GUILD_AGENT3_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_GU_032_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_GU_032_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_GU_032_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_GU_032_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_GU_032_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_SD_GU_032_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 5412921, 0, 60000000, 0, 0)
  LuaSetAchievedSkillPont(800)
  LuaSetAchievedPoint(300, "TEMPLE_HAROERIS")
end
