function QNO_SD_RE_013()
  QUESTID = LuaGetQuestID("QNO_SD_RE_013")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 106, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_SD_M_AREA_HORSE", "NPC_SD_M_AREA_HUNTER")
  LuaQuestInsertNpc(2, "NPC_SD_M_AREA_HORSE", "NPC_SD_M_AREA_HUNTER")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_HUNTER")
  LuaInsertDependancyQuests(1, "QNO_SD_RE_012")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDeliverMissionData(QUESTID, 0, MISSION_TYPE_DELIVER_ITEM, "SN_CON_QNO_SD_RE_013_1", "NPC_SD_M_AREA_HUNTER", 1, 1, "ITEM_QNO_SD_RE_013_1", 1, "SN_TALK_QNO_SD_RE_013_06")
  InsertQuestMenuStringList("NPC_SD_M_AREA_HORSE", 6, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_HORSE_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_RE_013_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_RE_013_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_RE_013_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_RE_013_04", "BASIC_MENUSTRING_INVENTORY_FULL", "SN_TALK_QNO_SD_RE_013_05")
  InsertQuestMenuStringList("NPC_SD_M_AREA_HUNTER", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_HUNTER_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_RE_013_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 5575309, 0, 2471, 0, 0)
  LuaSetAchievedSkillPont(1200)
end
