function QNO_JUPITER_SUB_007()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_007")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 115, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_SOLDIER_04")
  LuaQuestInsertNpc(1, "NPC_JUPITER_SOLDIER_04")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_SOLDIER_04")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 3)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_JUPITER_SUB_007_1", 1, "NPC_JUPITER_SOLDIER_04", 1, 40, "ITEM_QNO_JUPITER_SUB_007_1", "MOB_JUPITER_FIRE_PROTECTION", 26)
  LuaSetCollectionItemMissionData(QUESTID, 1, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_JUPITER_SUB_007_2", 1, "NPC_JUPITER_SOLDIER_04", 1, 40, "ITEM_QNO_JUPITER_SUB_007_2", "MOB_JUPITER_WATER_PROTECTION", 26)
  LuaSetCollectionItemMissionData(QUESTID, 2, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_JUPITER_SUB_007_3", 1, "NPC_JUPITER_SOLDIER_04", 1, 40, "ITEM_QNO_JUPITER_SUB_007_3", "MOB_JUPITER_SOUL_PROTECTION", 26)
  InsertQuestMenuStringList("NPC_JUPITER_SOLDIER_04", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_04_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_007_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_007_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_007_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_007_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_007_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_007_06")
end
