function QNO_CH_GENARAL_BO_2()
  QUESTID = LuaGetQuestID("QNO_CH_GENARAL_BO_2")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 11, 1)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CH_GENARAL_BO")
  LuaInsertMissionOrCompleteNpc("NPC_CH_GENARAL_BO")
  LuaQuestInsertNpc(1, "NPC_CH_GENARAL_BO")
  LuaSetAchievementLimit(1)
  LuaInsertDependancyQuests(1, "QNO_CH_GENARAL_BO_1")
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_CH_GENARAL_BO_2", 2, "NPC_CH_GENARAL_BO", 1, 14, "ITEM_QNO_CH_GENARAL_BO_2_01", "MOB_CH_BANDITARCHER", 10, "MOB_CH_BANDITARCHER_CLON", 10)
  InsertQuestMenuStringList("NPC_CH_GENARAL_BO", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_GENARAL_BO_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_CH_GENARAL_BO_2_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_CH_GENARAL_BO_2_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_CH_GENARAL_BO_2_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_CH_GENARAL_BO_2_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_CH_GENARAL_BO_2_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_CH_GENARAL_BO_2_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 59280, 10000, 8300, 0, 0)
  LuaSetAchievedSkillPont(0)
end
