function QNO_JUPITER_SUB_029()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_029")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 115, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_INVESTIGATION_06")
  LuaQuestInsertNpc(1, "NPC_JUPITER_INVESTIGATION_06")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_INVESTIGATION_06")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_JUPITER_SUB_029_1", 6, "NPC_JUPITER_INVESTIGATION_06", 1, 50, "ITEM_QNO_JUPITER_SUB_029_1", "MOB_JUPITER_ANATU_LION", 25, "MOB_JUPITER_IMMOTAL_GUARD", 25, "MOB_JUPITER_IMMOTAL_WATCH", 25, "MOB_JUPITER_IMMOTAL_PROTECTION", 25, "MOB_JUPITER_ASHERAH_LION", 25, "MOB_JUPITER_DESPAIR_MINO", 25)
  InsertQuestMenuStringList("NPC_JUPITER_INVESTIGATION_06", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_INVESTIGATION_06_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_029_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_029_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_029_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_029_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_029_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_029_06")
end
