function QNO_SD_NO_001()
  QUESTID = LuaGetQuestID("QNO_SD_NO_001")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 100, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_SD_M_AREA_LIGHTHOUSE", "NPC_SD_M_AREA_SENMUTE")
  LuaQuestInsertNpc(2, "NPC_SD_M_AREA_LIGHTHOUSE", "NPC_SD_M_AREA_SENMUTE")
  LuaInsertMissionOrCompleteNpc("NPC_SD_M_AREA_SENMUTE")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDialLogMissionData(QUESTID, 0, MISSION_TYPE_DIALOG, "SN_CON_QNO_SD_NO_001_1", 1, "SN_TALK_QNO_SD_NO_001_05")
  InsertQuestMenuStringList("NPC_SD_M_AREA_LIGHTHOUSE", 5, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_LIGHTHOUSE_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_SD_NO_001_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_SD_NO_001_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_SD_NO_001_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_SD_NO_001_04")
  InsertQuestMenuStringList("NPC_SD_M_AREA_SENMUTE", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_SD_M_AREA_SENMUTE_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_SD_NO_001_05")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 4669234, 0, 2340, 0, 0)
  LuaSetAchievedSkillPont(600)
end
