function QNO_WC_GENARAL_SP_1()
  QUESTID = LuaGetQuestID("QNO_WC_GENARAL_SP_1")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 61, 51)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_WC_GENARAL_SP")
  LuaInsertMissionOrCompleteNpc("NPC_WC_GENARAL_SP")
  LuaQuestInsertNpc(1, "NPC_WC_GENARAL_SP")
  LuaSetAchievementLimit(3)
  LuaSetMissionDataSize(QUESTID, 2)
  LuaSetCollectionItemMissionData_EX(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_WC_GENARAL_SP_1", 2, "NPC_WC_GENARAL_SP", 1, 15, "ITEM_QNO_WC_GENARAL_SP_1_01", "MOB_DH_BUGGHOST", 5, "MOB_DH_BUGGHOST_CLON", 1, 1, 0, 0, 0, 0, 0)
  LuaSetCollectionItemMissionData_EX(QUESTID, 1, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "", 2, "NPC_WC_GENARAL_SP", 1, 15, "ITEM_QNO_WC_GENARAL_SP_1_02", "MOB_DH_BUGGHOST", 50, "MOB_DH_BUGGHOST_CLON", 25, 0, 1, 0, 0, 0, 0)
  InsertQuestMenuStringList("NPC_WC_GENARAL_SP", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_WC_GENARAL_SP_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_WC_GENARAL_SP_1_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_WC_GENARAL_SP_1_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_WC_GENARAL_SP_1_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_WC_GENARAL_SP_1_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_WC_GENARAL_SP_1_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_WC_GENARAL_SP_1_06")
  LuaSetMissionCompleteNum(1)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 5420100, 0, 0, 0, 0)
  LuaSetAchievedSkillPont(0)
end
