function QNO_JUPITER_MAIN_001()
  QUESTID = LuaGetQuestID("QNO_JUPITER_MAIN_001")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 111, 111)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 2, "NPC_EU_GENERAL", "NPC_JUPITER_INVESTIGATION_01")
  LuaQuestInsertNpc(2, "NPC_EU_GENERAL", "NPC_JUPITER_INVESTIGATION_01")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_INVESTIGATION_01")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetDialLogMissionData(QUESTID, 0, MISSION_TYPE_DIALOG, "SN_CON_QNO_JUPITER_MAIN_001_1", 1, "SN_TALK_QNO_JUPITER_MAIN_001_05")
  InsertQuestMenuStringList("NPC_EU_GENERAL", 5, "BASIC_MENUSTRING_GREETING", "SN_NPC_EU_GENERAL_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_MAIN_001_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_MAIN_001_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_MAIN_001_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_MAIN_001_04")
  InsertQuestMenuStringList("NPC_JUPITER_INVESTIGATION_01", 2, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_INVESTIGATION_01_QS", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_MAIN_001_05")
end
