function QNO_JUPITER_SUB_035()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_035")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 118, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_BELIEVER_01")
  LuaQuestInsertNpc(1, "NPC_JUPITER_BELIEVER_01")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_BELIEVER_01")
  LuaSetAchievementLimit(1)
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_JUPITER_SUB_035_1", 2, "NPC_JUPITER_BELIEVER_01", 1, 20, "ITEM_QNO_JUPITER_SUB_035_1", "MOB_JUPITER_BLOOD_WITCH2", 10, "MOB_JUPITER_CHARM_WITCH2", 10)
  InsertQuestMenuStringList("NPC_JUPITER_BELIEVER_01", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_BELIEVER_01_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_035_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_035_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_035_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_035_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_035_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_035_06")
end
