function QNO_TQ_FINDFRIEND_4()
  QUESTID = LuaGetQuestID("QNO_TQ_FINDFRIEND_4")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 85, 74)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_CH_KISAENG5")
  LuaInsertMissionOrCompleteNpc("NPC_CH_KISAENG5")
  LuaQuestInsertNpc(1, "NPC_CH_KISAENG5")
  LuaSetAchievementLimit(1)
  LuaInsertDependancyQuests(1, "QNO_TQ_FINDFRIEND_3")
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetMissionData(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_TQ_FINDFRIEND_4_01", 1, "MOB_TQ_TOMBARCHER_CLON", 0, MONSTER_CLASS_NORMAL, 500, 0)
  InsertQuestMenuStringList("NPC_CH_KISAENG5", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_CH_KISAENG5_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_TQ_FINDFRIEND_4_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_TQ_FINDFRIEND_4_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_TQ_FINDFRIEND_4_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_TQ_FINDFRIEND_4_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_TQ_FINDFRIEND_4_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_TQ_FINDFRIEND_4_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 8002400, 50000, 240000, 0, 0)
  LuaSetAchievedSkillPont(0)
end
