function QNO_EU_EASTEU_16()
  QUESTID = LuaGetQuestID("QNO_EU_EASTEU_16")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 17, 7)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_EU_GENERAL")
  LuaInsertMissionOrCompleteNpc("NPC_EU_GENERAL")
  LuaQuestInsertNpc(1, "NPC_EU_GENERAL")
  LuaSetAchievementLimit(1)
  LuaInsertDependancyQuests(1, "QNO_EU_EASTEU_15")
  LuaSetMissionDataSize(QUESTID, 1)
  LuaSetCollectionItemMissionData(QUESTID, 0, MISSION_TYPE_GATHER_ITEM_FROM_MONSTER, "SN_CON_QNO_EU_EASTEU_16", 1, "NPC_EU_GENERAL", 1, 1, "ITEM_QNO_EU_EASTEU_16_01", "MOB_EU_LION_CLON", 1)
  InsertQuestMenuStringList("NPC_EU_GENERAL", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_EU_GENERAL_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_EU_EASTEU_16_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_EU_EASTEU_16_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_EU_EASTEU_16_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_EU_EASTEU_16_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_EU_EASTEU_16_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_EU_EASTEU_16_06")
  LuaSetMissionCompleteNum(0)
  PAY_ITEM_METHOD_EXACT = 1
  LuaSetAchievedItem(0, 88000, 10000, 12600, 0, 0)
  LuaSetAchievedSkillPont(0)
end
