function QNO_JUPITER_SUB_054()
  QUESTID = LuaGetQuestID("QNO_JUPITER_SUB_054")
  LuaSetStartCodition(2, QSC_QUEST, QSC_LEVEL, 119, 100)
  QM_CONVERSATION = 1
  LuaSetStartMethod(QM_CONVERSATION, 1, "NPC_JUPITER_SOLDIER_01")
  LuaInsertMissionOrCompleteNpc("NPC_JUPITER_SOLDIER_01")
  LuaQuestInsertNpc(1, "NPC_JUPITER_SOLDIER_01")
  LuaInsertDependancyQuests(1, "QNO_JUPITER_SUB_021")
  LuaSetAchievementLimit(0)
  LuaSetMissionDataSize(QUESTID, 2)
  LuaSetMissionData_EX(QUESTID, 0, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_054_1", 1, "MOB_JUPITER_HELL_WATCH", 0, 250, 0, 1)
  LuaSetMissionData_EX(QUESTID, 1, MISSION_TYPE_KILL_MONSTER, "SN_CON_QNO_JUPITER_SUB_054_2", 1, "MOB_JUPITER_HELL_PROTECTION", 0, 250, 0, 1)
  InsertQuestMenuStringList("NPC_JUPITER_SOLDIER_01", 7, "BASIC_MENUSTRING_GREETING", "SN_NPC_JUPITER_SOLDIER_01_QS", "BASIC_MENUSTRING_REQUEST_ACCEPT_QUEST", "SN_TALK_QNO_JUPITER_SUB_054_01", "BASIC_MENUSTRING_AT_ACCEPT", "SN_TALK_QNO_JUPITER_SUB_054_02", "BASIC_MENUSTRING_AT_DENY", "SN_TALK_QNO_JUPITER_SUB_054_03", "BASIC_MENUSTRING_NOT_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_054_04", "BASIC_MENUSTRING_ACHIEVED", "SN_TALK_QNO_JUPITER_SUB_054_05", "BASIC_MENUSTRING_ACHIEVED_NOW", "SN_TALK_QNO_JUPITER_SUB_054_06")
end
